### ISSUE TITLE
esta feisima esa aplicacion

### ISSUE THREAD

**Issue by popepatas** [popepatas/Situr#1]
tenaz la barba del man
![screenshot_3](https://cloud.githubusercontent.com/assets/10553595/11036603/960e5936-86c7-11e5-94f4-67aa703ce332.png)

**Comment by popepatas** [comment]
no no me parece

**Comment by popepatas** [comment]
se cierra el bug

**Comment by popepatas** [comment]
no sigue fallando

**Comment by popepatas** [comment]
re-abierto para Estepfany

**Comment by Estepfany** [comment]
se cierra el issues de prueba

**Comment by JPDH** [comment]
0la khe aze ?
