### ISSUE TITLE
Diseño - icono

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#100]
Se debe modificar el favicon o icono de pagina ya que el actual no corresponde a SItur
![1](https://cloud.githubusercontent.com/assets/15731914/11567118/6aea9a0e-99b3-11e5-9454-d25e9796df33.png)

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
