### ISSUE TITLE
Actualizar establecimiento 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#101]
Al momento de especificar los números telefónicos esta permitiendo el ingreso de caracteres alfanuméricos, solo se debe permitir caracteres numéricos 
![1](https://cloud.githubusercontent.com/assets/15731914/11569849/1e46b00c-99c2-11e5-8355-de15d9cb9d7c.png)

**Comment by AndresTello** [comment]
Resuelto.
Se configura el campo para permita digitar solamente numeros

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
