### ISSUE TITLE
Logueo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#103]
El fin de contar con la opción "Entrar" siempre visible es poder realizar el proceso de logueo en cualquier pantalla en la que se encuentre pero esta solo esta funcionando en la pantalla de inicio, ademas la pantalla emergente "Ingresa a tu cuenta" no se puede acceder en la pantalla "Experiencias y aventuras", en las demas pantallas se puede visualizar pero no realiza el proceso de logueo a la aplicación
![1](https://cloud.githubusercontent.com/assets/15731914/11630736/c5428c98-9ccc-11e5-957c-b4400ac5bb70.png)

**Comment by EverHidalgo** [comment]
se replico para que desde cualquier pantalla permitida para cuando un usuario no esta logueado se pueda loguear y realiazar el proceso de olvido de contraseña
