### ISSUE TITLE
Creación de oferta

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#107]
Al indicar esta opción de "Configurar oferta" se muestra solo los botones del formulario, no se muestran los campos necesarios para crear una oferta, esta prueba se realizo con el usuario CLEO el cual es adminET, se debe verificar el funcionamiento con otros usuario del mismo rol
![1](https://cloud.githubusercontent.com/assets/15731914/11719785/507f0f0c-9f2a-11e5-8030-9e8a4e9d525e.png)

**Comment by AndresTello** [comment]
Este caso se presenta debido a que el establecimiento fue creado con categoría restaurante y aun no se ha definido la configuración de campos en la documentación para ofertas para esta categoría.

**Comment by Estepfany** [comment]
Se cierra por lo indicado por el desarrollador
