### ISSUE TITLE
Diseño - icono de galeria

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#111]
en el navegador Explorer no se visualiza el icono de galería de manera correcta
![1](https://cloud.githubusercontent.com/assets/15731914/11725473/d7e9d4e6-9f47-11e5-887c-c33b0569e1ff.png)

**Comment by ChristiaanGuzman** [comment]
esto es un problema que presenta  el navegador explorer, ya que la imagen esta bien en resolucion

**Comment by Estepfany** [comment]
Se cierra, pero se debe tener en cuenta que este icono no se vera bien en todos los navegadores
