### ISSUE TITLE
Diseño - imagenes de servicio

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#112]
Al seleccionar un establecimiento, se visualiza la información del establecimiento (Hotel) y entre esta información se cuenta con los servicios, la cual se indica por medio de imágenes, estas están muy juntas, de igual forma aparecen en todos los navegadores
![1](https://cloud.githubusercontent.com/assets/15731914/11725857/d1bf9aa4-9f49-11e5-8523-e8ebf92a52bb.png)

**Comment by ChristiaanGuzman** [comment]
fixed

2015-12-10 14:25 GMT-05:00 Estepfany notifications@github.com:

**Comment by ChristiaanGuzman** [comment]
realizar update para ver el cambio

2015-12-10 14:54 GMT-05:00 Christiaan Guzmán <
christiaan.guzman@illustrato.net>:

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
