### ISSUE TITLE
Crear reserva - AdminET

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#114]
En el formulario de crear reserva se visualiza un campo en el cual no se puede especificar el valor
![1](https://cloud.githubusercontent.com/assets/15731914/11728360/6685f7e8-9f57-11e5-855f-66a1653053a5.png)

**Comment by AndresTello** [comment]
No se realizó la prueba con la ultima versión del aplicativo

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
