### ISSUE TITLE
Cancelar reserva - visitante/anónimo 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#115]
Se crea una reserva, el código de la reserva es 59, se intenta realizar el proceso de cancelación pero el sistema informa que el código no corresponde a una reserva, se debe poder cancelar una reserva en calidad de usuario no registrado es decir como visitante o anónimo
![1](https://cloud.githubusercontent.com/assets/15731914/11729197/02b64f88-9f5c-11e5-8598-dd09474e8e53.png)

**Comment by GiovHernandez** [comment]
se soluciono

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
