### ISSUE TITLE
Usuario logueado

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#117]
Mientras se cargan las pantallas en la sección en la cual se visualiza la información del usuario que se encuentra logueado se visualiza otra información, una vez finalizada la carga del formulario me muestra la información correcta del usuario logueado, mientras se carguen las pantallas no se debe visualizar información que no pertenezca al usuario autenticado 
![1](https://cloud.githubusercontent.com/assets/15731914/11729933/ef893160-9f5f-11e5-9546-d5ac27fc8834.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
