### ISSUE TITLE
Página de inicio

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#118]
Se debe modificar la pantalla de inicio con el fin de que los comentarios que se visualizan sean los consultados de la bd, actualmente esta información esta estática (quemada) 
![1](https://cloud.githubusercontent.com/assets/15731914/11745093/8824a084-9fe3-11e5-9198-0c41cd341d15.png)

**Comment by GiovHernandez** [comment]
se soluciono, muestra las 5 ultimos

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
