### ISSUE TITLE
Motivo cancelación reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#119]
Al iniciar sesión con un usuario de rol adminET se intenta acceder a la opcion de "Motivos cancelación de reserva" pero este indica que no se cuenta con los permisos necesarios
![1](https://cloud.githubusercontent.com/assets/15731914/11746213/e204a5ca-9fea-11e5-9741-04eaf7b35b60.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
