### ISSUE TITLE
Notificación - novedad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#120]
Se debe verificar el proceso de notificación al momento de identificar un establecimiento nuevo, para tenerlo en cuenta para la notificación como novedad este establecimiento debe estar en estado Activo y en la especificación de visible debe ser igual a SI
Para la notificación de las ofertas estas deben estar en estado igual a Activo

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/11754647/8ab8fbc4-a01a-11e5-8c7c-95a23c8d7c0b.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
