### ISSUE TITLE
Fotos establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#121]
Al adicionar una imagen para el establecimiento se visualiza una pantalla emergente en la cual se debe indicar la ruta de la imagen, pero esta a su vez abre otra pantalla, se debe tener en cuenta el tamaño de las ventanas, están debe tener al menos un tamaño que permita visualizar de forma completa los mensajes arrojados por el sistema
![1](https://cloud.githubusercontent.com/assets/15731914/11746640/fb90c7c4-9fec-11e5-9418-f04ece6cda9f.png)

**Comment by AndresTello** [comment]
Resuelto.
Se saca la alerta de la ventana de carga de imagenes y se coloca en la ventana de imagenes del establecimiento.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
