### ISSUE TITLE
Fotos establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#122]
Después de realizar el proceso para adicionar una imagen de forma correcta, esta se muestra y esta acompañada de un campo de texto, se debe adicionar la etiqueta en la cual se indique al usuario que se puede adicionar información a la imagen
![1](https://cloud.githubusercontent.com/assets/15731914/11746758/71deb0da-9fed-11e5-8298-2e3931f18d83.png)

**Comment by AndresTello** [comment]
Resuelto.

se adiciona la etiqueta para el campo descripción de la imagen

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
