### ISSUE TITLE
Puntos de referencia - establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#123]
Se deben cargar las ciudades que se encuentran relacionadas con el departamento indicado previamente en la creación del establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/11747090/51615180-9fef-11e5-9308-3d390f58392f.png)

**Comment by AndresTello** [comment]
Resuelto.

se corrige error al momento de cargar las listas de departamentos y ciudades

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
