### ISSUE TITLE
Configuración de habitación - establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#124]
La opción para adicionar imágenes en el navegador Firefox no cuenta con la etiqueta, solo se visualiza un campo "vació" 
![1](https://cloud.githubusercontent.com/assets/15731914/11747386/02fed650-9ff1-11e5-81c5-faac0b398d3b.png)

**Comment by AndresTello** [comment]
Revisar por diseño.

el campo tiene un placeholder y en el navegador chrome si se ve pero en fire fox no

**Comment by ChristiaanGuzman** [comment]
por favor enviar url y usuario con pass para ver este hallazgo

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
