### ISSUE TITLE
Periodo de la temporada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#126]
Se debe modificar la forma en la cual se especifican las fechas ya que permite que el usuario digite una fecha invalida y se produzcan errores como el siguiente
![1](https://cloud.githubusercontent.com/assets/15731914/11748595/01e3879c-9ff7-11e5-9a89-7b129a2b6cb5.png)
En la consulta se visualizan mas periodos de los que se han configurado, se debe verificar si solo esta consultando los periodos de la temporada del establecimiento o esta consultando todos los periodos existente
![1](https://cloud.githubusercontent.com/assets/15731914/11748791/0c40424c-9ff8-11e5-83bd-fa6c45a5df02.png)

**Comment by AndresTello** [comment]
1. el primer punto se corrige junto con el caso 125
2. para el segundo caso se realiza la prueba y se encuentra que el aplicativo está funcionando correctamente.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
