### ISSUE TITLE
Autenticación fallida 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#127]
Cuando se realiza el proceso de autenticación con información incorrecta se debe visualizar un mensaje en el cual le indique que la información ingresada no es correcta, esta mensaje se debe visualizar en el entorno de SItur, actualmente se esta direccionando al usuario a un pantalla de GECO-empresarial
![1](https://cloud.githubusercontent.com/assets/15731914/11748954/e4195e2e-9ff8-11e5-9e27-15e4942125d6.png)

**Comment by EverHidalgo** [comment]
solucionado.

![imagen1](https://cloud.githubusercontent.com/assets/15741670/11753923/0caaa088-a016-11e5-92de-ef00891b7550.png)

**Comment by Estepfany** [comment]
Se sigue presentando el error
![1](https://cloud.githubusercontent.com/assets/15731914/11824472/bdd1ba8e-a347-11e5-8636-32feee11dda0.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/11844172/5db78aae-a3db-11e5-96dc-88323a271e1a.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
