### ISSUE TITLE
Periodo de la temporada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#128]
En el formulario no se cuenta con una opción para cerrar la ventana o para indicar el final del proceso
![1](https://cloud.githubusercontent.com/assets/15731914/11749298/d64be6de-9ffa-11e5-82d5-915a025500b4.png)

**Comment by AndresTello** [comment]
Resuelto.
Se concede permiso sobre el botón al rol AdminET

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
