### ISSUE TITLE
Tarifa de la temporada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#129]
En la configuración de la tarifa de la temporada no se cuenta con un botón para realizar la asignación general del porcentaje 
![1](https://cloud.githubusercontent.com/assets/15731914/11749623/e813e734-9ffc-11e5-8456-54fddf654947.png)

**Comment by AndresTello** [comment]
Resuelto.
Se conceden permisos sobre el botón para el rol AdminET

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
