### ISSUE TITLE
Crear reserva - AdminET 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#131]
La consulta para saber la disponibilidad no arroja resultado,por lo cual no se logra generar una reserva por parte del adminET
![1](https://cloud.githubusercontent.com/assets/15731914/11752900/1dd5458a-a010-11e5-93dd-44db4b68602b.png)

**Comment by AndresTello** [comment]
Se realiza la prueba, y se encuentra que el aplicativo está funcionando correctamente.
Esta prueba se realizó con el mismo usuario y se encontró que las temporadas que se configuraron no se habían publicado, por ende el sistema no muestra disponibilidad.

**Comment by Estepfany** [comment]
Se verifica y al realizar la prueba no se cuenta con el campo para ingresar la cantidad de habitaciones y tampoco muestra la disponibilidad al realizar la prueba con habitaciones compartidas
![1](https://cloud.githubusercontent.com/assets/15731914/12020642/a8446798-ad4c-11e5-907e-0f7347811efd.png)

**Comment by AndresTello** [comment]
se resuelve el campo de cantidad de habitaciones.

para disponibilidad se verifica y es porque ese usuario no tiene confiugradas tarifas en las habitaciones compartidas para las temporadas

**Comment by Estepfany** [comment]
Se verifica las temporadas y las habitaciones compartidas, se logra consultar la disponibilidad de las habitaciones compartidas pero si se indica "tipo de habitación" a privada una vez realizada la disponibilidad con el "tipo de habitación" compartida no se hace visible el campo "Cantidad de habitaciones"
![1](https://cloud.githubusercontent.com/assets/15731914/12024091/975bde9e-ad6e-11e5-957a-19bdfff44231.png)

**Comment by AndresTello** [comment]
esta prueba se realizó sin tener la ultima versión del aplicativo

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
