### ISSUE TITLE
Consulta reserva - AdminET

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#132]
En la consulta de reservas no se esta discriminado por el establecimiento, se esta visualizando todas las reservas realizadas. 
![1](https://cloud.githubusercontent.com/assets/15731914/11753016/e1da1082-a010-11e5-9ddf-00dbf49119c4.png)

**Comment by AndresTello** [comment]
Resuelto.
Se modifica la consulta de reservas agregando el identificador del establecimiento

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
