### ISSUE TITLE
Tarifa de la temporada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#133]
Se debe manejar la misma separación decimal en ambos valores del reporte, campos: precio de la habitación y total
![1](https://cloud.githubusercontent.com/assets/15731914/11754530/dff1464c-a019-11e5-8074-44ef845ca780.png)

**Comment by AndresTello** [comment]
Resuelto.
Se agrega el separador de miles en la columna Total del reporte.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
