### ISSUE TITLE
Diseño

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#134]
En el pantalla inicial los enlacen en la parte inferior no llevan al formulario o página esperada, ademas se sobre pode al logo de illustrato "create by"
![1](https://cloud.githubusercontent.com/assets/15731914/11755664/f0f52820-a021-11e5-84f8-2252b7f1c308.png)

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Aun hay enlaces que no apuntan a un formulario o pagina segun corresponda, ademas en el navegador de Explorer los enlaces se visualizan en 2 lineas
![1](https://cloud.githubusercontent.com/assets/15731914/12021497/36babd30-ad55-11e5-92bf-b21eff77a94b.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
