### ISSUE TITLE
Diseño - logo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#135]
Al dar clic cerca del logo (recuadro en rojo) lleva al usuario a un formulario que contiene un error, se debe verificar la acción que se debe realizar al dar clic cerca del logo, ya sea cargar la pagina o no realizar ninguna acción
![1](https://cloud.githubusercontent.com/assets/15731914/11756608/229a6d20-a029-11e5-9488-91ec8cf482c1.png)

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
