### ISSUE TITLE
Reserva - datos de reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#137]
Al comenzar a realizar el proceso de registro de la reserva se evidencia el titulo del campo incorrecto, el campo debe indica "Número de identificación", esta inconsistencia se presenta siempre y cuando el usuario que realiza la reserva este autenticado
![1](https://cloud.githubusercontent.com/assets/15731914/11823576/ae11189c-a342-11e5-9115-d23010adacb6.png)

**Comment by GiovHernandez** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
