### ISSUE TITLE
Diseño - servicios

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#139]
En la consulta de los establecimientos en la parte en la cual se informa acerca de los servios que presenta el establecimiento, se muestran algunos iconos que tiene un gran tamaño como lo son: discapacidad-active,  mascotas-active, modificar el tamaño, colocarlos del tamaño del resto de los iconos
![1](https://cloud.githubusercontent.com/assets/15731914/11824152/081b106a-a346-11e5-8c1b-aa89c9ed6a39.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
