### ISSUE TITLE
Métodos de pago

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#140]
Se debe validar que los métodos de pagos no se repitan para un establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/11825351/8a9facf2-a34c-11e5-9f0f-ce00e62ff12c.png)

**Comment by AndresTello** [comment]
Resuelto.

Se realliza la validación al momento de la creación para que no se dupliquen los tipos de pagos

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
