### ISSUE TITLE
Reserva - cancelada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#141]
En el proceso de cancelación de reservas cuando el usuario esta autenticado, se realiza el proceso de cancelación y el sistema muestra un mensaje en el cual indica que el proceso de realizo pero este no se quita ni indicando el boton de cerrar "X" o "Aceptar"
![1](https://cloud.githubusercontent.com/assets/15731914/11825497/5ad9af12-a34d-11e5-8899-6c19ee7330d0.png)

**Comment by GiovHernandez** [comment]
se realizaron pruebas en los navegadores  y funciono bien

**Comment by Estepfany** [comment]
Se sigue presentando, la prueba se realizo en el navegador firefox
![1](https://cloud.githubusercontent.com/assets/15731914/11872700/bb8200aa-a4a4-11e5-8531-390d291345ae.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
