### ISSUE TITLE
Parametrizacion - tipos de actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#142]
Eliminar tipo de actividad, se debe capturar el error que se genera si se indica la eliminación de un tipo de actividad que ya esta relacionada con otro registro, se debe informar que la eliminación no se puede realizar indicando la razón para no efectuar la acción
![1](https://cloud.githubusercontent.com/assets/15731914/11826302/98409f1e-a352-11e5-854f-04f37898af36.png)

**Comment by EverHidalgo** [comment]
SOLUCIONADO.

![image](https://cloud.githubusercontent.com/assets/15741670/11842144/c3948cac-a3cf-11e5-96c2-b90349cfe4b6.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
