### ISSUE TITLE
Ofertas establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#143]
La oferta de tipo habitación permite crear la oferta sin especificar la habitación a la cual aplicará
![1](https://cloud.githubusercontent.com/assets/15731914/11845148/6e245502-a3e0-11e5-9077-086d9149f4ff.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
