### ISSUE TITLE
Reserva adminete

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#144]
Se debe verificar el valor del la habitación el valor que se visualiza en la creación de la reserva, el valor base de la habitacion es de 253.000, con la temporada queda en 278.300, y durante el periodo seleccionado de la reserva aplica una oferta del 20 %, pero es valor que se visualiza de la habitación es de 556.600, estos valores no corresponden
![1](https://cloud.githubusercontent.com/assets/15731914/11846459/c852aba4-a3e6-11e5-8dcf-7651b63be375.png)

**Comment by AndresTello** [comment]
Se revisa la aplicación y esta funcionando correctamente, realizando el caso tal cual como esta aquí

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
