### ISSUE TITLE
Reporte del establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#146]
Se debe restringir el ingreso de caracteres alfabéticos en los campos de fechas
![1](https://cloud.githubusercontent.com/assets/15731914/11848831/cca1e7fe-a3f2-11e5-855a-7bdc3c1e6ce3.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
