### ISSUE TITLE
Configuración de servicios

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#147]
Después de realizar la configuración de los servicios de una habitación e indicar la opción de cerrar "X", se recarga la aplicación completa y dirección al usuario a la pantalla principal
![1](https://cloud.githubusercontent.com/assets/15731914/11849065/f3173ed8-a3f3-11e5-961b-1d29ac8d96f8.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
