### ISSUE TITLE
Consulta directorio - hoteles activo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#148]
Se indica el nombre de un establecimiento que se encuentra inactivo y la consulta trae el establecimiento sin confirmar su estado
![1](https://cloud.githubusercontent.com/assets/15731914/11850538/e6cd2f22-a3fb-11e5-8736-8023270a67bf.png)

**Comment by GiovHernandez** [comment]
solucionado

**Comment by Estepfany** [comment]
Para que el establecimiento pueda estar dentro del listado de establecimientos del directorio turístico aparte de que su estado debe ser Activo en la información del establecimiento se debe establecer si esta visible o no

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
