### ISSUE TITLE
Consulta directorio - hoteles

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#149]
Al crear el establecimiento no se relaciona una imagen, este proceso se realiza en la actualización del registro, esta imagen no se esta visualizando en la consulta del directorio turístico
![1](https://cloud.githubusercontent.com/assets/15731914/11851067/b30228de-a3fe-11e5-953e-35c1a41017c2.png)

**Comment by GiovHernandez** [comment]
no esta guardando la foto principal en la tabla de establecimiento turistico

**Comment by AndresTello** [comment]
Resuelto.

se agrega un campo para la configuración de la imagen principal del estaqblecimiento  en la opción Mi establecimiento

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
