### ISSUE TITLE
Modulo - parametrización (zonas cardinales)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#15]
El proceso de actualización y de eliminación deben realizarse una vez se confirme la acción a realizar, el mensaje debe tener por título "Confirmación" y el cuerpo del mensaje: ¿Desea eliminar el registro? para eliminar o ¿Desea actualizar el registro? para la modificación, una vez el usuario confirme la acción se realiza la operación y si se logro realizar con éxito se visualiza  el mensaje de la operación realizada correctamente
![1](https://cloud.githubusercontent.com/assets/15731914/11120843/6d4f52ba-8920-11e5-9905-d3b65aa5539d.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
