### ISSUE TITLE
Consulta directorio - hoteles

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#150]
Se realiza la consulta de un hotel, después se indica la disponibilidad y no se visualizan las habitaciones
![1](https://cloud.githubusercontent.com/assets/15731914/11851715/105ca24a-a402-11e5-9cdf-e8534a7b8184.png)

**Comment by GiovHernandez** [comment]
resuelto ya muestra la habitacion

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
