### ISSUE TITLE
Crear establecimiento- actividades - Nueva funcionalidad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#154]
Al crear el establecimiento se establece de categoría actividades, al realizar la actualización del mismo se evidencia que se puede especificar las habitaciones, no se debería permitir especificar habitaciones a establecimientos que tiene esta categoria.
Nueva funcionalidad

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
