### ISSUE TITLE
Directorio turístico - que hacer

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#155]
La consulta "Que hacer" no se esta visualizando los establecimientos que son solo de actividades, se visualizan también los hoteles
![1](https://cloud.githubusercontent.com/assets/15731914/11856055/1802fbf6-a41c-11e5-9d1e-eecf341b5907.png)

**Comment by GiovHernandez** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
