### ISSUE TITLE
Reserva adminete

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#157]
En la creación de la reserva se evidencia que el valor total de la reserva no se logra identificar, se debe corregir el error de javascript NaN, este error se debe corregir lo mas pronto posible ya que es bloqueante (No permite crear la reserva)
![1](https://cloud.githubusercontent.com/assets/15731914/11859014/0c2322c0-a435-11e5-95c1-95f64c864b7c.png)

**Comment by AndresTello** [comment]
Se revisa el aplicativo y se encuentra que esta funcionando correctamente, esta prueba se realizó sin la ultima versión del aplicativo

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
