### ISSUE TITLE
Registro de cuenta - adminete

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#159]
Al realizar el proceso de creación del usuario para administrar un establecimiento se presenta este mensaje sin haber iniciado el proceso de logueo
![1 png](https://cloud.githubusercontent.com/assets/15731914/11873397/5cffced2-a4a8-11e5-8ea6-70c294ce67d3.jpg)

**Comment by EverHidalgo** [comment]
este me lo indico yina, resulta que ella estaba creando un establecimiento, le envió el enlace y llego a validación de registro ingreso la información y salio este mensaje, ella me indico que el usuario era nuevo por lo cual no debería haber mostrado ese mensaje

"El usuario no existe"

**Comment by AndresTello** [comment]
Este caso se debe revisar junto con el ingeniero ever ya ue no conozco exactamente como se desarrollo la página de validación de la cuenta

**Comment by AndresTello** [comment]
Con ever se realizó la prueba y el aplicativo esta funcionando correctamente

![img_18122015_091437](https://cloud.githubusercontent.com/assets/15741949/11898708/03ef1aa8-a568-11e5-926c-97c5d07ea35b.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
