### ISSUE TITLE
Modulo - parametrización (zonas cardinales) 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#16]
El mensaje de confirmación de la eliminación debe tener por título "Confirmación" y el cuerpo del mensaje: ¿Desea eliminar el registro?, una vez el usuario confirme la acción se realiza la operación y si se logro realizar con éxito se visualiza  el mensaje de la operación realizada correctamente
![1](https://cloud.githubusercontent.com/assets/15731914/11121138/2dae4bfa-8922-11e5-9bcc-a83d3669d275.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
