### ISSUE TITLE
Enviar mensaje - CRM

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#160]
No se logra especificar un contacto o indicar todos los contactos en la creación del mensaje
![1](https://cloud.githubusercontent.com/assets/15731914/11874497/099ed188-a4ae-11e5-8765-83a901ea668f.png)

**Comment by EverHidalgo** [comment]
solucionado.

selecionar un contacto en particular.

![image](https://cloud.githubusercontent.com/assets/15741670/11882473/9702f5f0-a4da-11e5-8c40-aca8027c6910.png)

**Comment by EverHidalgo** [comment]
seleccionando todos los coctactos.

![image](https://cloud.githubusercontent.com/assets/15741670/11882512/c836b2f6-a4da-11e5-83d5-df613abf1895.png)

**Comment by Estepfany** [comment]
Se realiza la prueba nuevamente el día de hoy y no funciona, verificar funcionalidad
![1](https://cloud.githubusercontent.com/assets/15731914/12025154/c1c2d8ee-ad79-11e5-87bf-e7333df389b3.png)

**Comment by EverHidalgo** [comment]
solucionado.

para realizar esta prueba deben haber usuarios que hayan visitado el establecimiento. como el usuario de la prueba es addministrador de un establecimiento que no lo han visitado, por eso no sale ningun dato

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
