### ISSUE TITLE
Consulta mensaje - CRM

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#161]
No se cuenta con las opciones en la pantalla de consulta, se debe verificar los permisos tanto de las acciones como de la visualización de las opciones del menú, se debe tener en cuenta que las opciones ocultas no deben ser visible para los usuarios diferentes de desarrollador 
![1](https://cloud.githubusercontent.com/assets/15731914/11874796/779f6386-a4af-11e5-8743-79055ceae720.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/11882173/079c2fe0-a4d9-11e5-8727-70288920ee7e.png)

**Comment by Estepfany** [comment]
Las opciones ya se pueden ejecutar pero el resultado de la consulta no esta filtrando los mensajes de cada establecimiento si no que esta mostrando todos los mensajes enviados
![1](https://cloud.githubusercontent.com/assets/15731914/12025228/6681c174-ad7a-11e5-81ad-f44856d2f478.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
