### ISSUE TITLE
Información municipio

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#162]
En el documento se establece que se puede consultar el clima y de mas detalles del municipio en el cual esta el establecimiento indicado, esta información se recupera en la parametrización de municipios, la que actualmente se maneja como ciudad, se debe adicionar la info para que al consultar esta información se visualice en el recuadro que se ve en la imagen 
 Descripción: Breve descripción que se quiera dar al municipio. De ingreso opcional
 Temperatura: Temperatura promedio del municipio.  De ingreso opcional
 Habitantes: Valor de la cantidad de habitantes del municipio. De ingreso opcional.
 Área: Campo de texto para ingresar la información del área (extensión) del municipio. De ingreso opcional.
 Foto: El sistema permitirá almacenar una foto del municipio. De ingreso opcional.

Adicional:
Se debe ingresar al menos 3 municipios que cuente con esta información con el fin de constatar que se esta obteniendo la información de la bd 
![1](https://cloud.githubusercontent.com/assets/15731914/11879420/40856fe8-a4c9-11e5-9b85-03d39a140fec.png)

**Comment by GiovHernandez** [comment]
la pantalla de parametrizacion ya fue realizada por ever se debe de llenar la informacion para el municipio que vayan a probar

**Comment by Estepfany** [comment]
Se verifica, el formulario cuenta con los campos faltantes pero no se puede realizar la búsqueda para realizar el proceso de modificación
![1](https://cloud.githubusercontent.com/assets/15731914/12025313/8cc9e720-ad7b-11e5-84a9-b0a7c09c7ec4.png)

**Comment by GiovHernandez** [comment]
se corriguio la actulizacion de los parametros y la visualizacion de los datos en el hotel  se habilitaron estas dos ciudades , si quieren ver mas deben acomodar los parametros

Antioquia -Abriaqui
valle - cali

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
