### ISSUE TITLE
Modulo - parametrización

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#163]
En el formulario de clasificación de productos, se evidencia que permite almacenar registro en mayúsculas, se recuerda que se estableció que toda información debe registrarse en minúsculas
![1](https://cloud.githubusercontent.com/assets/15731914/11879875/fcad2628-a4cb-11e5-8706-4596299edda3.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
