### ISSUE TITLE
Consulta de reservas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#167]
El reporte de las reservas creadas se evidencia que no todas las columnas tiene un titulo, se deben adicionar los títulos a las columnas 
![1](https://cloud.githubusercontent.com/assets/15731914/11900629/25666990-a575-11e5-9df5-dd6216749f82.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
