### ISSUE TITLE
Asunto correo electronico

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#171]
Cuando se crea la reserva se envía al correo electrónico la información de la misma, se evidencia que el asunto del correo no es correcto ya que no aparece el nombre del establecimiento si no "(mostrar el nombre del hotel en el cual reservó)"
el campo precio debe llevar el $ y realizar la división decimal 
![1](https://cloud.githubusercontent.com/assets/15731914/11904946/76b025a4-a591-11e5-841d-a51374d5d721.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by Estepfany** [comment]
Se debe verificar la construcción de la estructura del cuerpo del correo ya que falta un dato "Fecha limite de cancelación de reserva"
![1](https://cloud.githubusercontent.com/assets/15731914/12090291/90c4f23a-b2bb-11e5-95c1-143ec66bde22.png)

**Comment by AndresTello** [comment]
Resuelto.

Este caso se presenta debido a que no se le configuro el número de días de pago al establecimiento, para esto se configuro el campo como obligatorio en el establecimiento, este cambio se debe hacer en el documento también

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
