### ISSUE TITLE
Creación de reservas - simultaneas 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#172]
Se intenta reservar como turista visitante, turista registrado y como adminete una misma habitación, en el mismo establecimiento, se evidencia que en la parte del turista si realiza nuevamente la validación de disponibilidad antes de crear la reserva pero esta validación no esta en el ambiente del adminete
![1](https://cloud.githubusercontent.com/assets/15731914/11905146/a190b3e6-a592-11e5-9aa7-470e8d38d61c.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
