### ISSUE TITLE
Adicionar abono

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#173]
Se intenta registrar un abono de una reserva, se evidencia que la ventana emergente es muy pequeña, cambia su tamaño con el fin de que al menos se visualice el botón de registro de la información
![1](https://cloud.githubusercontent.com/assets/15731914/11905254/63df1f82-a593-11e5-8ce8-579df2e6aded.png)

**Comment by ChristiaanGuzman** [comment]
lo mismo para esta pantalla los tamaños se dan en jquery

**Comment by ChristiaanGuzman** [comment]
se ajusto el tamaño de la pantalla, mas el fancy sigue estando pequeño

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
