### ISSUE TITLE
Consulta de ventas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#174]
En el resultado de la consulta, es decir en el reporte no se logra especificar el tipo de pago que fue efectuado en la reserva
![1](https://cloud.githubusercontent.com/assets/15731914/11906203/d80f5930-a598-11e5-85d4-a4460f98c211.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/11906521/2faf7a92-a59b-11e5-9e9d-3b0ce53a1540.png)

**Comment by Estepfany** [comment]
El tipo de pago que refleja la reserva 73 no corresponde a la forma de pago que fue efectuado

**Comment by AndresTello** [comment]
Se realiza la prueba junto con ever y el aplicativo esta funcionando correctamente

![capture](https://cloud.githubusercontent.com/assets/15741949/11932460/90010508-a7c3-11e5-9353-b8490475d3af.PNG)

![capture](https://cloud.githubusercontent.com/assets/15741949/11932483/bae4baf8-a7c3-11e5-80ec-be5e04031915.PNG)

**Comment by Estepfany** [comment]
Se realiza la prueba y ya se visualiza el tipo de pago pero no se esta mostrando todas las reservas y el valor total de reservas no es correcto
![1](https://cloud.githubusercontent.com/assets/15731914/12037975/28359866-ae22-11e5-8ceb-67f848830147.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/12041321/3f0a9688-ae3e-11e5-895c-3ce49d5c25ad.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Se evidencia que hay registros que no cuenta con la especificación del tipo de pago
![1](https://cloud.githubusercontent.com/assets/15731914/12101719/3ddb0aac-b304-11e5-915b-fd16c7be5ad2.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/12274510/3c253af8-b939-11e5-99dd-b5fcd0dccb1e.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
