### ISSUE TITLE
Correo electrónico - reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#175]
La estructura del correo electrónico que se envía una vez creada la reserva no cuenta con el asunto completo, no se visualiza el nombre del establecimiento, en el cuerpo falta el nombre del establecimiento:
(el hotel "Nombre del hotel" con los siguientes datos:);  
la estructura de la fecha de limite de pago es dd/MM/AAAA
![1](https://cloud.githubusercontent.com/assets/15731914/11906578/93c7ca0c-a59b-11e5-87e3-15440d45579b.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
