### ISSUE TITLE
CRM - Mensaje - Mejora!

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#176]
Se realiza la prueba del envió de mensajes, se evidencia que el asunto y el cuerpo pueden no ser suficientes para identificar el destinatario, se recomienda adicionar en el asunto el nombre del establecimiento ademas del siguiente texto: "Información importante"
![1](https://cloud.githubusercontent.com/assets/15731914/11907028/c303c5e8-a59e-11e5-92cd-1dd726c4995f.png)

**Comment by EverHidalgo** [comment]
se hablo con sergio y se difinio que el asunto sera "comunicaciones situr" y el cuerpo del mensaje sera el mismo"

**Comment by Estepfany** [comment]
No se logra realizar el envió del mensaje
![1](https://cloud.githubusercontent.com/assets/15731914/12036761/060bda94-ae17-11e5-93b1-36920ced4ef6.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
