### ISSUE TITLE
Reporte - auditoria de cambios de información

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#178]
Al ingresar a este formulario e indicar la opción consultar, se visualiza un mensaje que indica que no se cuenta con los permisos
![1](https://cloud.githubusercontent.com/assets/15731914/11908064/1da215c4-a5a7-11e5-8530-edee083b353e.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Si se realiza la consulta pero el reporte solo debe mostrar la información referente al establecimiento al cual esta asociado el usuario actual del sistema
![1](https://cloud.githubusercontent.com/assets/15731914/12036658/0e4baf3c-ae16-11e5-9fab-3e793af4d642.png)

**Comment by GiovHernandez** [comment]
La pantalla es para el admin de tuga, se ajustaron los permisos solo para este usuario

**Comment by Estepfany** [comment]
Se realiza pruebas de consultas, se evidencia que se están manejando 2 reportes, estos deben manejar las mismas columnas, ademas de que todas las columnas deben tener titulo 
![1](https://cloud.githubusercontent.com/assets/15731914/12119400/a4759ec2-b399-11e5-827d-43af1dd75e04.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
