### ISSUE TITLE
Check in - Nuevo requerimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#180]
Al realizar el proceso de consulta se evidencia que se puede realizar el check in de una reserva cancelada, se verifica con la documentación y no se observa la especificación de la validación del estado de la reserva, se debe validar el estado de la reserva sea igual a Confirmada, esta validación tambien se adiciona a la documentación
![1](https://cloud.githubusercontent.com/assets/15731914/11932072/7bd473d8-a7c0-11e5-9c25-86fa1a7a5c33.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
