### ISSUE TITLE
Creación de habitación - compartida

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#181]
Se crea una habitación de tipo compartida y se adicionan servicios, según la documentación no se debe permitir adicionar servicios
![1](https://cloud.githubusercontent.com/assets/15731914/11933377/9d004dd0-a7c9-11e5-855f-c5847b6d0032.png)

**Comment by AndresTello** [comment]
Resuelto.

El boton de servicios se oculta cuando se va a editar una habitación de tipo compartida

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
