### ISSUE TITLE
Validación de registro

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#183]
Una vez ingresada toda la información se indica la opción aceptar y se visualiza un mensaje indicando que falta la especificación del código alfanumerico que se muestra en la imagen.
![1](https://cloud.githubusercontent.com/assets/15731914/11938688/835193a0-a7ea-11e5-8500-f888dd1f600c.png)

**Comment by EverHidalgo** [comment]
solucionado:

![image](https://cloud.githubusercontent.com/assets/15741670/11939810/8a05feb8-a7f2-11e5-8320-58917e48e295.png)

**Comment by Estepfany** [comment]
Se verifica y el captcha no esta funcionando
![1](https://cloud.githubusercontent.com/assets/15731914/12036377/7131a640-ae13-11e5-9ccf-6c0808cbcb57.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
