### ISSUE TITLE
Creación de habitación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#184]
Se intenta crear una habitación sin especificar el valor por noche y el sistema permite su creación, se debe adicionar esta validación
![1](https://cloud.githubusercontent.com/assets/15731914/11941756/eba834da-a7ff-11e5-985a-5a567f9f674e.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
