### ISSUE TITLE
Creación de habitación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#185]
Se intenta crear una habitación especificando caracteres alfanumérico en el campo numero de habitación y se presento el siguiente error, se debe permitir solo caracteres numéricos
![1](https://cloud.githubusercontent.com/assets/15731914/11941886/a9856284-a800-11e5-9adc-ff35a755f20f.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
