### ISSUE TITLE
Opinión

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#191]
Se intenta registrar una opinión con un turista (diegonaz) y la opinión no se puede almacenar, al indicar la opción de publicar no se genera ninguna acción, este prueba se realiza una vez se consulta un establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/11963810/5de6e99e-a8b7-11e5-945a-49336b170d0b.png)

**Comment by GiovHernandez** [comment]
el registrar opiniones se quita ya que esto solo se debe registrar desde el movil

**Comment by Estepfany** [comment]
Se cierra ya que la función fue eliminada
