### ISSUE TITLE
Modificar oferta

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#194]
Una vez realizada la modificación de la oferta y aceptar el mensaje se visualizo el siguiente error
![1](https://cloud.githubusercontent.com/assets/15731914/11978235/df53d8de-a957-11e5-9e83-4e1ea3e37c12.png)

**Comment by AndresTello** [comment]
Se revisa la aplicación y se encuentra que esta funcionando correctamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
