### ISSUE TITLE
Crear reserva adminete

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#198]
Después de crear la reserva situa nuevamente al usuario en la información de la reserva creada con las opciones de reserva y cancelar, una vez creada la reserva debe de colocar el formulario sin datos o retornar al formulario con el cual se iniciar la reserva - ver disponibilidad
![1](https://cloud.githubusercontent.com/assets/15731914/11984422/14c144a8-a989-11e5-96f2-9580ed875496.png)

**Comment by AndresTello** [comment]
Resuelto.

Se modifica la aplicación de tal forma que cuando el usuario guarda la reserva la aplicación le muestra el mensaje de éxito y cuando le da aceptar se abre la página donde se muestra el detalle de la reserva

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
