### ISSUE TITLE
Reporte de reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#199]
Se realizan reservas las cuales estan con estado pendientes pero estas no se visualizan en el reporte para gestionar su pago
![1](https://cloud.githubusercontent.com/assets/15731914/11985143/c885afc8-a98f-11e5-891e-06ef0ce959f4.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
