### ISSUE TITLE
Modulo - Parametrización

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#2]
En el formulario Categorías, se indica la opción de eliminar una categoría, esta no debe poder eliminar si no quedar inactiva ya que este parámetro es requerido 
![captura1](https://cloud.githubusercontent.com/assets/15731914/11099017/d3614478-8876-11e5-9af5-f1d9c0230246.PNG)

**Comment by AndresTello** [comment]
Esta pantalla fue desarrollada por Ever Hidalgo

**Comment by EverHidalgo** [comment]
solucionado.

al eliminar este parametro se esta validando que no se encuentre vinculado a otro registro, si es asi no  lo permite eliminar

**Comment by Estepfany** [comment]
Se verifica la solución indicada por el desarrollador evidenciando que realiza la validación especificada
