### ISSUE TITLE
Registrar abono

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#200]
Al realizar el proceso para registrar abono a un pago se evidencia que la ventana emergente es muy pequeña para el contenido, aumentar el tamaño de esta ventana
![1](https://cloud.githubusercontent.com/assets/15731914/11985350/e56dae0e-a991-11e5-898b-ef3c8a325187.png)

**Comment by ChristiaanGuzman** [comment]
es pequeña pero si se alcanza a ver su contenido por completo sin embargo si se decide agrandar un poco el tamaño de este fancy necesitaria saber exactamente cual es, ya q estos tamaños se dan por jquery

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
