### ISSUE TITLE
Estados de oferta

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#201]
Las ofertas que su fecha finalización sea inferior a la fecha actual del sistema debe quedar en estado inactivo, se debe verificar ademas los estados vigente y vencido, indicar en que procesos se genera como resultado esos estados
![1](https://cloud.githubusercontent.com/assets/15731914/12019488/c389a300-ad3e-11e5-9d6c-2f5ea902f154.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica y aun no se realiza el cambio del estado de la oferta

**Comment by AndresTello** [comment]
Se verifica y el aplicativo esta funcionando correctamente

**Comment by Estepfany** [comment]
Se verifica y aun no se realiza el cambio del estado de la oferta

**Comment by popepatas** [comment]
porque me asignaron esto ?

**Comment by popepatas** [comment]
si era lo de los cron, este cron ya funciona

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
