### ISSUE TITLE
Estilo de formulario

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#202]
En el formulario de mi establecimiento en la opción para cargar imágenes falta adicionar el estilo
![1](https://cloud.githubusercontent.com/assets/15731914/12019513/38ef6d3c-ad3f-11e5-9750-b16760ce8f26.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
