### ISSUE TITLE
Notificación - ver mas!

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#203]
En las notificaciones se cuenta con la opción Ver mas, esta opción no esta funcionando de manera correcta, no conduce a ninguna pantalla
![1](https://cloud.githubusercontent.com/assets/15731914/12019638/cefbe0e8-ad40-11e5-89ef-b550cab246c4.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
