### ISSUE TITLE
Notificación de caducidad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#204]
Se verifica las fechas de las reservas creadas y que se encuentren pendientes por pagar, se evidencia que el proceso de notificación de caducidad de reserva no se realiza, este proceso indica que se debe notificar al turista y al adminete acerca de la reserva que esta por caducar
![1](https://cloud.githubusercontent.com/assets/15731914/12019783/c6b35c8e-ad42-11e5-990c-3fe71de62617.png)

**Comment by EverHidalgo** [comment]
solucionado.

el crom no estaba habilitado

**Comment by Estepfany** [comment]
no se logra verificar

**Comment by Estepfany** [comment]
Se realiza una prueba del cron y se evidencia que hay un error, se debe revisar y corregir

**Comment by AndresTello** [comment]
Se corrige error en el código, pero cuando se realiza la prueba se evidencia que el CRON no se esta ejecutando.
se realizo la prueba ejecutando la acción desde ele botón de la pantalla que usa el CRON y funciona correctamente.

**Comment by popepatas** [comment]
Ever por favor revisar porque el cron no funciona llamandolo desde el cron

**Comment by EverHidalgo** [comment]
solucionado.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
