### ISSUE TITLE
Crear reserva - adminete

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#206]
Se intenta crear una reserva con las siguientes especificaciones:
1 adulto
2 niños
Edades
15 y 16,
el establecimiento establece que la edad limite es 15; se realiza esta configuración en el formulario pero se evidencia que se cambian los numero digitados en los campos "Adultos" y "Menores"; como los datos son modificados por el sistema no permite establecer una habitación disponible, se verifica la configuración de las habitaciones y si hay una habitación que cumple para este caso
Establecimiento "el hostal de pedro"
![1](https://cloud.githubusercontent.com/assets/15731914/12024796/e9b4e2e2-ad75-11e5-8f4a-0a28792a57b9.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
