### ISSUE TITLE
Crear reserva - turista

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#207]
Se intenta crear una reserva con las siguientes especificaciones:
2 adultos
2 niños
Edades
15 y 16,
el establecimiento establece que la edad limite es 15; se realiza esta configuración en el formulario pero la habitación indicada no toma al niño de 16 como adulto, Ejemplo realizado con el establecimiento "el hostal de pedro"

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
