### ISSUE TITLE
Consulta de oferta

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#208]
Al realizar la consulta se evidencia que no se puede efectuar con los filtros de tipo oferta y con porcentaje
![1](https://cloud.githubusercontent.com/assets/15731914/12035244/b74a06c8-ae08-11e5-9a95-35e49b302e28.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se cierra por que la documentación no establece filtros para realizar esta consulta

**Comment by Estepfany** [comment]
Se debe permitir consultar por los siguientes filtros:
- tipo oferta
- fecha inicial
- fecha final
- porcentaje

**Comment by AndresTello** [comment]
Resuelto.

se crea una nueva pantalla que se encarga de realizar la consulta de ofertas en el establecimiento

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
