### ISSUE TITLE
Icono de eliminar notificación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#209]
Se debe modificar la ubicación del icono de eliminación de la notificación
![1](https://cloud.githubusercontent.com/assets/15731914/12041159/bd35230e-ae3c-11e5-8b7d-1681845bb41c.png)

**Comment by ChristiaanGuzman** [comment]
el html donde se ajusto esto, lo tiene ever, el quedo en ajustarlo en el sitio donde se encuentra

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
