### ISSUE TITLE
Cargar imagen - oferta actividad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#210]
En la creación de ofertas de establecimientos de actividad la opción para realizar la carga de la imagen se muestra como un campo vació
para realizar la prueba se puede utilizar el establecimiento "parque del tomate"
usuario: loboferoz
contraseña: SG11II@@sg
![1](https://cloud.githubusercontent.com/assets/15731914/12041339/7465b6b4-ae3e-11e5-9911-351d841f2d62.png)

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
