### ISSUE TITLE
Parametros - Departamento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#211]
Al intentar eliminar un departamento este arroja un error de sql, se debe capturar este error y mostrar al usuario que el dato no puede ser eliminado por que esta relacionado con otra información
![1](https://cloud.githubusercontent.com/assets/15731914/12041743/33e13f42-ae42-11e5-8da3-7cbe01c0d29e.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
