### ISSUE TITLE
Registrar

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#212]
Se realiza el proceso de registro de un turista, se evidencia que al finalizar el proceso el formulario continua con la información suministrada, se debe limpiar el formulario de registro una vez finalice el proceso
![image](https://cloud.githubusercontent.com/assets/15731914/12051753/9b00207e-aed5-11e5-9c1b-1a91ae876413.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
