### ISSUE TITLE
Usuario de cuenta

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#213]
Una vez se inicia sesión en el sistema en la parte superior derecha se visualiza el nombre del turista logueado pero si se indica ver el perfil cambia el nombre del turista por el usuario, se debe manejar solo uno ya sea el nombre del turista o nombre del usuario
![1](https://cloud.githubusercontent.com/assets/15731914/12051975/45ace28a-aed8-11e5-95ab-51747a79e354.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
