### ISSUE TITLE
Inicio de sesión - info incorrecta

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#215]
Se intenta iniciar la sesión con información de un usuario inexistente en los diferentes formularios y en los formularios "Registrarse" y "Donde quedarse" lleva al usuario a un formulario que no hace parte del sistema SItur
![image](https://cloud.githubusercontent.com/assets/15731914/12052375/60f235b4-aedc-11e5-88ef-8ced9279a5d7.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
