### ISSUE TITLE
Código de seguridad re utilizado

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#216]
Se intenta realizar el proceso de validar registro, se ingresa la información y un código de seguridad ya utilizado anteriormente, el sistema arroja lo que se visualiza en la imagen, se debe realizar esta validación e informar al usuario la razón por la cual falla el proceso
![image](https://cloud.githubusercontent.com/assets/15731914/12052563/33730878-aede-11e5-9633-4f97b810fb39.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/12056494/0170eaee-af05-11e5-85a9-dfc94669ff82.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
