### ISSUE TITLE
Creación establecimiento - representante legal

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#217]
Se crea una sede de un establecimiento pero se relaciona el mismo administrador de la sede principal, el sistema debe realizar la validación en la cual se establece que las sedes deben tener administradores diferentes
![image](https://cloud.githubusercontent.com/assets/15731914/12052868/5b70e2c0-aee1-11e5-83d0-d3e3bff2c98f.png)

**Comment by AndresTello** [comment]
Se decide que esta validación no se va a hacer, no se hacen cambios en la aplicación

**Comment by Estepfany** [comment]
Se cierra por que se quita la validación la cual indica que solo debe de existir un administrador por sede de establecimiento
