### ISSUE TITLE
Validación registro

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#218]
Se intenta realizar el proceso de validacion de registro de una cuenta, se ingresa la información valida pero el sistema arroja el siguiente error
![image](https://cloud.githubusercontent.com/assets/15731914/12052922/0029dd9e-aee2-11e5-8262-2f7e0692a93a.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Aun se presenta el error, (verifique la fecha que se visualiza en la imagen)
![image](https://cloud.githubusercontent.com/assets/15731914/12118675/d04ed03a-b395-11e5-9218-0d2a05b97f58.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/12272636/887185e2-b92f-11e5-839f-aae6a213945b.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
