### ISSUE TITLE
Directorio turistico - establecimiento actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#219]
Se intenta realizar la consulta de un establecimiento de actividades que no esta visible y el sistema permite realizar su consulta, se debe validar que el establecimiento este activo y visible (si) para que pueda ser consultado
![image](https://cloud.githubusercontent.com/assets/15731914/12053700/93421856-aee9-11e5-86cf-74996d301d5f.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
