### ISSUE TITLE
Configurar temporada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#220]
1) Se intenta crear una temporada con un año invalido y el sistema arroja un error de sql
se debe capturar este error y mostrar al usuario que el año indicado no es valido
2) Se intenta crear con un año pasado y permite su creación
se debe indicar al usuario que debe ser un año actual o futuro
![1](https://cloud.githubusercontent.com/assets/15731914/12054191/095a536e-aeef-11e5-8dea-696b0bd66a59.png)

**Comment by Estepfany** [comment]
Se debe verificar las validaciones que se realizan para habilitar los días en los calendarios de acuerdo al año seleccionado
![1](https://cloud.githubusercontent.com/assets/15731914/12054263/07518c12-aef0-11e5-9aed-4444036cdbf9.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
