### ISSUE TITLE
Detalle municipio

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#221]
Después de realizar la consulta de un establecimiento, se indica la opción ver mas en la sección del municipio, si este no cuenta con detalle este debe aparecer vació y no re direccionar al usuario a un formulario con mensaje de error
![1](https://cloud.githubusercontent.com/assets/15731914/12054582/cb2003c4-aef2-11e5-9314-5008f360c582.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
