### ISSUE TITLE
Crear reserva - establecimiento de actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#223]
Se intenta acceder al modulo de reservas desde un establecimiento clasificado como actividades, se permite ingresar y configurar una reserva sin obtener resultado de la disponibilidad, este modulo no debe estar habilitado para los establecimientos que tengan esta clasificación
![image](https://cloud.githubusercontent.com/assets/15731914/12055025/fd03919a-aef6-11e5-987a-787bbb30b49c.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
