### ISSUE TITLE
Crear reserva - Nuevo requerimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#226]
El sistema debe validar antes de crear una reserva si el establecimiento cuenta con la siguiente información especificada:
- número de días de pago
- número de días de notificaciones
- tope de edad de niños
  ![1](https://cloud.githubusercontent.com/assets/15731914/12055731/d84b124a-aefd-11e5-903b-e3b7e28bf804.png)

**Comment by AndresTello** [comment]
Resuelto.
los campos 
-número de días de pago
-número de días de notificaciones
se validan en la configuración del establecimiento como obligatorios y la configuración de tipos de pagos se valida al momento de ingresar a la opción de creación de reservas

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
