### ISSUE TITLE
Disponibilidad - directorio turistico

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#228]
Se intenta realizar la consulta de disponibilidad por medio del rango de precios y no se obtiene las habitaciones, la prueba se realiza con el hotel de camilo, fechas (01/1/2016 -03/1/2016), adultos 2, niños 0, precios desde 100000$ - 200000
![1](https://cloud.githubusercontent.com/assets/15731914/12056670/e233f228-af06-11e5-99f5-29bf9ba6f032.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Aun se presentan inconsistencias en la consulta, esta no funciona indicando un valor inicial diferente de cero, esta misma situación se presenta en el filtro que se encuentra al inicio de la búsqueda del establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/12100929/22ca1130-b300-11e5-8eb7-b3f1286431c0.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by Estepfany** [comment]
Se revisa nuevamente el filtro de rango de precios y se evidencia que nuevamente esta fallando, verificar si toma el rango especificado en el filtro;
MEJORA: Adicionar la separación decimal al ingresar el valor
la prueba se realiza con base a las tarifas que se tiene publicadas en la temporada vigente
![1](https://cloud.githubusercontent.com/assets/15731914/12452210/4e2691fc-bf5b-11e5-8ccd-363fd360e832.png)
![1](https://cloud.githubusercontent.com/assets/15731914/12453093/a1e4be5a-bf5f-11e5-82ff-89b048036296.png)

**Comment by popepatas** [comment]
El filtro de precios va contra el precio base de la habitacion, ya que seria muy dispendioso ver todos los posibles precios del año por temporadas.

la mejora sera tenida en cuenta a futuro cuando el desarrollo se termine por completo

**Comment by popepatas** [comment]
Esta mejora no se hara afecta demasiado el modelo de datos
