### ISSUE TITLE
Reserva - Disponibilidad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#229]
Se realiza la prueba nuevamente de la disponibilidad para realizar una reserva y no se logra efectuar, la prueba se realiza con varios establecimiento y se obtiene el mismo resultado
![1](https://cloud.githubusercontent.com/assets/15731914/12090190/95a3546e-b2ba-11e5-9872-292d436f3dee.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
