### ISSUE TITLE
Proceso Check-in / Check-out Nuevo requerimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#230]
Se deben adicionar validaciones a estos procesos;
Validaciones:
Check-in
- Se debe verificar que este proceso se lleve a cabo siempre y cuando la fecha en la cual se realice el proceso no sea menor a la fecha de llegada (fecha de reserva)
- Verificar el tipo de habitación reservado, si es compartida se debe validar que este proceso no se realice mas de los cupos indicado en la reserva

Check-out
- Verificar el tipo de habitación reservado, si es compartida se debe validar que este proceso no se realice mas de check -in realizados para esa habitación

![1](https://cloud.githubusercontent.com/assets/15731914/12090857/72153020-b2c0-11e5-8236-b67242cf1084.png)

**Comment by AndresTello** [comment]
Resuelto.

para la validación solicitada en la sección del check-out se hizo de la siguiente forma:

el sistema valida que se haga el check-out solo a las personas que hicieron check-in

**Comment by Estepfany** [comment]
Se debe adicionar una validación para las reservas que tiene relacionada habitaciones privadas, el proceso de check-in se debe realizar una sola vez por habitación, después que se realice este proceso se debe cerrar el formulario de registro de check-in
Se intenta realizar el proceso de check-out del registro anterior y la información visualizada no coincide 

NOTA:
- verificar el campo identificación, en ambos procesos ya que permite el ingreso de caracteres alfanuméricos 
- Se realiza el proceso de check-in para habitaciones compartidas, la reserva se realizo de la siguiente manera:
  1 habitación, 2 cupos
  2 habitación, 1 cupo
  para la 1 habitación el proceso se puede realizar 2 veces pero al indicar la 2 habitación para realizar el proceso este indica que ya se realizo, verificar este proceso ya que no funciona correctamente, esto también sucede con el proceso de check-out
  ![1](https://cloud.githubusercontent.com/assets/15731914/12125396/1dc63fa6-b3b9-11e5-8dcf-13fb71493060.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
