### ISSUE TITLE
Registrar pago de reserva - mensajes

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#232]
1) Se debe mejorar el mensaje que arroja el sistema cuando se selecciona una fecha inferior a la fecha actual y la fecha de creación de la reserva, este debe cambiar por el siguiente:"La fecha seleccionada debe ser mayor o igual a la fecha de creación de la reserva"
![1](https://cloud.githubusercontent.com/assets/15731914/12093360/8507df74-b2d0-11e5-8600-b7797c4a2083.png)

2) Se debe mejorar el mensaje que arroja el sistema, el cual tiene lugar cuando se indica una fecha mayor a la actual para registrar el pago, cambiar este mensaje por el siguiente: "La fecha seleccionada no debe ser mayor a la fecha actual del sistema"
![1](https://cloud.githubusercontent.com/assets/15731914/12093209/a4ca4de8-b2cf-11e5-9fcc-3bbb230c7b54.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
