### ISSUE TITLE
Reporte - Consultar turistas registrados

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#235]
Se verifica y este reporte no debe estar como opción para los adminete, solo debe estar habilitado para el admin de situr
![1](https://cloud.githubusercontent.com/assets/15731914/12096744/79f96d4a-b2e5-11e5-9eb6-52e608ee897d.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
