### ISSUE TITLE
Consulta de reservas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#236]
Se intenta realizar la consulta de las reservas, se evidencia que en el campo "fecha llegada" el calendario que se utiliza para indicar la fecha de consulta limita al usuario a seleccionar solo la fecha actual o futura, esta consulta no se debe limitar la selección de la fecha de llegada solo a la actual o futura puede ser una fecha anterior
![1](https://cloud.githubusercontent.com/assets/15731914/12097559/4f1925ac-b2ea-11e5-81fe-a33e6eb6d3cc.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica;
Se evidencia que los filtros de fechas no estan filtrando correctamente, ademas se permite consultar reservas de otros establecimientos
![1](https://cloud.githubusercontent.com/assets/15731914/12099827/fb867912-b2f8-11e5-867b-de17a62e9ce4.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
