### ISSUE TITLE
Reserva - tipo de habitación compartida

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#237]
Se realiza la reserva de tipo habitación compartida y se consulta el detalle de la misma, se evidencia que se requiere conocer la cantidad de cupos reservados, modificar el contenido de la columna tipo habitación, se debe mostrar ya sea privada o compartida no 5 ya que el usuario no identifica el valor de este número
![1](https://cloud.githubusercontent.com/assets/15731914/12099054/02f578a6-b2f4-11e5-82b7-e90cb32412d7.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
