### ISSUE TITLE
Reserva - Disponibilidad - tipo de habitación compartida

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#238]
Se verifica la disponibilidad de una habitación compartida, esta habitación tiene inicialmente 10 cupos, se realiza una 1era reserva con 2 cupos, se intenta crear otra reserva con 5 cupos, en la 2 validación que se realiza para la disponibilidad indica que ya no se cuenta con cupos disponibles, se debe revisar esta validación ya que no esta funcionando correctamente
![1](https://cloud.githubusercontent.com/assets/15731914/12099581/68794a92-b2f7-11e5-89e5-fbe90007540e.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
