### ISSUE TITLE
Consulta detalle reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#239]
Se realiza la consulta del detalle de la reserva y se evidencia que no se esta mostrando el municipio y el tipo de teléfono se indica con un número, este se debe de indicar en texto
![1](https://cloud.githubusercontent.com/assets/15731914/12115920/e6719760-b383-11e5-87bc-7fbed49dfab4.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
