### ISSUE TITLE
Consultar oferta - establecimiento actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#240]
En el proceso de consulta se evidencia que no se puede filtrar por la fecha de la oferta, ademas se visualiza el campo porcentaje el cual no hace parte de las ofertas que son para los establecimientos de actividades
![image](https://cloud.githubusercontent.com/assets/15731914/12117260/9b8a6da8-b38d-11e5-9f62-841c5aad6f16.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
