### ISSUE TITLE
Editar oferta - establecimiento actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#241]
Una vez realizada la consulta se indica el registro y se visualiza el detalle de la oferta, el formulario esta indicando un campo adicional para las ofertas "habitación", ademas se evidencia que la imagen no se carga
![1](https://cloud.githubusercontent.com/assets/15731914/12117502/3303e9ec-b38f-11e5-82a6-e9285e017ea9.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se debe permitir inactivar una oferta

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
