### ISSUE TITLE
consulta Configurar temporada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#242]
La modificación realizada no permite realizar la consulta de un temporada especifica de un año pasado 
![1](https://cloud.githubusercontent.com/assets/15731914/12118177/04a189f2-b393-11e5-9d37-4c4b1e01c26d.png)

**Comment by AndresTello** [comment]
Resuelto.

se crea una pantalla a parte solo para consulta de temporadas.

**Comment by Estepfany** [comment]
Resuelto, no se cierra por que aun le falta diseño, se reasigna a christiaan
![image](https://cloud.githubusercontent.com/assets/15731914/12129740/8b468698-b3d3-11e5-829d-eec68b52c2a2.png)

**Comment by ChristiaanGuzman** [comment]
lesto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
