### ISSUE TITLE
Código de seguridad - registrar cuenta adminete

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#243]
Se realiza el proceso de validar cuenta con un código enviado 30-12-2015, ese mismo día se realiza el  proceso de registrar cuenta y se genera un error por lo cual no se logro generar la cuenta al adminete, hoy 5-01-2016 se realiza nuevamente el proceso con los datos enviados el 30-12 y el proceso se realiza con éxito, ¿El código de seguridad no tiene caducidad? - debe tener un tiempo limite de validez, se intenta una vez mas crear la cuenta del adminete con los mismo datos pero esta vez el sistema arroja un mensaje vació, se debe identificar si el proceso que se intenta realizar ya se realizo para ese establecimiento y con ese código de seguridad, ademas de validar si ese establecimiento ya tiene asociado un adminete
![1](https://cloud.githubusercontent.com/assets/15731914/12120001/d0f6aa60-b39c-11e5-9387-eb9275236f99.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
