### ISSUE TITLE
Recordar contraseña - adminete - Nuevo requerimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#244]
Se estableció que un administrador de establecimiento puede administrar varias sedes y especificar el mismo correo electrónico, por esta razón el proceso de recordar contraseña debe modificarse para los usuario adminete, se debe identificar si el correo especificado pertenece a un adminete, de ser así, verificar si el correo esta especificado en varios establecimientos, si es así, se debe solicitar al usuario el establecimiento (a los que la consulta indico que esta asociado el adminete) del cual desea recordar la contraseña y continuar el proceso de recordar contraseña normal una vez se tenga identificado el establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/12121115/ac63f41e-b3a1-11e5-9375-d26592108fbe.png)

**Comment by GiovHernandez** [comment]
no se va a realizar de acuerdo a lo hablado

**Comment by Estepfany** [comment]
Se cierra ya que se establece que el representante legal no es necesariamente el admin del aplicativo para el establecimiento por lo cual se establece que solo debe existir un solo administrador (único registro de identificación y correo electrónico) por establecimiento sin importar si tiene sedes o no, de acuerdo con esto no seria necesario este nuevo requerimiento
