### ISSUE TITLE
Consulta ofertas - actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#245]
En la consulta de ofertas de un establecimiento de actividades se visualiza un campo que no hace parte de la oferta "porcentaje"
![image](https://cloud.githubusercontent.com/assets/15731914/12128027/c40addb8-b3c8-11e5-9da9-94471629c1f2.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
