### ISSUE TITLE
Editar oferta - actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#246]
Se consulta e indica actualizar un registro de oferta, se modifica y el sistema arroja el siguiente mensaje, indicando una creación en vez de una actualización
![1](https://cloud.githubusercontent.com/assets/15731914/12128105/3dbec908-b3c9-11e5-8a7b-9775c40affd0.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
