### ISSUE TITLE
Motivo de cancelación reserva - adminete - Nuevo requerimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#247]
Se establece que el administrador puede modificar el estado de la reservas que se encuentran pendientes, se debe solicitar la especificación del motivo de cancelación de la reserva
![1](https://cloud.githubusercontent.com/assets/15731914/12147410/b6396ef4-b466-11e5-8987-d90732b72c38.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indicada, al realizar el proceso de cancelación, y se confirma la acción se visualiza un mensaje que no es acorde con la acción realizada
![image](https://cloud.githubusercontent.com/assets/15731914/12183147/01d50bbc-b55b-11e5-90cb-5d22a5494bfe.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
