### ISSUE TITLE
Notificaciones - Cerrar

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#250]
En el formulario en el cual se muestran las ofertas no se cuenta con la opción de cerrar, se debe adicionar ya sea un botón de cerrar o permitir la acción de un clic fuera del formulario de notificaciones para que este se cierre
![1](https://cloud.githubusercontent.com/assets/15731914/12151960/be86fb44-b47f-11e5-8a54-2ed03fdb69e2.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
