### ISSUE TITLE
Reserva creada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#251]
Una vez se crea la reserva, el sistema muestra los datos de la reserva, se evidencia que la configuración de la disponibilidad se mantiene aun si se indica nuevamente buscar la disponibilidad, se debe limpiar estos campo una vez se realice la reserva o no encuentre habitaciones con la configuración indicada
![1](https://cloud.githubusercontent.com/assets/15731914/12153689/4355a90c-b489-11e5-8d49-a634d5821d98.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
