### ISSUE TITLE
Crear temporada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#252]
Al crear un temporada y especificar un periodo ya existente en otra temporada, el sistema arroja un mensaje de advertencia acerca del periodo indicado, la identificación de la inconsistencia esta bien solo que al generarse este caso se esta bloqueando el formulario y no permite su cierre por que se valida que existan periodos para la temporada creada

![1](https://cloud.githubusercontent.com/assets/15731914/12155000/d70adf76-b490-11e5-9d5b-62192d297a53.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
