### ISSUE TITLE
Tipo de identificación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#253]
El campo "tipo de identificación" no esta mostrando todos los tipos de identificación que se encuentran almacenados en la bd, verificar esto también en el formulario de crear establecimiento
![image](https://cloud.githubusercontent.com/assets/15731914/12181084/250a20c0-b54e-11e5-85dc-076e6f42f04f.png)

**Comment by AndresTello** [comment]
Se corrige con el caso 254

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
