### ISSUE TITLE
Parametros - tipos de identificación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#254]
Se debe adicionar el campo "tipo" con el fin de identificar si el tipo de identificación es para una persona o empresa y adicionar también el campo estado, esta especificación también es requerida en el reporte
![image](https://cloud.githubusercontent.com/assets/15731914/12181166/9f1ec4ce-b54e-11e5-85be-f7ecdd331814.png)

**Comment by AndresTello** [comment]
Resuelto.

se decide que no se va a permitir modificar ni eliminar los registros de este parámetro, solo crear nuevo y consultar

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
