### ISSUE TITLE
Cancelar reserva - turista

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#255]
En la selección de los motivos de cancelación de una reserva no se debe permitir seleccionar "cancelada por el sistema"
![1](https://cloud.githubusercontent.com/assets/15731914/12182898/31468760-b559-11e5-94b8-1ac8c1dc0f51.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
