### ISSUE TITLE
Consulta oferta - establecimiento actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#257]
Se realiza un prueba y se evidencia que el campo porcentaje permite el ingreso de caracteres alfanumerico, se debe restringir el campo para que solo permita ingreso numérico

![image](https://cloud.githubusercontent.com/assets/15731914/12210883/3d7c7f6c-b62b-11e5-9b42-37893922a77d.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
