### ISSUE TITLE
Configuración de habitación - reserva asociada- Fase I

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#258]
Se crea una reserva, se identifica la habitación reservada y posteriormente se verifica si el sistema permite la modificación de la configuración de la habitación, se debe verificar la validación de las reservas asociadas a la habitación para poder permitir su modificación
![1](https://cloud.githubusercontent.com/assets/15731914/12273619/ea7328b8-b934-11e5-8b60-4b79b69d1ad3.png)

**Comment by AndresTello** [comment]
Resuelto.

se debe actualizar para probar con los cambios realizados

**Comment by Estepfany** [comment]
Se verifica y el mensaje se arroja así la habitación no tenga asociado ninguna reserva

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica y permite realizar el cambio de la habitación asi este relacionado a una reserva, la reserva es la 155 (establecimiento la maría) y la habitación es la 004

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indicada, se evidencia que permite adicionarle servicios así la habitación este reservada
![1](https://cloud.githubusercontent.com/assets/15731914/12628124/a7597460-c50f-11e5-8dc0-76cafcaee14e.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
