### ISSUE TITLE
Caducidad de reserva pendiente

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#259]
Se verifica el contenido del mensaje de notificación de caducidad de reserva; se debe realizar la siguiente modificación:
*precio: campo con separación decimal y acompañado de $, ej: $400.230
*(Fecha límite de pago de la reserva sin tener en cuenta el día de gracia que otorga el sistema automáticamente) se debe manejar el formato dd/MM/yyyy
![1](https://cloud.githubusercontent.com/assets/15731914/12275027/c97fc506-b93b-11e5-9ba3-92d7a3762554.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
