### ISSUE TITLE
Reporte de visitas a establecimiento turistico

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#261]
Se revisa el reporte y se evidencia que falta información, en la documentación se indica que se puede contar con 2 opciones en el reporte (resumido y el reporte general), la información de cada cual es la siguiente;
reporte resumido:
o   Fecha de visita
o   Usuario
reporte general:
o   Fecha de visita
o   Hora visita
o   Navegador
o   IP
o   Usuario
![1](https://cloud.githubusercontent.com/assets/15731914/12296150/dc36b388-b9d3-11e5-9187-98ba023916f5.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica; la opcion del detalle eneral no esta habilitada para usuarios adminET solo esta para el admin
![1](https://cloud.githubusercontent.com/assets/15731914/12325803/c08c321c-ba9a-11e5-855b-146e162740c3.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
