### ISSUE TITLE
Reporte de visitas a establecimiento turistico

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#262]
Permite especificar fechas mayores a la fecha actual del sistema, se debe validar que la fecha final no sea superior a la fecha actual
![1](https://cloud.githubusercontent.com/assets/15731914/12296308/e0d8086e-b9d4-11e5-886a-3da69b79dd02.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
