### ISSUE TITLE
Reporte de ventas para hoteles

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#263]
Se verifica los permisos del reporte y se evidencia que este reporte se puede acceder desde un establecimiento que es diferente de hoteles, se debe verificar la clasificación del establecimiento y si este es diferente de hotel, se debe informar al usuario "Esta opción no esta disponible"
![1](https://cloud.githubusercontent.com/assets/15731914/12296501/0c226e78-b9d6-11e5-9d07-963ef9369b99.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica; se evidencia que se genero un alert básico se debe modificar
![1](https://cloud.githubusercontent.com/assets/15731914/12325628/7a8d09fe-ba99-11e5-8fbb-77af965a0b3f.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se debe verificar si al registrar el estado confirmada de la reserva se esta actualizando el tipo de pago efectuado para la misma

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
