### ISSUE TITLE
Reporte de calificaciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#264]
Se indica un rango de fechas superior al actual del sistema y permite realizar la consulta, se debe validar las fechas seleccionadas, que no sean superior a la fecha actual del sistema.
esto también aplica para los sgtes reportes:
- Reporte de experiencias
  *Reporte de ventas para hoteles 
  *Reporte de consumo de turistas
  *Visitas de turista 
  ![image](https://cloud.githubusercontent.com/assets/15731914/12299769/73e8fbb6-b9e6-11e5-87e1-24b3cee5f4ce.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
