### ISSUE TITLE
Reporte regional

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#265]
Se revisa el reporte regional y se evidencia que se cuenta con la opción de exportar a Excel, esta opción no debe estar habilitada según la documentación
Se debe modificar el tamaño de las ventanas emergentes, se debe aumentar el anchos con el fin de visualizar todo la información del reporte sin incurrir a los scroll
![1](https://cloud.githubusercontent.com/assets/15731914/12300243/950cb1f0-b9e8-11e5-8594-0a16fd62342a.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
