### ISSUE TITLE
Consulta de turistas registrados

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#266]
Se realiza la consulta de los turistas registrados y se evidencia que faltan registros, ademas de la función de ver los intereses de los turistas;
NOTA: Revisar si se puede unificar las columnas de inactivar y activar
![1](https://cloud.githubusercontent.com/assets/15731914/12325935/a9cff2e2-ba9b-11e5-9d74-e01e347fdfab.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
