### ISSUE TITLE
Perfil - guardar intereses

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#267]
Se ingresa al perfil de un usuario turista, se adiciona los intereses del usuario, al indicar que se almacene la información se visualiza el siguiente error
![1](https://cloud.githubusercontent.com/assets/15731914/12328055/b0fcf874-baa7-11e5-99a3-a49e3b81d54a.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
