### ISSUE TITLE
Estilo de mensajes de advertencia 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#268]
Se debe modificar el estilo de los mensajes de advertencia que se manejan en los reportes
-reporte de consumo (reservas con estado igual a confirmada)
-reporte de visitas (usuario que han consultado el establecimiento)
-reporte de ventas (reservas con estado igual a confirmada)
-reporte de experiencias
-reporte de calificaciones
![1](https://cloud.githubusercontent.com/assets/15731914/12334079/06a7b8cc-bac6-11e5-90a6-21ac614c7777.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
