### ISSUE TITLE
Modulo - parametrización (Tipos de habitación)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#27]
En el mensaje de la validación de los datos requeridos indica que falta el nombre pero la etiqueta del campo es descripción, se debe realizar el cambio en el mensaje
![1](https://cloud.githubusercontent.com/assets/15731914/11126841/fa48aefa-893e-11e5-8a98-554555b16836.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
