### ISSUE TITLE
Registrar pago - PSE- Fase I

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#270]
La reserva ya cuenta con un tipo de pago y aun se esta tomando como pendiente y permite agregar abonos
![1](https://cloud.githubusercontent.com/assets/15731914/12399509/794a0dba-bde8-11e5-94cc-397abb5472db.png)

**Comment by EverHidalgo** [comment]
El tipo de pago que aparece es la forma con que se va ha cancelar la reserva. este campo no significa que la reserva ya se pago

**Comment by Estepfany** [comment]
Se verifica la solución indica y se evidencia que aun se esta presentando la inconsistencia
![1](https://cloud.githubusercontent.com/assets/15731914/12490386/4e0ce8e0-c043-11e5-90fc-4f36a32f87a4.png)

**Comment by EverHidalgo** [comment]
cuando se crea una reserva por el arbol de tuga el tipo de pago esta obligatorio, falta definir como va ha quedar alfin ese proceso

**Comment by AndresTello** [comment]
Se decide que este campo debe eser obligatorio en el creación de reservas del administrador del establecimiento.

**Comment by Estepfany** [comment]
Se debe adicionar un mensaje cuando se seleccione el tipo de pago PSE cuando se seleccione desde la creación de la reserva (Admin ET), este mensaje debe indicar que esta opción no esta habilitada por el momento

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
