### ISSUE TITLE
Cancelar reserva - turista

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#272]
Se debe verificar el estado de la reserva ya que en un reporte esta se establece como cancelada pero al consultar por el perfil de turista aparece pendiente
![1](https://cloud.githubusercontent.com/assets/15731914/12401565/438bde76-bdf5-11e5-8123-00c2cb828c3c.png)

**Comment by GiovHernandez** [comment]
se revizo con sergio y no hay hallazgo

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
