### ISSUE TITLE
Consultar reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#273]
Se debe verificar los estados de las reservas ya que al consultar por el perfil de turista aparece pendiente pero en la consulta de la reservas aparece como cancelada 
![1](https://cloud.githubusercontent.com/assets/15731914/12401600/81c2eae0-bdf5-11e5-8f11-231526e4de13.png)

**Comment by popepatas** [comment]
Hola, se hizo la prueba con Tello (modificando una reserva desde el adminete) y con Gio desde los castor, y no se pudo replicar. revisar con ambos en caso de que persista.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
