### ISSUE TITLE
Barra de titulos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#274]
Se debe modificar la barra de los títulos para que estos no se corran una vez el usuario se desplace así abajo del formulario
![1](https://cloud.githubusercontent.com/assets/15731914/12402709/ba2fe462-bdfc-11e5-8a1d-1f0b86d22f96.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
