### ISSUE TITLE
Detalle mis experiencias

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#276]
Se consultas mis experiencias, se solicita su detalle y una vez en este se solicita nuevamente la opción Mis experiencias y esta opción no funciona, igual sucede con las opciones de perfil y mis reservas, verificar y solucionar por qué se afectan las opciones una vez se consulte el detalle de las experiencias
![1](https://cloud.githubusercontent.com/assets/15731914/12404052/66ef2164-be06-11e5-98c9-adea994b2192.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
