### ISSUE TITLE
Directorio turistico- Fase I

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#277]
Para un nuevo usuario algunos campos no dan a conocer de manera textual el significado de su contenido ya que no se cuentan con títulos, se deben adicionar las etiquetas para la lista de habitaciones, adultos y de niños o manejarlos como están en las otras listas, en las cuales en su 1er ítem indican el contenido (véase la lista de departamentos, municipios, calificación, estilos, zonas, puntos de referencia)
- MEJORA:  Se debe adicional un botón para limpiar los filtros o que estos se limpien una vez efectuada la consulta, verificar esta función también en la consulta de "Que hacer"
  NOTA: verificar también la pantalla en la cual se realiza la reserva
- MEJORA: Que el botón buscar esta a nivel que el usuario este bajando, es decir que siempre este de fácil disponibilidad sin necesidad de llegar hasta el ultimo filtros para realizar la busqueda

![1](https://cloud.githubusercontent.com/assets/15731914/12451151/ac5eb214-bf55-11e5-9eeb-8e2bd672cd84.png)
![1](https://cloud.githubusercontent.com/assets/15731914/12453167/05127076-bf60-11e5-902d-8d43bf6e5468.png)

**Comment by popepatas** [comment]
Esta mejora se hara una vea desarrollado todo lo restante del proyecto

**Comment by AndresTello** [comment]
Resuelto.

> MEJORA: Que el botón buscar esta a nivel que el usuario este bajando, es decir que siempre este de fácil disponibilidad sin necesidad de llegar hasta el ultimo filtros para realizar la busqueda

este punto se debe realizar con Christian

**Comment by Estepfany** [comment]
se debe limpiar también las cajas de chequeo de los servicios
Nota: adicionar la opción limpiar en el formulario "donde comer"  y las etiquetas de adultos / niños en la consulta de la disponibilidad del hotel (la pagina de crear reserva)
![1](https://cloud.githubusercontent.com/assets/15731914/12964005/c168e658-d01b-11e5-805b-e0ea06658871.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by AndresTello** [comment]
Se probo sin los cambios de la ultima versión

**Comment by Estepfany** [comment]
MEJORA: Que el botón buscar esta a nivel que el usuario este bajando, es decir que siempre este de fácil disponibilidad sin necesidad de llegar hasta el ultimo filtros para realizar la búsqueda, esto para todas las búsquedas del directorios turístico (hoteles, actividades, restaurantes)

**Comment by Estepfany** [comment]
Se cierra ya que la ultima mejora no se puede llevar acabo
