### ISSUE TITLE
Crear reserva - Mejora- Fase I

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#278]
Se debe cambiar la solicitud de los teléfonos, de tal manera que se puedan adicionar los 3 teléfonos sin necesidad de hacer hacer visible los campos si el usuario no especifica todos los 3 números, es decir que en 1er instancia se visualicen los campos para adicionar un número telefónico y si el desea pueda adicionar otro indicando la función de adicionar teléfono

NOTA: Adicionar la especificación \* obligatoriedad en los campos requeridos para crear la reserva
![1](https://cloud.githubusercontent.com/assets/15731914/12454941/94a5a896-bf67-11e5-82f0-53d576401cb6.png)

**Comment by popepatas** [comment]
Esta mejora se hara una vea desarrollado todo lo restante del proyecto

**Comment by popepatas** [comment]
Afecta:
-Desarrollo del castor

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
