### ISSUE TITLE
Modulo - parametrización (Motivos Cancelación Reserva) 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#28]
El título del mensaje de confirmación para realizar la acción no sigue el estándar, el título debe ser "Confirmación"
![1](https://cloud.githubusercontent.com/assets/15731914/11127408/34dd2566-8942-11e5-8e00-36ec1ce3ca0b.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
