### ISSUE TITLE
Crear reserva - Nombre del establecimiento - Mejora

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#280]
Una vez se esta en la configuración de la habitación para reservar se evidencia que el nombre del establecimiento no se encuentra especificado en la información visible, se debe adicionar el nombre del establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/12460945/540ee97e-bf84-11e5-8e1e-1184924e308d.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
