### ISSUE TITLE
Favoritos - turista

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#281]
Una vez se encuentre en el formulario de favoritos del usuario turista, al tratar de entrar en los enlaces de; perfil,  mis reservas, mis experiencias, mis favoritos, el enlace se pierde, no lleva a ningún formulario
![1](https://cloud.githubusercontent.com/assets/15731914/12461737/79f61d7a-bf88-11e5-82bc-33c56c5a3306.png)

**Comment by GiovHernandez** [comment]
favoritos fue trabajado por ever, ya solucione el problema del menu

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
