### ISSUE TITLE
Crear reserva - adminET- Fase I

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#282]
1) Se debe adicionar el significado del asterisco en las pantallas
![1](https://cloud.githubusercontent.com/assets/15731914/12462019/fe18fa54-bf89-11e5-99f0-aa4196699896.png)
 2) Se debe validar que el campo cupos cunado se selecciona que el tipo de habitación es compartidas debe permitir solo caracteres númericos
![1](https://cloud.githubusercontent.com/assets/15731914/12462056/41a0d5e4-bf8a-11e5-8dca-50d72c0702a9.png)

**Comment by AndresTello** [comment]
Resuelto.
La primera imagen no hace parte los hallazgos reportas en este caso

**Comment by Estepfany** [comment]
Se debe validar la cantidad que se ingresa, solo se debe permitir ingresar 7 caracteres máximo de números
![1](https://cloud.githubusercontent.com/assets/15731914/12648550/81fa9fde-c5a8-11e5-9ffc-81acb8e291cc.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
