### ISSUE TITLE
Directorio turistico

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#284]
Se intenta realizar la consulta por la calificación del establecimiento y esta no funciona, verificar también este filtro en la consulta de "Que hacer"
![1](https://cloud.githubusercontent.com/assets/15731914/12463464/956593ac-bf91-11e5-9666-d976552669ba.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
