### ISSUE TITLE
Directorio turístico - Que hacer

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#285]
Se realiza nuevamente las pruebas del formulario Que hacer y se evidencia que el único filtro que esta funcionando es el de los mas o menos visitados, lo otros filtros no funcionan, verificar y solucionar
![1](https://cloud.githubusercontent.com/assets/15731914/12463714/43810934-bf93-11e5-9209-6c166009de23.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
1) Se verifica, en los filtros de tipo actividad y actividad se evidencia que la consulta no esta funcionando de la manera correcta ya que trae 2 veces el mismo establecimiento
2) Falta la información de la ubicación del establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/12654230/17bc721e-c5c1-11e5-9b27-5000a4024c6e.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
