### ISSUE TITLE
Reserva - habitación compartida

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#286]
Se intenta crear una reserva de 2 habitaciones tipo compartidas, se ingresa la información y el sistema no responde, no se logra crear la reserva
![1](https://cloud.githubusercontent.com/assets/15731914/12469325/ddaf5720-bfb8-11e5-9e35-db0c39c1aea2.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
