### ISSUE TITLE
Clasificación de productos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#288]
Se debe validar que no se creen clasificaciones iguales; se debe adicionar la definición del asterisco (*)
![1](https://cloud.githubusercontent.com/assets/15731914/12469741/630bccca-bfbc-11e5-8aaa-4990b1ad77f1.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
