### ISSUE TITLE
Clasificación de productos - consulta

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#289]
Se realiza el proceso de consulta de clasificación de productos y se evidencia que no realiza la consulta de manera correcta, no busca por la descripción
![1](https://cloud.githubusercontent.com/assets/15731914/12470043/020af5ec-bfbf-11e5-9f64-40dd01b3ee3b.png)

**Comment by AndresTello** [comment]
Se revisa la aplicación y esta funcionando correctamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
