### ISSUE TITLE
Modulo - parametrización (Motivos Cancelación Reserva)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#29]
El proceso de actualización deben realizarse una vez se confirme la acción a realizar, el mensaje debe tener por título "Confirmación" y el cuerpo del mensaje: ¿Desea actualizar el registro? para la modificación, una vez el usuario confirme la acción se realiza la operación y si se logro realizar con éxito se visualiza  el mensaje de la operación realizada correctamente
![1](https://cloud.githubusercontent.com/assets/15731914/11127622/38a6f626-8943-11e5-81d0-9333c0054300.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
