### ISSUE TITLE
Creación de producto

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#291]
Al intentar crear un producto se evidencia que la lista de referencias no esta cargando la información correcta, verificar y corregir, se debe tener en cuenta también las otras listas, ya que al realizar la consulta de los registros en cada formulario correspondiente no se visualiza los mismos valores que cargan en la listas de producto
![1](https://cloud.githubusercontent.com/assets/15731914/12482025/3b604aca-c01b-11e5-8987-4de23400addd.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
