### ISSUE TITLE
Opción Notificaciones - Admin Et

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#292]
Verificar el contenido de las notificaciones, se debe tener en cuenta que la información a visualizar en este formulario debe ser filtrado por el establecimientos, actualmente se visualizan la información de todos los establecimientos
![1](https://cloud.githubusercontent.com/assets/15731914/12483089/0b3c3204-c021-11e5-8052-9c48517fc002.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
