### ISSUE TITLE
Crear reservas AdminET- Mejora

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#293]
Se debe mejorar el ingreso de los teléfonos al momento de crear una reserva, de tal manera que se puedan adicionar los 3 teléfonos sin necesidad de hacer hacer visible los campos si el usuario no especifica todos los 3 números, es decir que en 1er instancia se visualicen los campos para adicionar un número telefónico y si el desea pueda adicionar otro indicando la función de adicionar teléfono

NOTA: verificar este cambio en el registro del establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/12486633/7e4b31a4-c031-11e5-9aec-04c23861a05d.png)

**Comment by popepatas** [comment]
Esta es una mejora que se trabajara cuando se tenga finalizado todo el desarrollo definido.

**Comment by popepatas** [comment]
afecta:
-Desarrollo de las pantallas

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
