### ISSUE TITLE
Clasificación de productos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#294]
Se realiza la prueba de obligatoriedad, se evidencia que el mensaje que arroja el sistema debe ser modificado, quedando de la siguiente manera: "Debe ingresar la descripción de la clasificación del producto" 
NOTA: Verificar el mensaje en los otros formularios generados en esta fase como son:
_marcas, *referencias, *proveedores,_clasificación producto, *tipos de comida, *producto
![1](https://cloud.githubusercontent.com/assets/15731914/12564015/1187b89c-c37b-11e5-8f1c-11a8471d2258.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
