### ISSUE TITLE
Modulo - parametrización

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#3]
En el formulario de clasificación de productos, al realizar el proceso de creación de un nuevo registro indica una confirmación, se debe quitar este mensaje de confirmación de la acción a realizar exceptuando la acción de eliminación o actualización del registro
![1](https://cloud.githubusercontent.com/assets/15731914/11100338/a6a6e39a-887e-11e5-8f2c-61b70b04b6eb.png)

**Comment by AndresTello** [comment]
Resuelto.
se quita el mensaje al momento de creación del registro

**Comment by Estepfany** [comment]
Se verifica el proceso y se evidencia la solución
