### ISSUE TITLE
Tipo de cocina

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#302]
Se realiza la prueba de creación de un registro y se evidencia que visualmente hace falta la etiqueta en la cual se especifica el significado del *, se debe adicionar
![1](https://cloud.githubusercontent.com/assets/15731914/12586742/819ac49a-c41f-11e5-9d55-74d90f573d29.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
