### ISSUE TITLE
Tipo de cocina

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#303]
En la acción de activar/inactivar se debe verificar si el proceso que se va a realizar si es acorde con el estado del registro, es decir se puede indicar activar un registro que esta activo o inactivar un registro inactivo
![1](https://cloud.githubusercontent.com/assets/15731914/12586842/e2d6ab98-c41f-11e5-912c-bd8f3e3e0954.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/12755405/33a6195a-c99d-11e5-8243-6f858ac3c2d2.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
