### ISSUE TITLE
Tipo de cocina - establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#304]
El formulario utilizado para la gestión de los platos del restaurante no cuenta con el diseño, adicionar diseño
Ruta de formulario:
SITUR -Gestión Situr- Mi establecimiento- opción "Configurar plato"
![1](https://cloud.githubusercontent.com/assets/15731914/12592679/7dac1476-c43b-11e5-95a6-75513f66ae50.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
