### ISSUE TITLE
Tipo de cocina - establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#305]
Se intenta adicionar la especificación de los platos en un establecimiento tipo restaurante y se evidencia que no se esta solicitando la especificación del tipo de cocina, no hace parte de la información general del establecimiento ni esta en la gestión de los platos como lo indica la documentación
![1](https://cloud.githubusercontent.com/assets/15731914/12592810/123ce412-c43c-11e5-8525-a8db08bb58ae.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
