### ISSUE TITLE
Plato - foto

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#306]
En el formulario se establece que la imagen del plato es obligatorio, esta imagen debe pasarse a opcional, se debe tener en cuenta que cuando no se relaciona imagen en las consultas del plato debe cargar una imagen por defecto
![1](https://cloud.githubusercontent.com/assets/15731914/12593917/788a1c26-c441-11e5-85a8-930ef82eeff1.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indicada,  se permite crear el registro sin asociar la imagen pero una vez se finaliza el proceso la información permanece en el formulario, este formulario debe que dar limpio una vez se ejecute ya sea la acción de guardar o modificar
![1](https://cloud.githubusercontent.com/assets/15731914/12889926/44410584-ce4f-11e5-8c88-ad8839675aa0.png)

**Comment by AndresTello** [comment]
Resuelto.

se probo sin actualizar

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
