### ISSUE TITLE
Opción de tipo de comida

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#307]
La opción para administrar los tipos de comida solo debe estar habilitado para los establecimientos que se clasifican como restaurantes
![1](https://cloud.githubusercontent.com/assets/15731914/12594627/08002cb2-c445-11e5-9843-d723dcb3cedf.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
