### ISSUE TITLE
Crear producto 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#310]
Se evidencia que si se llega al parametro para adicionar un producto y no se cuenta con la información previa como lo es clasificación y marcas no le informa al usuario que se requiere contar con una información previa
![1](https://cloud.githubusercontent.com/assets/15731914/12615879/2cad17d2-c4d6-11e5-89be-d0011b2b2f74.png)

**Comment by popepatas** [comment]
afecta:
-Desarrollo de la pantalla

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
