### ISSUE TITLE
Alerta de existencia de producto

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#314]
Se realizo la prueba de las alertas de los topes mínimos y topes máximos de los producto, se evidencia que al indicar el detalle no se cuenta con los permisos para acceder a estos
![1](https://cloud.githubusercontent.com/assets/15731914/12617939/bc1b07c2-c4df-11e5-9c87-fd465b5a15f0.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
Se debe adicionar el titulo a la 1era columna, indicar N°
![1](https://cloud.githubusercontent.com/assets/15731914/12887940/66cb16a8-ce45-11e5-969b-61ff6fe142f5.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
