### ISSUE TITLE
Cancelar reserva AdminET- Fase I

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#321]
Se crea una reserva desde el ambiente de un usuario tipo turista, en este ambiente no se requiere especificar el tipo de pago, se intenta cancelar esta reserva desde el ambiente del adminET y se evidencia que hay una validación referente al tipo de pago , el cual indica que se debe tener un tipo de pago pero este campo esta des habilitado, se debe habilitar este campo para que se pueda especificar la información
![1](https://cloud.githubusercontent.com/assets/15731914/12629356/92bfada2-c515-11e5-916a-8934339d9d29.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
