### ISSUE TITLE
Enlace de registro- Fase I

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#322]
Se realiza el registro de un establecimiento y aun se evidencia que la url enviada en el cuerpo del mensaje no esta tomando la dirección de la bd 
![image](https://cloud.githubusercontent.com/assets/15731914/12646090/030c6e20-c59c-11e5-9856-d529070bdd71.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
