### ISSUE TITLE
Gestión de estilo - establecimientos actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#323]
Se necesita adicionar la especificación de estilos en la gestión de los establecimientos que estén clasificados como actividades ya que esta información es requerida para efectuar la consulta por la opción de recomendados que funciona con los estilos del establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/12649988/11b37410-c5af-11e5-8421-c8ab8c93747b.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
