### ISSUE TITLE
Especificación de actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#324]
Los establecimientos pueden especificar las diferentes actividades que se pueden llevar acabo en el sitio, ademas de la información que se consigna seria bueno tener la opción de adicionar una imagen de la actividad para que en la consulta del detalle del establecimiento estas actividades sean mas atractivas para el turista
![1](https://cloud.githubusercontent.com/assets/15731914/12650424/c9686c7c-c5b0-11e5-887c-83b9802ce035.png)

**Comment by popepatas** [comment]
afecta:
-Maquetacion Web
-Diseño de base de datos
-Cambios en castor
-Cambios en pantalla de admin del ET

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
