### ISSUE TITLE
Experiencias

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#326]
Cuando se intenta consultar las experiencias por ubicación, una vez indicado el departamento la lista de municipios se recarga pero el titulo de la lista se pierde, se requiere que una vez se recargue los municipios del departamento indicado no se pierda el 1er valor de la lista "Municipios" con el fin de que visualmente se le indique al usuario que aun falta la selección del municipio
![1](https://cloud.githubusercontent.com/assets/15731914/12656099/63c74d92-c5ca-11e5-9120-f7ea3e0fb4c2.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
