### ISSUE TITLE
Consulta de mis reservas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#327]
En la consulta de mis reservas en la información de la reserva se evidencia que la imagen que se visualiza no corresponde a la imagen del establecimiento si no a una imagen por defecto, se debe modificar y mostrar la imagen principal del establecimiento al cual esta relacionada la reserva
![1](https://cloud.githubusercontent.com/assets/15731914/12656705/9bf2e318-c5cd-11e5-8274-ec3f967a7de6.png)

**Comment by GiovHernandez** [comment]
ok,verificar que las imagenes esten en el equipo de pruebas

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
