### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#328]
Se debe modificar el menú en la opción "Donde comer" ya que en el navegador Firefox la selección de la opción indicada aparece arriba y no abajo como el resto de opciones
![1](https://cloud.githubusercontent.com/assets/15731914/12656917/cd637740-c5ce-11e5-8bae-b5ecf6f526b3.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
