### ISSUE TITLE
Opciones - establecimientos tipo restaurantes

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#329]
Para los establecimientos con la clasificación de restaurantes no se debe permitir gestionar temporadas, al indicar esta opción se debe visualizar el siguiente mensaje "Esta opción no esta disponible", y dirigir al usuario a la gestión del establecimiento
Deshabilitar: 
*Publicación de temporadas
*Configuración de temporadas
![1](https://cloud.githubusercontent.com/assets/15731914/12658004/58dd5c32-c5d4-11e5-8dc3-78bfdd69f032.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
