### ISSUE TITLE
Suministros

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#330]
Se debe adicionar una validación en la cual al indicar la opción de suministros se verifique si el establecimiento cuenta con productos, de no se así, debe informar al usuario para que se realice esta especificación
![1](https://cloud.githubusercontent.com/assets/15731914/12661286/b52210ac-c5e6-11e5-873e-07db397f2364.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
