### ISSUE TITLE
Suministros

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#331]
Se debe adicionar una validación en la cual al realizar el proceso de quitar un suministro del proveedor, se debe validar si ese suministro esta en algún pedido del proveedor en estado diferente de anulado o recibido, si no esta se quitar la relación del proveedor con el suministro, si esta en algún pedido se indica que no se puede quitar el suministro ya que esta asociado a un pedido en curso

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
