### ISSUE TITLE
Pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#332]
Se debe adicionar una validación en la cual se verifique el proveedor seleccionado para el pedido tenga relacionado suministros, si no tiene relación con suministros se debe indicar al usuario que el pedido para ese proveedor no se realizará hasta que se especifique sus suministros
- tambien se debe validar que la fecha de entrega de pedido no sea igual o superior a un año con referencia a la fecha actual del sistema
  ![1](https://cloud.githubusercontent.com/assets/15731914/12678832/bfd0959a-c66e-11e5-81b2-2f099ffc8975.png)

**Comment by AndresTello** [comment]
Resuelto.

Para el segundo punto no se realiza ningun desarrollo, ya que se encuentra funcionando como lo solicitan

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
