### ISSUE TITLE
Pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#333]
Se debe adicionar estilo a los siguientes formularios que se encuentran en la siguiente ruta de opciones:
Gestión Situr - Administración de pedidos - opciones de:
- producto
- historial
- Recibir
  ![1](https://cloud.githubusercontent.com/assets/15731914/12679413/197c707a-c672-11e5-9fc8-374925696342.png)

![1](https://cloud.githubusercontent.com/assets/15731914/12753216/25f8f0a6-c994-11e5-994f-7d65ec49899f.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
