### ISSUE TITLE
Suministro del proveedor

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#335]
La consulta de los producto a asociar a los proveedores con el resultado de la consulta de los productos del inventario no concuerdan verificar los reportes de ambos formularios
![1](https://cloud.githubusercontent.com/assets/15731914/12681041/9d3bea82-c67a-11e5-93c8-b2c68eb8da01.png)

**Comment by AndresTello** [comment]
No se pudo replicar este caso

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
