### ISSUE TITLE
Creación de pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#336]
Actualmente el proceso para crear un pedido se divide en 2 momentos, 1ro se crea el encabezado del pedido, 2do se adicionan los suministros para el pedido, la mejora sería que una vez indicado el proveedor y la fecha de entrega, se recuperen automáticamente los suministros asociados al proveedor, se verifique la cantidad a solicitar de acuerdo a lo parametrizado en el inventario, se cree el pedido con la especificación de los suministros, una vez creado el pedido mostrarlo al usuario con el fin de que se pueda modificar las cantidades a solicitar o adicionar otro suministro

**Comment by AndresTello** [comment]
Resuelto.

El usuario solamente podra agregar un nuevo suministro, si este fue creado despues de crear el pedido, ya que el sistema no le permite agregar dos suministros iguales al pedido

**Comment by Estepfany** [comment]
La mejora se evidencia pero durante la prueba de modificación de cantidad de suministro se evidencia el siguiente error
![1](https://cloud.githubusercontent.com/assets/15731914/12929034/c07b2fb8-cf3e-11e5-8c7f-7e271201c78b.png)

**Comment by AndresTello** [comment]
RESUELTO

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
