### ISSUE TITLE
Suministro del proveedor

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#337]
Se debe realizar la separación de miles en el ingreso del costo cuando se adiciona un suministro a un proveedor
![1](https://cloud.githubusercontent.com/assets/15731914/12684966/935c31e2-c68f-11e5-9e67-abee7ab711f8.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se debe verificar la función utilizada para adicionar los puntos decimales, ya que se genera un error al realizar la modificación del costo de un suministro
![1](https://cloud.githubusercontent.com/assets/15731914/12927391/00b26ffa-cf36-11e5-94a8-2d4ddd61573b.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se debe verificar el proceso para eliminar un suministro del proveedor ya que si el suministro esta asociado a un pedido recibido o anulado al momento de realizar consulta sobre estos pedido la información del suministro aun debe ser visible

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
