### ISSUE TITLE
Historial del pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#338]
Se debe revisar el reporte del historial del pedido ya que no esta filtrando realmente por el pedido, esta mostrando el historial de todos los pedidos sin tener en cuenta el proveedor y el pedido
![1](https://cloud.githubusercontent.com/assets/15731914/12685251/4162e26c-c691-11e5-8904-4354de751a2a.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
