### ISSUE TITLE
Producto del pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#339]
En el reporte de los productos/suministros de un pedido se debe modificar la ultima columna del reporte y que funcione a base del estado del pedido, si el estado del pedido es generado se debe poder realizar la modificación del suministro, si el pedido esta en un estado diferente se debe cambiar por ver detalle, el icono también debe cambiar
NOTA: para editar no se esta habilitando el botón para almacenar el cambio
![1](https://cloud.githubusercontent.com/assets/15731914/12686045/b8cb5ce0-c695-11e5-9f4f-623dcfdc8753.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Sobre un pedido con estado igual a generado se consulta sus suministros y se indica la modificación de un de ello para lo cual se evidencia que no monta la información completa del suministro en el formulario
![1](https://cloud.githubusercontent.com/assets/15731914/12930634/6c604964-cf47-11e5-9e93-e354d3bd7691.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
