### ISSUE TITLE
Consulta de pedidos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#340]
Se debe adicionar la especificación en el 1er rango de fechas ya que no indican a que fecha hace referencia, se debe cambiar por fecha de creación desde - fecha de creación hasta
- la consulta por el estado anulado no funciona
  ![1](https://cloud.githubusercontent.com/assets/15731914/12687693/793452a8-c69f-11e5-83db-cc7092c205f4.png)

**Comment by AndresTello** [comment]
No se puede replicar el caso

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
