### ISSUE TITLE
Pedido - suministro

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#341]
Se debe adicionar el asterisco \* a aquellos campos que son de carácter obligatorio ademas de la etiqueta en la cual se indica el significado del *
![1](https://cloud.githubusercontent.com/assets/15731914/12687817/2d46aebc-c6a0-11e5-953a-7019dbc1b7c8.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
