### ISSUE TITLE
Consulta de pedidos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#342]
Para el filtro producto se debe adicionar una verificación en la cual se tenga en cuenta el valor seleccionado en el campo clasificación, si la clasificación no cuenta con valor, la lista de productos deberá traer todos los productos pero si el campo clasificaciones cuenta con información, se debe filtrar la información contenida en el campo producto
![1](https://cloud.githubusercontent.com/assets/15731914/12688366/c975ca40-c6a3-11e5-9cb6-e0ee6fdd4364.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
