### ISSUE TITLE
Anular pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#343]
Actualmente se permite eliminar un pedido que se encuentre en estado Solicitado sin especificar un motivo de anulación, se debe adicionar ya sea:
- Un parámetro en el cual se gestione los motivos de cancelación de un pedido
- Adicionar un campo tipo observación de anulación a los pedido, que se especifica solo cuando se realiza el proceso de anulación
  Al indicar la anulación de un pedido se debe solicitar un motivo de su anulación, quedara registrado el motivo, la fecha y el usuario que realizo el cambio

**Comment by AndresTello** [comment]
Resuelto.

Se tomo la segunda opción

**Comment by Estepfany** [comment]
El proceso de anulación funciona, se debe des habilitar la opción del calendario
![1](https://cloud.githubusercontent.com/assets/15731914/12930198/d78551e2-cf44-11e5-9da5-245e57d0e3d8.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
