### ISSUE TITLE
reporte de suministros de pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#344]
se debe omitir el campo observación del reporte ya que el contenido de este campo pueden ser muy extenso y puede dificultar el  manejo de la pantalla
![1](https://cloud.githubusercontent.com/assets/15731914/12689887/93e60d9a-c6ad-11e5-9853-56dd9175c4f5.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
