### ISSUE TITLE
Historial del pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#345]
las columnas descritas en el reporte no coinciden con las especificadas en el formulario, las columnas debe ser:
- Número de pedido
- Estado
- Fecha modificación
- Usuario modifica
- Acción
- Registro anterior
- Registro nuevo

![1](https://cloud.githubusercontent.com/assets/15731914/12690385/05fafb40-c6b1-11e5-9928-67962c59b5f4.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica, se cierra el hallazgo debido a que se modifica el requerimiento y solo se realiza la auditoria referente al cambio de estado que puede sufrir el pedido
