### ISSUE TITLE
Envío de pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#346]
Se realiza el proceso de enviar el pedido al proveedor de suministros, se debe adicionar una validación acerca de la fecha de entrega indicada por el adminET, se debe verificar que la fecha seleccionada no sea menor a la fecha actual del sistema
![1](https://cloud.githubusercontent.com/assets/15731914/12721291/14edc84e-c8cd-11e5-8b6e-4459a1515e8b.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
