### ISSUE TITLE
Envío de pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#347]
Se realiza el envío del correo para los proveedores, se verifica la estructura del correo, se debe modificar la columna "CASIFICACIÓN" por CLASIFICACIÓN
![1](https://cloud.githubusercontent.com/assets/15731914/12721683/f63fdff2-c8ce-11e5-9072-e045f3af9ee4.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
