### ISSUE TITLE
Consultar suministro - pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#350]
Se indica un producto y se solicita su búsqueda para lo cual trae todos los productos/suministros asociados al pedido sin tener en cuenta el suministro indicado
![1](https://cloud.githubusercontent.com/assets/15731914/12751685/98451660-c98c-11e5-9760-07c008c9e58d.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
