### ISSUE TITLE
recibir pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#351]
En el detalle de los productos se indica que la cantidad es exacta, pero permite la modificación de la cantidad; se debe adicionar la validación en la que si se indica la opción exacta, no se debe permitir modificar la cantidad
Se debe validar la fecha especificada en la entrega con base a la indicara anteriormente
Se debe validar la persona que se indica que realiza la entrega, esta persona debe estar relacionada en los contactos del proveedor
Se debe validar la información obligatoria como la fecha de entrega y la persona que realiza la entrega
![1](https://cloud.githubusercontent.com/assets/15731914/12753137/b9de1752-c993-11e5-8af5-62a2e08b78ef.png)

**Comment by popepatas** [comment]
> Se debe validar la persona que se indica que realiza la entrega, esta persona debe estar relacionada en los contactos del proveedor

Y que pasa si la entrega se hace por un servicio de mensajería X? En ese caso no se puede saber con antelación la información de la persona que entrega. Bajo esa premisa pienso que no aplica.

**Comment by popepatas** [comment]
> Se debe validar la fecha especificada en la entrega con base a la indicara anteriormente

Si la validación consiste en que no se puede recibir el pedido sino en la fecha exacta que se puso cuando el mismo se realizo, no aplica, puesto que un proveedor en la vida real puede adelantarse o retrasarse en la fecha de entrega

**Comment by AndresTello** [comment]
> En el detalle de los productos se indica que la cantidad es exacta, pero permite la modificación de la cantidad; se debe adicionar la validación en la que si se indica la opción exacta, no se debe permitir modificar la cantidad

Si se hace esta validación el sistema perdera la funcionalidad para editar el registro.
este modulo funciona de la siguiente manera:
-Si el usuario indica que el pedido llego Exacto, el sistema toma el valor de la cantidad solicitada y lo coloca en la cantidad real.
-si el ususario indica que fue exacto por equivocación puede editar la cantidad real y el sistema edita el registro quitando el exacto y guardando la nueva cantidad real.
-si el usuario en la cantidad real indica el mismo valor de la cantidad solicitada, el sistema guarda esta cantidad real y le aplica que fue exacto.

**Comment by AndresTello** [comment]
> Se debe validar la información obligatoria como la fecha de entrega y la persona que realiza la entrega
> este error no pudo ser replicado 

![pedidos](https://cloud.githubusercontent.com/assets/15741949/12887904/3cdfbbe6-ce45-11e5-86f6-38b54d12a32d.PNG)
![peidos2](https://cloud.githubusercontent.com/assets/15741949/12887903/3cdd9212-ce45-11e5-809e-3d8a5aa5f6e1.PNG)

**Comment by Estepfany** [comment]
Se debe adicionar un limite de caracteres en el campo cantidad real, que no permite mas de 10 caracteres
![1](https://cloud.githubusercontent.com/assets/15731914/12958166/5b56b6be-cffe-11e5-9f5e-4381e055bd37.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
