### ISSUE TITLE
Finalizar recibir pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#352]
Se deben tener las validaciones indicadas en el issues 351, ademas una vez indicado la opción recibido el formulario de gestión del pedido debería cerrarse para indicar que el proceso finalizo y no dejarlo como hace actualmente ademas de que no carga toda la información que se supone que almaceno, al parecer no almacena la información de la fecha ni la del nombre de quien entrega, verificar!
![1](https://cloud.githubusercontent.com/assets/15731914/12754819/c321675e-c99a-11e5-8c34-21098d4cdaa9.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se deben contar con la opción de poder consultar las cantidades reales que se recibieron de los suministros
NOTA: Se recomienda adicionar una columna en el reporte de los suministros(productos) del pedido en la cual se indica la cantidad real recibida 
![1](https://cloud.githubusercontent.com/assets/15731914/12959622/4739c2c8-d005-11e5-884a-35c68e103347.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se debe modificar el siguiente formulario omitiendo el botón "Guardar" 
![1](https://cloud.githubusercontent.com/assets/15731914/12978790/240dd7a2-d0a1-11e5-88d2-5217879afc26.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
