### ISSUE TITLE
Alertas productos - pedido recibido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#353]
Se debe tener en cuenta cada vez que se modifique un producto en su cantidad se debe verificar si se requiere una alerta
Según el documento:"Cada vez que se afecten las cantidades de existencias de un producto y/o suministro en el inventario (recibo de pedidos, modificación de productos y/o suministros en el inventario, creación de productos y/o suministros en el inventario), el sistema de manera automática deberá realizar una serie validaciones con el fin de registrar o actualizar la información de las alertas de existencia de productos"

**Comment by AndresTello** [comment]
Se debe definir este tema.

**Comment by popepatas** [comment]
Hola, Esta funcionalidad cambio, quedo con un proceso que se corre cada hora y verifica en ese momento el estado de las cantidades y topes de los productos y genera para ese momento la alerta. Ya no aplica lo de la tabla de notificaciones para productos.

**Comment by Estepfany** [comment]
Se cierra por modificación de requerimiento, se debe modificar requerimiento en documentación
