### ISSUE TITLE
Mensaje en proceso de autenticación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#354]
Se debe adicionar la función del Enter para aquellos mensajes que se pueden visualizar durante el proceso de autenticación, es decir, que funcione tanto con el botón de aceptar que acompaña el mensaje como con el botón Enter

![1](https://cloud.githubusercontent.com/assets/15731914/12756318/434bd1ac-c9a1-11e5-8ad2-7ada12ad18ee.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica y solo funciona de la manera solicitada desde el Home, se debe adicionar a:
donde quedarse
que hacer
donde comer
experiencias
registrate
![1](https://cloud.githubusercontent.com/assets/15731914/12960301/8d8f94d4-d008-11e5-885b-2c9b20d5b236.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
