### ISSUE TITLE
Formulario de notificaciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#355]
1) Se debe revisar el formulario de notificaciones ya que con los cambios realizados referente a las imágenes afecto este formulario
![1](https://cloud.githubusercontent.com/assets/15731914/12760344/f4e7c1e8-c9b3-11e5-8b3c-bbaf0b3ed1b1.png)

2) Se debe adicionar la imagen por defecto cuando aun el usuario no a adicionado ninguna imagen de perfil
![1](https://cloud.githubusercontent.com/assets/15731914/12760043/6ffbb526-c9b2-11e5-93c9-a92ff11bca47.png)

3) Se debe verificar por que la imagen de perfil solo se ve cuando se encuentra en el formulario de perfil
![1](https://cloud.githubusercontent.com/assets/15731914/12760300/bbf5911c-c9b3-11e5-8332-612719ab65c0.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
El 3 punto no esta completo falta en el detalle de las experiencias
![1](https://cloud.githubusercontent.com/assets/15731914/12979230/bedd32ee-d0a3-11e5-82e3-83879954f531.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
