### ISSUE TITLE
Cargar imagen perfil

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#356]
Se debe revisar el formulario utilizado para realizar el cargue de una imagen de perfil
![1](https://cloud.githubusercontent.com/assets/15731914/12760560/f14b8122-c9b4-11e5-9def-10e2867fd016.png)

**Comment by ChristiaanGuzman** [comment]
listo

**Comment by Estepfany** [comment]
Se debe verificar por que la imagen una vez cargada y almacenada al realizar nuevamente la consulta no se carga
![1](https://cloud.githubusercontent.com/assets/15731914/12960623/38eaee68-d00a-11e5-8895-080b425a141c.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
1) Se realiza el proceso de modificación de la imagen y se realiza de forma satisfactoria pero al indicar cualquiera de las opciones (donde quedarse, que hacer, donde comer, experiencias - sin ir a ningun detalle) y se retornar al perfil esta ya no se visualiza
![image](https://cloud.githubusercontent.com/assets/15731914/13054816/a085428a-d3d9-11e5-8bd9-d19c5dd1fa3c.png)
2) Si se dirige al detalle de alguna experiencia se pierde la imagen del usuario
![image](https://cloud.githubusercontent.com/assets/15731914/13054866/f01b370a-d3d9-11e5-8abc-73f92bad3b83.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
