### ISSUE TITLE
Directorio turistico

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#357]
Se debe verificar la consulta de las imágenes en el directorio turístico ya que el cambio realizado en la imágenes afecto la visualización de los establecimientos
![1](https://cloud.githubusercontent.com/assets/15731914/12762031/63573238-c9bb-11e5-9a92-71012ae95ff7.png)

**Comment by GiovHernandez** [comment]
ok, verificar que la carpetas de imagenes este actualizado en el equipo que se prueba

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
