### ISSUE TITLE
Opinión del establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#358]
Al ingresar al aplicativo de Situr se visualiza los diferentes comentarios / opiniones dado por los turistas acerca de algún establecimiento, este comentario esta acompañado de la imagen del usuario, se debe adicionar la siguiente validación, si el usuario del comentario no cuenta con una imagen asociada al perfil se debe colocar la imagen por defecto del perfil dada por el sistema, si esta validación ya esta, entonces se debe verificar el llamado de la imagen ya que no lo esta tomando
![1](https://cloud.githubusercontent.com/assets/15731914/12784567/e3ce0a46-ca55-11e5-8002-b220c7a56480.png)

**Comment by GiovHernandez** [comment]
aparece asi por que fisicamente no esta la foto registrada, si no se le registro foto al usuario que hizo el comentario saldra la foto por defecto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
