### ISSUE TITLE
Cargar imagen establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#359]
Se debe modificar la imagen que se visualiza en la opción de cargar imagen de establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/12785706/c946eb38-ca5b-11e5-83e0-e696ae5e8c20.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
