### ISSUE TITLE
Ciudad - imagen

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#360]
Se debe adicionar una imagen por defecto cuando la ciudad no tiene asociado una imagen
![1](https://cloud.githubusercontent.com/assets/15731914/12786022/2f9ea6a4-ca5d-11e5-915e-45aa6a7325e7.png)

**Comment by GiovHernandez** [comment]
revizar si las imagenes estan en el servidor de pruebas , la consulta esta ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
