### ISSUE TITLE
Clima ciudad - imagen

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#361]
Se deben recargar las imágenes que están relacionada a los climas que se especifican en cada ciudad
![1](https://cloud.githubusercontent.com/assets/15731914/12786572/acb3e6ac-ca5f-11e5-87b5-e718a237425d.png)

**Comment by GiovHernandez** [comment]
la consulta esta bien, verificar que el archivo de la imagen exista en el servidor

**Comment by Estepfany** [comment]
Se debe verificar el cargue de las imágenes de los climas

**Comment by popepatas** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica
=>Solucionado
