### ISSUE TITLE
Ciudad Fase I

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#362]
Al realizar el proceso de modificar se evidencia que la observación no se actualiza, verificar los otros campos del formulario
![1](https://cloud.githubusercontent.com/assets/15731914/12786731/4e72ab90-ca60-11e5-984b-8de1b1655337.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
