### ISSUE TITLE
Habitación - imagen

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#363]
Se debe verificar la consulta de las imágenes de las habitaciones de acuerdo a la modificación realizada para la consulta de las mismas
![1](https://cloud.githubusercontent.com/assets/15731914/12787525/c9949628-ca63-11e5-9509-4a9dd451856f.png)

**Comment by AndresTello** [comment]
Se realiza la prueba y esta funcioanndo correctamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
