### ISSUE TITLE
Mensaje de campos obligatorios - 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#364]
Se debe modificar el mensaje de error de campos requeridos verificados, ya que bajo responsive el mensaje de advertencia toma todo el formulario de la información de reserva
![image](https://cloud.githubusercontent.com/assets/15731914/12787925/67dbe93e-ca65-11e5-945e-b989614d10a9.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se debe verificar las imágenes de las habitaciones del establecimientos
![image](https://cloud.githubusercontent.com/assets/15731914/12981730/ec079488-d0af-11e5-9826-2cb9660c75fe.png)

**Comment by AndresTello** [comment]
Se verifica y esta funcionando correctamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
