### ISSUE TITLE
Cancelar reserva turista

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#365]
El proceso de cancelar reserva no se ejecute bajo el responsive, solo solicita los datos de la reserva y no realiza ningún otra accion
![image](https://cloud.githubusercontent.com/assets/15731914/12790843/4bea125c-ca72-11e5-8e22-dbf49beca22f.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
