### ISSUE TITLE
Alertas de inventario

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#366]
Se verifica la estructura del reporte del inventario de productos, hace falta una columna, esta es:
"Fecha de alerta: Fecha en la que se creó la alerta."

![1](https://cloud.githubusercontent.com/assets/15731914/12817207/d3d1c640-cb1e-11e5-9bb2-00f8fab108b0.png)

**Comment by GiovHernandez** [comment]
se desarrollo con una version anterior

**Comment by Estepfany** [comment]
Se verifica y se debe modificar el documento de requerimientos, ajustarlo a como quedo desarrollado
