### ISSUE TITLE
Opciones de menu

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#367]
Se inicia sesión con un turista, al indicar la opción "Donde quedarse" en el menu se visualizan 2 veces el usuario, modificar
![image](https://cloud.githubusercontent.com/assets/15731914/12817882/61da821c-cb22-11e5-9cda-50d9ac8b422b.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
