### ISSUE TITLE
Opción de perfil

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#368]
Se realiza la verificación para acceder al perfil del usuario pero este enlace no funciona, se debe enlazar 
![image](https://cloud.githubusercontent.com/assets/15731914/12817968/c2bf765a-cb22-11e5-954d-440dad8b38b9.png)

**Comment by ChristiaanGuzman** [comment]
ya fue solucionado

**Comment by Estepfany** [comment]
El error de duplicar el usuario ya no sucede pero aun persiste el problema de permisos, este hallazgo se cierra por que ya se reporto el problema de permisos con otro issues
