### ISSUE TITLE
Mis favoritos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#369]
Se debe verificar el llamado de las imágenes ya que no se están visualizando en la consulta de mis favoritos
![1](https://cloud.githubusercontent.com/assets/15731914/12818242/fa9fd3b6-cb23-11e5-8bd8-d1ae752436ce.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
