### ISSUE TITLE
Opción de restaurantes

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#370]
Se debe modificar el formulario de restaurantes ya que:
1) El titulo debe cambiar por "Donde comer"
2) Los enlaces se pierden una vez se esta en este formulario
3) Se debe verificar el llamado de la imagen de los establecimientos
4) Se pierde la sesión una vez se indica esta opción en el menú 
![1](https://cloud.githubusercontent.com/assets/15731914/12818755/1b448b28-cb26-11e5-9635-c07ec4242670.png)

**Comment by Estepfany** [comment]
Se debe modificar el titulo del formulario en el cual se ven el listado de los restaurantes
![1](https://cloud.githubusercontent.com/assets/15731914/12932567/6cf93994-cf51-11e5-8e00-ce6a2a6d40f7.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/13009532/d447c028-d16a-11e5-84a1-b3167fb75680.png)

**Comment by Estepfany** [comment]
Se sigue presentando la ultima inconsistencia indicada, el nombre del formulario "COMIDA Y RESTAURANTES"
![1](https://cloud.githubusercontent.com/assets/15731914/13060841/62333f36-d402-11e5-8d4c-e5e375aede69.png)

**Comment by AndresTello** [comment]
Se verifica y la el titulo esta como se solicita en este caso

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
