### ISSUE TITLE
Error de autenticación - Fase I

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#371]
Se verifica si se presente de nuevo un error de autenticación que lleva una pantalla diferente a la del sistema de SItur
NOTA: Se debe tener en cuenta el nuevo formulario de que comer / restaurante para verificar el proceso de autenticación
Verificar este proceso en los diferentes formularios
![image](https://cloud.githubusercontent.com/assets/15731914/12820965/5ea51f14-cb2f-11e5-9f25-96b7ea4eb31f.png)
![image](https://cloud.githubusercontent.com/assets/15731914/12820976/6d5701e4-cb2f-11e5-8752-812a42a1df70.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
