### ISSUE TITLE
Consulta restaurantes - rango de precios

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#372]
No se valida la información que se ingresa en los campos de rango de precios, ya que permite ingresar un valor mayor en el rango inicial al valor que se especifica en el rango final
![1](https://cloud.githubusercontent.com/assets/15731914/12822260/3a15484e-cb35-11e5-893e-9ad180652162.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
