### ISSUE TITLE
Consulta restaurantes - tipo de cocina

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#373]
No se puede realizar la búsqueda por tipo de cocina, adicionar este filtro a la consulta
![1](https://cloud.githubusercontent.com/assets/15731914/12824842/39604b04-cb41-11e5-8b55-de44a1472945.png)

**Comment by GiovHernandez** [comment]
funciona bien , verificar nuevamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
