### ISSUE TITLE
Detalle restaurantes - horario 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#375]
Se debe adicionar en el detalle de restaurante la información del horario
![1](https://cloud.githubusercontent.com/assets/15731914/12825970/d77a030c-cb46-11e5-9640-5f02e7459efd.png)

**Comment by GiovHernandez** [comment]
ok, a pruebita le puse un horario de prueba , se debe configurar el horario a os demas restaurantes

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
