### ISSUE TITLE
Imagen de restaurante

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#376]
Se debe cambiar el tamaño de la imagen del establecimiento para que se ajuste al listado del directorio turístico
![1](https://cloud.githubusercontent.com/assets/15731914/12828019/6969f28c-cb50-11e5-9cd9-82bd8faedf9e.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
