### ISSUE TITLE
Crear ofertas - restaurantes

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#377]
Se intenta crear una oferta pero se evidencia que no se cuentan con los campos para la creación
![1](https://cloud.githubusercontent.com/assets/15731914/12828583/c209fb78-cb53-11e5-9e61-5681d4785eff.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se debe adicionar el campo porcentaje en la creación de ofertas para restaurantes
![1](https://cloud.githubusercontent.com/assets/15731914/12951487/8df5b2d2-cfe0-11e5-9b7d-cf0bf1cfa6db.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
