### ISSUE TITLE
Cerrar sesión

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#378]
Se intenta cerrar sesión y se evidencia que el sistema no responde
![image](https://cloud.githubusercontent.com/assets/15731914/12828841/eb20aeca-cb54-11e5-967e-2bdb6ab59f63.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
