### ISSUE TITLE
Opción de pago PSE

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#379]
Se debe adicionar un mensaje en el proceso de crear reserva, una vez consultado los tipos de reserva que maneja el establecimiento, si el turista selecciona PSE se debe visualizar un mensaje que indique que la opción no esta disponible por el momento
![1](https://cloud.githubusercontent.com/assets/15731914/12829726/9a7c79a4-cb59-11e5-9091-0b7f228291cb.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
