### ISSUE TITLE
Modal de ofertas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#387]
Se debe mejorar la presentación de la imagen de la oferta ya que esta no esta bien alineada referente con el tamaño del mensaje donde se visualiza la oferta
![image](https://cloud.githubusercontent.com/assets/15731914/12851468/f41b4d3e-cbf7-11e5-963b-a8fc881492cf.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
