### ISSUE TITLE
Opción de donde comer

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#389]
Esta opción no muestra nada, se debe arreglar para que consulte los restaurantes
![image](https://cloud.githubusercontent.com/assets/15731914/12851797/ce6b43ee-cbf9-11e5-99f7-70426029f46d.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
