### ISSUE TITLE
Campos requeridos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#391]
en el proceso de registro debería adicionarse el asterisco para aquellos campos que son requeridos para el registro
![1](https://cloud.githubusercontent.com/assets/15731914/12852650/093d56b6-cbfe-11e5-894f-fbf09e4ae531.png)

**Comment by EverHidalgo** [comment]
se decidió dejar de ultimo este proceso, por si sobra tiempo

**Comment by AndresTello** [comment]
Resuelto.

Se agregaron los asteriscos a los campos obligatorios, pero se debe aplicar diseño

**Comment by Estepfany** [comment]
Se debe adicionar la validación de la fecha de nacimiento como obligatorio
![1](https://cloud.githubusercontent.com/assets/15731914/12980037/9b71ed2c-d0a8-11e5-8caf-549676b534c2.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/13009972/6272a870-d16d-11e5-9dac-f7e260d93cc1.png)

**Comment by Estepfany** [comment]
Se verifica y no se evidencia la solución indicada

**Comment by AndresTello** [comment]
Se verifica y la aplicación esta funcionando como se solicita en este caso

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
