### ISSUE TITLE
Registrarse - campos requeridos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#392]
Se realiza el 1er paso para realizar el registro de un usuario, se evidencia que al validar la información faltante limpia la información que ya se había ingresado, modificar para que no limpie los campos que ya cuenta con información antes de terminar el proceso de registro
![image](https://cloud.githubusercontent.com/assets/15731914/12852706/5b1d54c2-cbfe-11e5-8931-28b934228c3c.png)

**Comment by EverHidalgo** [comment]
hice la prueba pero no me borro ninguna informacion, me valida la informacion faltante y me saca el mensaje, pero cuando hacepto la informacion ingresada sigue intacta

![image](https://cloud.githubusercontent.com/assets/15741670/12901417/9236f4c6-ce89-11e5-97da-0cb44cc2d0e5.png)

![image](https://cloud.githubusercontent.com/assets/15741670/12901443/c4509822-ce89-11e5-9e37-e9e4c4c98a6e.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
