### ISSUE TITLE
Detalle de expericiencia

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#393]
Una vez se realiza la consulta de "Mis experiencias" y se va al detalle de la misma, con la galeria se duplica el usuario en el menú, corregir 
![image](https://cloud.githubusercontent.com/assets/15731914/12854807/ad79b336-cc09-11e5-8a2d-9a0761b1119e.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
