### ISSUE TITLE
Consulta de hotel por rango de precios

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#394]
Se especifica valores en el rango de precio para la consulta de hoteles y esta no arroja ningún resultado
![image](https://cloud.githubusercontent.com/assets/15731914/12855674/bfe0214a-cc0e-11e5-82a0-d354bf725059.png)

**Comment by GiovHernandez** [comment]
se probo y  funciono bien , probar nuevamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
