### ISSUE TITLE
envío de pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#398]
Se debe adicionar una validación cuando se genere el envío del pedido, se debe validar que cuando se indique realizar el envío verifique la fecha de entrega, esta no debe ser menor a la fecha actual
![1](https://cloud.githubusercontent.com/assets/15731914/12921352/e57dd1fe-cf1a-11e5-9e30-fcd70fd316ef.png)

**Comment by AndresTello** [comment]
La validación ya esta, se debe limpiar cache
![capturee444](https://cloud.githubusercontent.com/assets/15741949/12922459/a07aafc8-cf1f-11e5-8141-eeb9e6934dc7.PNG)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
