### ISSUE TITLE
Modulo - parametrización (Calificaciones)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#40]
Este parámetro no debe contar con la opción de eliminación, solo la opción de actualización
![1](https://cloud.githubusercontent.com/assets/15731914/11150471/29db049e-89f6-11e5-9aa1-070714522c1a.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
