### ISSUE TITLE
Imagen de experiencia

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#400]
Se debe modificar el tamaño del formulario que permite visualizar las imágenes ya que es muy grande
![1](https://cloud.githubusercontent.com/assets/15731914/12933356/9ba78fe4-cf55-11e5-8839-59fb7c06a8e4.png)

**Comment by ChristiaanGuzman** [comment]
el slider no tiene un tamaño definido, eso lo da la imagen, tocaria verlo como se comporta con una imagen en el slider

**Comment by Estepfany** [comment]
Se verifica la solución indica;
se realiza la prueba con una experiencia con imágenes asociadas y tal parece que funciona de la manera correcta
