### ISSUE TITLE
Enviar pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#402]
Antes de que se realice el proceso de enviar el pedido al proveedor se debe validar que los suministros cuente con la especificación de cantidad diferente de cero
![1](https://cloud.githubusercontent.com/assets/15731914/12959526/bf459d56-d004-11e5-9fb7-c549c5f12bf8.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
