### ISSUE TITLE
Foto de perfil 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#404]
Se indica la consulta de mi perfil y se evidencia que la foto de perfil no la toma, verificar la consulta de la imagen de perfil 
![image](https://cloud.githubusercontent.com/assets/15731914/12982184/bf23522a-d0b1-11e5-861d-341935f6eb12.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se realiza la prueba y no se evidencia el cambio
![image](https://cloud.githubusercontent.com/assets/15731914/13057853/cd8d765e-d3ec-11e5-9b82-1122e13b18fd.png)

**Comment by AndresTello** [comment]
Se verifica y la aplicación esta funcionando correctamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
