### ISSUE TITLE
Detalle de experiencias

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#405]
Una vez en el detalle de la experiencia se intenta acceder a l perfil desde el menú y sale la pantalla de permisos
![1](https://cloud.githubusercontent.com/assets/15731914/12982493/019bd6da-d0b3-11e5-8c0f-54315bc84a74.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
El enlace desde el detalle de las experiencias ya funciona pero desde mis favoritos no, se indica la opción mis favoritos, se va al detalle de una de los establecimiento y se indica la opción perfil, el sistema muestra el siguiente mensaje
![1](https://cloud.githubusercontent.com/assets/15731914/13111661/f9720848-d554-11e5-8acc-5401a6ca79a6.png)

**Comment by AndresTello** [comment]
Se esta probando con la versión incorrecta

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
