### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#406]
En los siguientes formularios en favicon no se puede ver:
Que hacer
Donde comer
Detalle de restaurante
![1](https://cloud.githubusercontent.com/assets/15731914/12986369/eea71d2a-d0c4-11e5-9289-b491dbbe7138.png)

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
