### ISSUE TITLE
Filtro rango de precios 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#407]
Se debe validad la información especificada, el rango inicial debe ser menor al rango final en el campo rangos de precios, esto aplica para la búsqueda de hoteles y la de restaurantes
![1](https://cloud.githubusercontent.com/assets/15731914/12989092/b5dc8cf2-d0d1-11e5-8ff4-55ab77197695.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
