### ISSUE TITLE
Intereses 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#408]
Se realiza la prueba para quitar todos los intereses a un turista y se evidencia que siempre deja un interés sin quitar, ejemplo, se adiciona 2 intereses (familiar y clásico), se almacena y el sistema inserta el cambio, se intenta quitar los 2 intereses, el sistema indica que la acción se realizo con éxito, se consulta de nuevo y se evidencia que el ultimo interés que se indico para eliminar no fue eliminado, se debe permitir al turista no tener indicado ningún interés
![1](https://cloud.githubusercontent.com/assets/15731914/12990047/1c9ab8f2-d0d6-11e5-9229-9d80a69e28d4.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Permite quitar todos los intereses, se realiza la prueba seleccionando todos los intereses de la lista y se evidencia que el conteo que realiza el sistema en 1era instancia no es correcto, esta tomando el valor "intereses" como otro valor de la lista, modificar
![1](https://cloud.githubusercontent.com/assets/15731914/13057540/e2a269e8-d3ea-11e5-81b1-25cf4244c5de.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
