### ISSUE TITLE
Consulta actividad 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#409]
Se especifica en el filtro de calificación la opción "Sin calificaciones" y se evidencia que no trae la información correcta, ya que se visualiza establecimientos con calificaciones
![1](https://cloud.githubusercontent.com/assets/15731914/12990396/2ec5e504-d0d8-11e5-9f07-1d9596a01cb9.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
