### ISSUE TITLE
Modulo - parametrización (Calificaciones)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#41]
El proceso de actualización deben realizarse una vez se confirme la acción a realizar, el mensaje debe tener por título "Confirmación" y el cuerpo del mensaje: ¿Desea actualizar el registro?, una vez el usuario confirme la acción se realiza la operación y si se logro realizar con éxito se visualiza el mensaje de la operación realizada correctamente
![1](https://cloud.githubusercontent.com/assets/15731914/11150672/285ad3aa-89f7-11e5-8e10-f441db6016f9.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
