### ISSUE TITLE
Ubicación restaurante  2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#410]
Se debe modificar el estilo de la letra que se utiliza para especificar la ubicación del lugar del restaurante ya que no concuerda con el estilo que se venia manejando para especificar la ubicación de los lugares
![1](https://cloud.githubusercontent.com/assets/15731914/12990536/e69b7496-d0d8-11e5-94c4-92b4d2c9b9f9.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
