### ISSUE TITLE
Rango de precio 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#411]
En la consulta de restaurantes se evidencia que la consulta de precios no funciona correctamente ya que los restaurantes que están actualmente 2 no tiene rango de precios y uno si cuenta con la especificación, con ese rango se realiza la consulta y el resultado sigue siendo el mismo, los 3 restaurantes
![1](https://cloud.githubusercontent.com/assets/15731914/12990980/1f65dfbc-d0db-11e5-917f-1b7bddc73374.png)

**Comment by GiovHernandez** [comment]
revizar los valores de los platos, de acuerdo alo revizado esta bien la consulta contra la informacion

**Comment by Estepfany** [comment]
Se modificaron los valores de los platos en BD y se evidencio que la consulta no estaba de forma correcta, se verifico con el desarrollador y se modifico el proceso que realizaba para la consulta, solucionado
