### ISSUE TITLE
Registrar pago 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#412]
Se debe colocar un mensaje en el cual se indique que esta opción no es valida para los restaurantes y  los de actividades 
![1](https://cloud.githubusercontent.com/assets/15731914/13010453/d8d0ad12-d16f-11e5-82d1-a098f77909a9.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
