### ISSUE TITLE
Actividad 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#413]
Se modifica una actividad del establecimiento, el proceso se realiza de forma satisfactoria pero al finalizar se evidencia que el registro modificado permanece en el formulario, una vez se termine la acción el formulario debe quedar como al inicio (limpio)
![1](https://cloud.githubusercontent.com/assets/15731914/13012188/371d01b0-d178-11e5-8fa2-d443a475a388.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
