### ISSUE TITLE
Actividad establecimiento 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#414]
En la gestión del establecimiento se modifica una actividad, se consulta en el directorio turístico el establecimiento y se evidencia que la actividad que se encuentra inactiva aun es parte de las actividades que presenta el establecimiento, se deben corregir, solo deben ser visibles las actividades que se encuentre activas
![1](https://cloud.githubusercontent.com/assets/15731914/13012409/243e80cc-d179-11e5-87f2-e6572ad8715c.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
