### ISSUE TITLE
Publicación de temporadas 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#415]
Se debe adicionar para el campo de año un limite de caracteres ya que permite al ingresar una cantidad muy alta genera error, (max 6)
![1](https://cloud.githubusercontent.com/assets/15731914/13015826/3bd4ad3c-d189-11e5-8b8a-008fbad1f998.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se debe modificar la cantidad de caracteres permitidos solo deben ser 4 para que no se genere el siguiente error, 
NOTA: verificar que solo esa esta la causa del error
![1](https://cloud.githubusercontent.com/assets/15731914/13052802/d8f2daa2-d3ce-11e5-9ddb-7f4c25d5cb53.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
