### ISSUE TITLE
Costo de habitación 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#416]
1) El campo que contiene el costo de la habitación queda en cero hasta que se especifique algún servicio, esto se debe modificar, si la habitación no tiene asociado ningún servicio debe tomar el valor ingresado de la habitación, adicionar la especificación que el costo es por noche
![1](https://cloud.githubusercontent.com/assets/15731914/13016108/e1ad933a-d18a-11e5-86c7-b0d734799084.png)
2) Se crea una habitación con su información requerida y se asocia una imagen, se crea otra habitación se asocia una imagen y al parecer todo funciona correctamente, pero al realizar la consulta se evidencia que la imagen que maneja las habitaciones es la imagen de la ultima habitación gestionada
![1](https://cloud.githubusercontent.com/assets/15731914/13016301/c624074c-d18b-11e5-9ddb-62862cf322f6.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
