### ISSUE TITLE
Puntos de referencia 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#417]
Se intenta indicar la ubicación (departamento / ciudad) de los puntos de referencia y se evidencia que no esta tomando los filtros
![1](https://cloud.githubusercontent.com/assets/15731914/13016627/f6d772c8-d18d-11e5-80a1-f18df1464468.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
