### ISSUE TITLE
Publicar temporada 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#418]
Se debe revisar la validación acerca de publicar una temporada sin tener la especificación de tarifas ya que permitió publicar una temporada sin tener tarifas asociadas
![1](https://cloud.githubusercontent.com/assets/15731914/13017000/118e134a-d190-11e5-8f69-9afb8f988652.png)

**Comment by AndresTello** [comment]
No se puede replicar el error, se realizaron algunas mejoras que podrían evitar este caso

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
