### ISSUE TITLE
Envió de pedido 2-v 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#419]
Se debe adicionar a la estructura del correo electrónico que se envía al proveedor la dirección del correo electrónico del establecimiento a la cual debe realizar la confirmación de la solicitud del pedido recibido por el proveedor
![1](https://cloud.githubusercontent.com/assets/15731914/13018497/d6a31250-d197-11e5-854e-521fba2b1a6a.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
