### ISSUE TITLE
Modulo - parametrización (Categorias)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#42]
Al realizar el proceso de eliminación se muestra el titulo de la ventana como "Mensaje", los mensajes de confirmación deben llevar el título "Confirmación" y el cuerpo del mensaje: "¿Desea eliminar el registro?" para el proceso de eliminación
![1](https://cloud.githubusercontent.com/assets/15731914/11151416/01fa8abc-89fb-11e5-8973-daa6d26372f9.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
