### ISSUE TITLE
Envió de pedido 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#420]
Se debe revisar el proceso de envió de pedido ya que se esta visualizando la siguiente información mientras se completa el proceso de envió 
![1](https://cloud.githubusercontent.com/assets/15731914/13019322/bebd71da-d19c-11e5-8d52-736bffdfef96.png)

**Comment by popepatas** [comment]
revisar bien cuando esta sucediendo, para poder tener claro que accion tomar

**Comment by Estepfany** [comment]
Se verifica y esta información se visualiza cuando la internet es lenta y se esta generando el envio del correo electronico del pedido
