### ISSUE TITLE
En revisión 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#421]
Se intenta marcar un pedido con la opción de "En revisión" y se genera el siguiente error
![1](https://cloud.githubusercontent.com/assets/15731914/13019462/a1a781c0-d19d-11e5-9dbe-96c98f79a8ca.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
1) El error se presento nuevamente:
![image](https://cloud.githubusercontent.com/assets/15731914/13052129/17f7cec8-d3cb-11e5-86d1-995d06f9b7ce.png)
2) Se debe adicionar el asterisco para indicar la información requerida ademas de la etiqueta en la cual se indica el significado del asterisco
![image](https://cloud.githubusercontent.com/assets/15731914/13052150/3e1cbd02-d3cb-11e5-81b7-6037e7db5ad6.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
