### ISSUE TITLE
Check-in 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#422]
Una vez se identifique que se intenta realizar este proceso antes de la fecha de la reserva y una vez se muestre el mensaje este debe cerrar el popup al indicar la opción de aceptar en el mensaje emergente
![1](https://cloud.githubusercontent.com/assets/15731914/13019978/b881dc80-d1a0-11e5-9d5b-aa47a4e7d08e.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
