### ISSUE TITLE
Enviar mensaje 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#424]
Se debe adicionar el asterisco a los campo requeridos, ademas de la etiqueta en la cual se indica el significado del asterisco
![1](https://cloud.githubusercontent.com/assets/15731914/13021483/7b78a50e-d1a9-11e5-8a18-cce637a946a3.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
