### ISSUE TITLE
Reporte de favoritos 2-v

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#425]
El reporte de favoritos solo debe estar habilitado para el admin de SItur no para los adminET
![1](https://cloud.githubusercontent.com/assets/15731914/13021730/c4ec00ea-d1aa-11e5-881a-9a1a40a623b9.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
