### ISSUE TITLE
Reporte de tendencias

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#427]
Este reporte no debe estar habilitado para el adminET si no solo para adminSItur
![1](https://cloud.githubusercontent.com/assets/15731914/13022240/f28d34e4-d1ad-11e5-9de6-981f66079ea6.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se revisa y se evidencia que las columnas no están en el orden correcto, la 1ra columna debe ser categoría y la 2da cantidad
![1](https://cloud.githubusercontent.com/assets/15731914/13079591/f71720dc-d492-11e5-9c81-c32387206834.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
