### ISSUE TITLE
Reporte de tendencias - por edades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#428]
1) En la documentación se establece que el admin SItur contará con 2 opciones mas para filtrar que son la categoría del establecimiento y el nombre del establecimiento, adicionarlos
2) La estructura del reporte establece 1ro la columna de edad y 2do la cantidad total
3) Verificar la consulta de los reportes por que en el lado del admin no se genera ningún resultado
![1](https://cloud.githubusercontent.com/assets/15731914/13050452/7673ed92-d3c1-11e5-8ed0-3a6a0aeda2ac.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
falta el siguiente punto:
1) En la documentación se establece que el admin SItur contará con 2 opciones mas para filtrar que son la categoría del establecimiento y el nombre del establecimiento, adicionarlos

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
