### ISSUE TITLE
Reporte de tendencias - por genero (sexo)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#429]
1) La documentación establece que el admin SItur cuenta con filtros adicionales que son la categoría y el nombre del establecimiento
2) Revisar las consultas sql del reporte ya que no muestran ningun registro aun con datos modificados para poder visualizar el reporte
![1](https://cloud.githubusercontent.com/assets/15731914/13050898/468c8992-d3c4-11e5-8c46-f3f79d1308b1.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
