### ISSUE TITLE
Modulo - parametrización (Categorias)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#43]
Al realizar el proceso de actualización se debe solicitar la confirmación de esta acción, los mensajes de confirmación deben llevar el título "Confirmación" y el cuerpo del mensaje: "¿Desea actualizar el registro?" para el proceso de actualización, si se confirma se realiza el proceso de modificación del registro y si se logro realizar con éxito se muestra el mensaje de acción realizada
![1](https://cloud.githubusercontent.com/assets/15731914/11151546/b6757042-89fb-11e5-9755-4eda3b25fabb.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
