### ISSUE TITLE
Reporte de tendencias - por ubicación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#430]
1) La documentación establece que el admin SItur tiene mas filtros como, categoría, nombre del establecimiento,departamento y municipio/ciudad
2) Verificar la estructura de la consulta por que no se logra consultar
![1](https://cloud.githubusercontent.com/assets/15731914/13051205/dd816222-d3c5-11e5-8204-096a20c6b3de.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se evidencia el 1er punto resuelto pero el 2do no se logra verificar

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
