### ISSUE TITLE
Crear actividad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#431]
1) Se ingreso toda la información para crear una actividad sin especificar ninguna imagen y se genero el siguiente error
![1](https://cloud.githubusercontent.com/assets/15731914/13053298/c4126a5a-d3d1-11e5-9efe-7b65e0e0b65c.png)
2) En la consulta de actividades en el reporte falta el nombre de una columna
![1](https://cloud.githubusercontent.com/assets/15731914/13053446/852d1f3c-d3d2-11e5-9c6a-6ccada829a06.png)
3) Al indicar la opción de limpiar se llama a un reporte diferente, verificar a que reporte se debe llamar realimente ya que uno cuenta con imagen y otro no
![1](https://cloud.githubusercontent.com/assets/15731914/13053667/b5cddc48-d3d3-11e5-9952-0f4855f0d32d.png)

**Comment by AndresTello** [comment]
1. El primer punto no es problema de imagen, como se muestra en la imagen es un problema de longitud de caracteres en alguno de los campos, para solucionarlo se configuran los campos para que no se permita degitar un numero superior de caracteres a los que se permiten a nivel de base de datos.

todo el caso fue resuelto.

**Comment by Estepfany** [comment]
Se verifica y se presentaron las siguientes inconsistencias:
1) Se realiza nuevamente la prueba de cantidad a contener cada campo y se genera nuevamente el error, validar cada campo tipo descripción
![image](https://cloud.githubusercontent.com/assets/15731914/13059480/61aa2034-d3f8-11e5-9388-b47cdd6fee31.png)
2) Se modifica un registro antiguo y se adiciona una imagen, según el sistema el proceso se realizo de forma satisfactoria, se realiza la consulta y no se visualiza la imagen asociada
![image](https://cloud.githubusercontent.com/assets/15731914/13059510/932ccd00-d3f8-11e5-9f4d-105e6a7a3388.png)
3) Se intenta filtrar la actividad que se desea consultar y se evidencia que los filtros no están funcionando de la manera correcta, revisar
![image](https://cloud.githubusercontent.com/assets/15731914/13059532/c59d21a4-d3f8-11e5-9c78-957cd0bc702d.png)
4) La imagen en la actividad se solicito como mejora, con el fin de que las actividades del establecimiento fuesen mas atractivas para el turista a la hora de consultar que hacer, estas imagen no se visualizan en la consulta de las actividades, adicionar
![image](https://cloud.githubusercontent.com/assets/15731914/13059590/3287d5de-d3f9-11e5-8153-035d16031580.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indicada y se evidencia que los siguientes puntos aun presentan inconsistencias
2) Se modifica un registro antiguo y se adiciona una imagen, según el sistema el proceso se realizo de forma satisfactoria, se realiza la consulta y no se visualiza la imagen asociada
3) Se intenta filtrar la actividad que se desea consultar y se evidencia que los filtros no están funcionando de la manera correcta, revisar

**Comment by AndresTello** [comment]
el punto 2 se resuelve 
para que se solicita en el punto 3, ni en la documentación ni en los hallazgos reportados se solicito filtros de busqueda para esta pantalla, por ende este punto se toma como una mejora

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
