### ISSUE TITLE
Imágenes de experiencia

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#432]
Se debe verificar si el tamaño destinado para la visualización del detalle de las imágenes que hace parte de la experiencia es adecuado
![1](https://cloud.githubusercontent.com/assets/15731914/13057725/097b394a-d3ec-11e5-82d0-ebeaad0a3e37.png)

**Comment by AndresTello** [comment]
Para este caso se encontró que el contenedor de imagenes se muestra así porque la imagen (fisica) que se cargo la borraron del servidor. se probó con una imgen que si existe y funciona correctamente, por ende no se realiza ningun cambio

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
