### ISSUE TITLE
Reporte de tendencia - por genero

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#433]
Se debe modificar la ubicación del reporte
![image](https://cloud.githubusercontent.com/assets/15731914/13060129/3dd88aec-d3fd-11e5-9496-76414e72f8e2.png)

**Comment by ChristiaanGuzman** [comment]
Solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
