### ISSUE TITLE
Reporte de tendencia - por edad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#435]
Se debe modificar la estructura de un reporte ya que este no se visualiza de forma correcta
![1](https://cloud.githubusercontent.com/assets/15731914/13079154/ce9a39c0-d490-11e5-855a-751211084eb7.png)

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
