### ISSUE TITLE
Enlace de experiencias - favoritos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#436]
En la opción de mis experiencias una vez en la experiencia se indica ver su detalle
![image](https://cloud.githubusercontent.com/assets/15731914/13112118/8a92939a-d557-11e5-9112-5067dbf5d37e.png)
y posteriormente se indica la opción mis favoritos para lo cual envía al usuario nuevamente a mis experiencias y no a mis favoritos como se supone que debería funcionar
![1](https://cloud.githubusercontent.com/assets/15731914/13112474/d21550da-d558-11e5-974a-6a6ce1f27b51.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
