### ISSUE TITLE
Imagen de habitación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#438]
Se realiza la consulta de disponibilidad y se evidencia que al seleccionar la imagen de la habitación se direcciona al usuario al siguiente formulario, corregir no debe enviar al usuario a ningún otro formulario, esto también sucede en responsive
![1](https://cloud.githubusercontent.com/assets/15731914/13113961/61e68976-d55f-11e5-91e6-c1d1c96e6c5a.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
