### ISSUE TITLE
Detalle de establecimiento en favoritos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#439]
Verificar si se puede manejar el mismo estilo de las letras en la información del establecimiento que se consulta en los favoritos, para que se vean como están en la consulta del directorio turístico
![1](https://cloud.githubusercontent.com/assets/15731914/13122609/d387b5b6-d585-11e5-99b8-fa7cc83ddc28.png)

**Comment by ChristiaanGuzman** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/15741537/14465975/9aa8bffc-009a-11e6-9507-83d6f53018ee.png)

para poder que el titulo quede con el tipo de letra de los directorios por favor entrar al html de favoritos y aplicarle la clase que esta seleccionada en la screen ( titleSite ) no lo hago ya que esta lista se arma dinamicamente y no se donde se esta ubicando este html por favor reasignarlo a quien haya hecho favoritos

**Comment by Estepfany** [comment]
Por favor realizar el ajuste indicado por el diseñador

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
