### ISSUE TITLE
Filtro de consulta

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#440]
Se debe cambiar la etiqueta que se ve en el filtro de búsqueda por nombre, cambiar por nombre establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/13144178/f42aaae4-d616-11e5-97e7-cab83d1cccb5.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
