### ISSUE TITLE
Intereses

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#442]
se realiza la consulta de recomendados de hoteles, el sistema informa que se requiere la especificación de los intereses, se intenta acceder al perfil y se arroja el siguiente mensaje
![image](https://cloud.githubusercontent.com/assets/15731914/13146070/f9bca51a-d621-11e5-9e36-4f61f28fa316.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
