### ISSUE TITLE
Consulta de que hacer

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#443]
Se realiza la consulta de la opción que hacer y se evidencia que el responsive no se obtiene todos los resultados esperados, revisar
![1](https://cloud.githubusercontent.com/assets/15731914/13146409/9c1d312a-d623-11e5-8bfa-fb216a054f16.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
