### ISSUE TITLE
Actividades de establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#444]
Se debe quitar el enlace que se encuentra en las imágenes de las actividades del establecimiento ya que están enviado al usuario a un formulario de error
![1](https://cloud.githubusercontent.com/assets/15731914/13149209/9d782d30-d62e-11e5-93ae-60b436046a61.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
