### ISSUE TITLE
Almacenar intereses

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#445]
Se realiza la verificación de almacenar los intereses para aquellos usuarios que no tienen asociado ninguna imagen, se verifica en la bd y el registro no se almacena y se genera el siguiente mensaje
![image](https://cloud.githubusercontent.com/assets/15731914/13156855/9d2500b4-d652-11e5-8c93-3c6d11279c8e.png)

**Comment by AndresTello** [comment]
Para dar solución a este caso, se cambio la forma en que se muestran los mensajes de validación.
Esto se hizo  ya que el error no pudo ser replicado, entonces cuando vuelva a ocurrir, el sistema va a arrojar un mensaje con la exception de java, en ese momento se debe tomar un pantallazo y reportar el caso nuevamente con la imagen tomada, para poder ver que es lo que esta pasando y así poder dar solución final al caso

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
