### ISSUE TITLE
Cerrar slider

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#446]
Se debe implementar la opción para cerrar el slider al dar clic por fuera del recuadro de la imagen, tener en cuenta que esto aplica para todas aquellas pantallas en la cual se pueden desplegar imágenes 
![image](https://cloud.githubusercontent.com/assets/15731914/13178510/33867c78-d6ed-11e5-825e-b942ec90c26e.png)

**Comment by AndresTello** [comment]
Se traslada al area de diseño

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
