### ISSUE TITLE
Mensajes de advertencia en búsqueda

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#447]
En la prueba de los filtros disponibles para la búsqueda de un establecimiento, se utiliza el filtro de "Zona" para lo cual el sistema valida que se cuente con la ubicación, en los filtros no se cuenta con la etiqueta en la cual se indique textualmente que se maneja como ubicación por lo cual se debe adicionar al mensaje de advertencia los siguiente: "Error! Ingrese la ubicación de zona
(Departamento / municipio)"
![1](https://cloud.githubusercontent.com/assets/15731914/13220587/02de97cc-d945-11e5-9541-cedc0a3f1dc4.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verificas la solución indicada, se limpia cache en todos los navegadores utilizados para pruebas y en ninguno se evidencia el cambio

**Comment by AndresTello** [comment]
Se probo sin actuzlizar la versión

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
