### ISSUE TITLE
Cantidad de adultos x habitación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#448]
En la consulta de hoteles se indica las disponibilidad, una vez indicada la fecha de reserva, se indica la cantidad de habitaciones, la cantidad de adultos y la cantidad de niños, la opcion de n° de adultos en el navegador de Exploret no funciona, corregir
![1](https://cloud.githubusercontent.com/assets/15731914/13221524/dd5f3204-d949-11e5-8cd2-64179fcc710d.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
