### ISSUE TITLE
Mas visitados

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#449]
1) Se realiza la consulta sobre los establecimientos de actividades mas visitados y no se evidencia el resultado de la bus queda, verificar
![1](https://cloud.githubusercontent.com/assets/15731914/13222649/e3344048-d94e-11e5-87cf-80307a0e8db1.png)
2) Se intenta realizar la busqueda del establecimiento por actividad y subtipo actividad, se evidencia que la consulta no se esta realizando por el subtipo de actividad

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
