### ISSUE TITLE
Separación de botones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#450]
Se requiere modificar el espacio entre los botones del formulario de hoteles y actividades, que se vean  el mismo espacio entre los botones que se manejo en el formulario de restaurantes
![1](https://cloud.githubusercontent.com/assets/15731914/13223359/e86cc58c-d951-11e5-9702-46f25eafc0bd.png)

**Comment by ChristiaanGuzman** [comment]
solucionado por favor actualizar

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
