### ISSUE TITLE
tope de edad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#452]
Se debe restringir el ingreso de caracteres alfabéticos en el campo tope de edad
![1](https://cloud.githubusercontent.com/assets/15731914/13228458/22703f9e-d96a-11e5-811e-d622abf15e22.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
