### ISSUE TITLE
Puntos de referencia

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#453]
Se debe adicionar una validación en la cual se puede identificar si para el departamento y municipio del establecimiento que se esta actualizando cuenta con puntos de referencia, si no cuenta con ningún punto de referencia se debe informar al usuario que ese departamento y ciudad no cuenta con puntos de referencia parametrizados, se debe informar al usuario indicando que debe gestionar los puntos de referencia que desea adicionar al establecimiento
![1](https://cloud.githubusercontent.com/assets/15731914/13228863/0a15d7ea-d96c-11e5-8e13-09205f261ddd.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
