### ISSUE TITLE
Validación del tipo de pago PSE

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#454]
Se evidencia que falta la validación de la selección del tipo de pago PSE, la validación dice:
"NOTA: Se debe validar si en el tipo de pago solo se indicó la opción PSE, de ser así el sistema debe informar que se requiere adicionar otro tipo de pago, y no permitirá almacenar la información del establecimiento hasta que se cuente con el tipo de pago adicional, esta validación aplica cuando solo se ha indicado el tipo de pago PSE"

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
