### ISSUE TITLE
Consulta de establecimientos - admin

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#455]
En el modulo para consultar los establecimiento se cuenta con la función de disparar la consulta con al menos un filtro especificado, pero cuando es restaurante y se quiere especificar el rango de precios esta función no permite realizar la consulta de manera adecuada, la consulta se debe disparar una vez se cuente con los 2 valores especificado, es decir cuando se cuente con el valor del campo precio máximo, se debería realizar la consulta y no antes ya que no toma el ultimo valor especificado
![1](https://cloud.githubusercontent.com/assets/15731914/13230778/b5f3b14c-d974-11e5-85c6-2515b21b8cdd.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica, se evidencia que permite realizar la especificación de los 2 valores pero la consulta no arroja resultado, verificar este filtro de la consulta ya que no muestra la información de acuerdo a lo especificado en el rango
![1](https://cloud.githubusercontent.com/assets/15731914/13302499/278faf0a-db18-11e5-8051-a02d20f19119.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
