### ISSUE TITLE
Tipo de pago establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#456]
Una vez se termine el proceso de guardar o de modificar se debe limpiar el formulario ya que este esta quedando con la información cargada
![1](https://cloud.githubusercontent.com/assets/15731914/13263677/9775405e-da38-11e5-81bd-de641e4c2adc.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
