### ISSUE TITLE
Disponibilidad crear reserva - adminET 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#457]
Se debe adicionar una validación en la cual se verifique si el establecimiento cuenta con las temporadas requeridas para realizar la reserva; si no se cuenta con una temporada vigente y valida no se debe permitir indicar la opción "Nueva reserva"
![image](https://cloud.githubusercontent.com/assets/15731914/13267092/61000354-da49-11e5-8963-1b7d5850227a.png)

**Comment by AndresTello** [comment]
Resuelto.

Se debe actualizar la versión para poder verificar el caso

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
