### ISSUE TITLE
Reporte de visita de turistas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#458]
Se debe adicionar un botón volver cuando se indique ver los detalles, ya desea el resumen o del detallado
![1](https://cloud.githubusercontent.com/assets/15731914/13301299/41eea906-db12-11e5-8f20-751de024521e.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
