### ISSUE TITLE
Editar reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#459]
Se consulta una reserva, se editar (se cancela la reserva), se termina el flujo de edición y el sistema retorna al formulario de consulta pero se evidencia que el estado queda indicado en el campo con el valor que se indico durante la edición de la reserva, se debe modificar, una vez se termine la edición y el sistema retorne al formulario de consulta este debe tener los campo limpios
![1](https://cloud.githubusercontent.com/assets/15731914/13321753/f13297ba-db9e-11e5-9e3a-7fbefbbf48b2.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
