### ISSUE TITLE
Modulo - parametrización (Productos marcas)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#46]
Al realizar el proceso de eliminación se muestra el titulo de la ventana como "Mensaje", los mensajes de confirmación deben llevar el título "Confirmación" y el cuerpo del mensaje: "¿Desea eliminar el registro?" para el proceso de eliminación
![1](https://cloud.githubusercontent.com/assets/15731914/11154444/588c18a2-8a0d-11e5-8de8-8eb64859cdfc.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
