### ISSUE TITLE
Editar reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#460]
Se consulta una reserva cancelada y se indica almacenar su modificación para lo cual el sistema indica que la reserva esta por fuera de las temporadas publicadas y se evidencia el botón "Reservar", este botón no debe estar visible y  habilitado para una reserva cancelada
![1](https://cloud.githubusercontent.com/assets/15731914/13322207/564b3dc6-dba1-11e5-871e-06ed171d0c38.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se debe verificar el comportamiento del botón de reservar ya que se esta visualizando en la reserva ya creada sin importar el estado de la misma, solo se hace visible si se cumple la validación de no tener una temporada valida
![image](https://cloud.githubusercontent.com/assets/15731914/13355963/fdb6dcb2-dc70-11e5-8cb6-24ca2b201df9.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
