### ISSUE TITLE
contacto del proveedor

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#461]
1) Se consulta los proveedores, se consulta un proveedor, se indica la opción limpiar, y se va la información del proveedor, se indica la opción contacto y permite crear un contacto sin tener un proveedor en el formulario anterior, se debe adicionar una validación en la cual se verifique que el proveedor a asignar el contacto este, si no esta el proveedor se debe informar que se debe contar con el proveedor; tener en cuenta esta validación también para los suministros
![image](https://cloud.githubusercontent.com/assets/15731914/13322743/deddcaee-dba3-11e5-968a-3f84f2c79ada.png)
2)En contacto no se están validando la información marcada como obligatoria (Teléfono)
![1](https://cloud.githubusercontent.com/assets/15731914/13322784/1a3de876-dba4-11e5-9838-839f5880525c.png)

**Comment by AndresTello** [comment]
Resueto.
En el punto 1, Se realiza un cambio. El boton limpiar se oculta en el momento en que se esta viendo el detalle de un registro o creado un registro.
En el punto 2, los teléfonos no son campos obligatorios, entonces lo que se hizo fue quitar el *

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
