### ISSUE TITLE
Administración de Pedido

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#462]
Verificar los sgtes filtros en la consulta de pedidos con los siguientes filtros. fecha de creación desde y hasta, proveedor, clasificación, marca, productos
![1](https://cloud.githubusercontent.com/assets/15731914/13323413/5aff1580-dba7-11e5-8edd-7f22a4bce7af.png)

**Comment by AndresTello** [comment]
Resuelto.

Solo se realiza corrección para los campos fecha desde y hasta, ya que los demas filtros funcionan correctamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
