### ISSUE TITLE
Consulta de mensajes enviados

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#463]
1)Se debe modificar la consulta de los mensajes enviados por el adminET, no se esta mostrado la información correcta, puede ser el reporte o la opción de enviar el mensaje el que presenta la falla, esta se evidencia ya que el mensaje es enviado al usuario diego trujillo y se visualiza el nombre de jeniffer gil
2) la ultima columna no tiene titulo 
3)Se debe permitir consultar los mensajes del mismo día, ejemplo quisiera consultar los mensaje que he enviado el día de hoy
![1](https://cloud.githubusercontent.com/assets/15731914/13324140/6ab95ad2-dbaa-11e5-8be7-d5f68ea5dfcc.png)

**Comment by AndresTello** [comment]
1. Este punto se presenta ya que en la sistema busca en usuario con el correo que se le configuro, pero en la base de datos todos tienen el mismo correo , por ende el sistema toma el priumero que encuentra y este es jeniffer gil.
2. resuelto
3. se verifica y el sistema permite realizar la consulta por un día en especifico

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
