### ISSUE TITLE
Punto de referencia

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#465]
Se debe modificar el mensaje de advertencia del campo descripción ya que en el cuerpo del mensaje se indica que falta el nombre y la descripción que es como se maneja el campo que esta validando
![image](https://cloud.githubusercontent.com/assets/15731914/13325645/bc8e1dc4-dbb0-11e5-8bfd-7d41327692a9.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
