### ISSUE TITLE
Opción de consultar reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#467]
Se debe adicionar el mensaje que indica que esta opción no es valida para establecimientos tipo restaurante y de actividades
![1](https://cloud.githubusercontent.com/assets/15731914/13326630/b34cd918-dbb4-11e5-929d-e604c1752c78.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
