### ISSUE TITLE
Enviar mensaje

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#468]
1) Esta opción no esta funcionando para los establecimientos que son diferente de hotel
2) no se puede realizar envió masivo de mensajes
![1](https://cloud.githubusercontent.com/assets/15731914/13326975/f70641fc-dbb5-11e5-96e2-f25d98e2b3e7.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
