### ISSUE TITLE
Cambio de contraseña

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#470]
Se debe asociar el diseño al formulario de cambio de contraseña
![image](https://cloud.githubusercontent.com/assets/15731914/13330153/7bc48caa-dbc5-11e5-8e01-2d876fd54895.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
