### ISSUE TITLE
Imagenes de establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#471]
Se debe mejorar la visualización de las imágenes que se asocien al establecimiento, ya que actualmente se encuentran en desorden 
![1](https://cloud.githubusercontent.com/assets/15731914/13331024/8cc52254-dbc9-11e5-9cb3-39f49ac0d89b.png)

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
