### ISSUE TITLE
Verificación de publicaciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#472]
Se debe cambiar la visualización de las imágenes que necesitan aprobación, según lo indicado sería un mosaico de imágenes con la información de cada una
![1](https://cloud.githubusercontent.com/assets/15731914/13331135/26765b70-dbca-11e5-814a-050cab1d6b24.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
