### ISSUE TITLE
Verificación de publicaciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#473]
1) Se debe omitir de la lista de establecimientos el valor "Admin"
![1](https://cloud.githubusercontent.com/assets/15731914/13331745/e304fe20-dbcc-11e5-8106-406e111bbba0.png)
2) Unificar las etiquetas, usuario/login
![image](https://cloud.githubusercontent.com/assets/15731914/13332018/06067fc4-dbce-11e5-8fe1-b9421d4c5a49.png)
3) Verificar los filtros de la consulta por que no estan funcionando de la manera correcta
4) Modificar la estructura de la fecha (dd/MM/YYYY)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
