### ISSUE TITLE
Eliminar publicaciones rechazadas 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#474]
Se rechazan 2 imágenes de perfil y se intenta consultar en el formulario de publicaciones rechazadas y estas no se evidencias, se deben traer todas las imágenes que fueron rechazadas incluyendo las imágenes de perfil
![image](https://cloud.githubusercontent.com/assets/15731914/13333805/d863d996-dbd6-11e5-8b93-86b9f2df5c01.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
El reporte no cuenta con toda la información de la imagen relacionada, modificar
![image](https://cloud.githubusercontent.com/assets/15731914/13354252/c50078be-dc67-11e5-824b-3a5c9a2c2f71.png)

**Comment by AndresTello** [comment]
Se decide cambiar esa pantalla colocando solo los filtros de fecha de publicación de la imagen

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
