### ISSUE TITLE
Verificación de publicaciones de perfil

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#475]
Se realiza el proceso de aprobar una imagen de perfil, se realiza el proceso según lo indicado pero al realizar nuevamente la consulta de las publicaciones de perfil se evidencia que el reporte no esta funcionando de manera correcta ya que esta mostrado los registro que están aprobados y no los registros que están pre-aprobados como se supone funciona el reporte
![image](https://cloud.githubusercontent.com/assets/15731914/13353787/aa50672a-dc64-11e5-8f69-90de6580be72.png)

**Comment by AndresTello** [comment]
RESUELTO

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
