### ISSUE TITLE
Validar imagen de perfil

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#476]
A un usuario se le adiciona una imagen, esta imagen debería quedar pre-aprobado y ser visible en el reporte de verificación de publicaciones de perfil pero se evidencio que no se esta tomando en cuenta esta imagen
![image](https://cloud.githubusercontent.com/assets/15731914/13354234/af8e163a-dc67-11e5-8416-0ab6558a0bbb.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
