### ISSUE TITLE
Cargar imágenes a establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#477]
1) Se verifica la carga de las imágenes para el establecimiento y se evidencia que al carga una nueva imagen la imagen que ya estaba relacionada se pierde, ademas de que se pierde el estilo al realizar el proceso de cargar la imagen
2) Adicionar una mensaje de confirmación de la opción de eliminar ademas del mensaje de la acción realizada con éxito 
![image](https://cloud.githubusercontent.com/assets/15731914/13358624/3d41f1f2-dc7e-11e5-919e-f4e2f12df58f.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
