### ISSUE TITLE
Botones estilos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#478]
Se debe verificar y solucionar los estilos de los botones del formulario en el cual se actualizan los establecimientos 
![image](https://cloud.githubusercontent.com/assets/15731914/13361633/e47fbb98-dc8d-11e5-81c7-c2734454f462.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
