### ISSUE TITLE
Modificar contacto

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#479]
Se consulta los contacto y se intenta modificar la información pero el sistema arroja un mensaje que indica que no se puede realizar la modificación, cambiar
![image](https://cloud.githubusercontent.com/assets/15731914/13362097/796dbfe6-dc90-11e5-926e-25de3adf4950.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
