### ISSUE TITLE
Modulo - parametrización (Productos referencias)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#48]
Al realizar el proceso de eliminación se muestra el titulo de la ventana como "Mensaje", los mensajes de confirmación deben llevar el título "Confirmación" y el cuerpo del mensaje: "¿Desea eliminar el registro?" para el proceso de eliminación
![1](https://cloud.githubusercontent.com/assets/15731914/11155079/4eb24ea6-8a11-11e5-84fe-ddcfff33529b.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
