### ISSUE TITLE
Consulta de turistas registrado

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#480]
en la consulta de los turistas registrados una vez especificado los filtros no realiza la búsqueda, se debe verificar la consulta ya que esta debe funcionar con los filtros que se quieran especificar
![image](https://cloud.githubusercontent.com/assets/15731914/13748837/8fed2b14-e9cc-11e5-971a-74082c21f271.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
