### ISSUE TITLE
Modificación de reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#482]
En la documentación se establece que la modificación de una reserva se debe permitir si esta se encuentra en estado igual a pendiente y su cambio debe ser referente al estado, de pendiente a cancelado, se realizo una reserva de tipo  compartida, se indico su edición, indicando el cambio de la fecha de inicio de la reserva para lo cual dejo realizar el cambio, se verifico en la bd y al realizar este proceso la reserva pierde su estado y su cupo, esta modificación no se debe permitir
![image](https://cloud.githubusercontent.com/assets/15731914/13824373/c007097c-eb7b-11e5-996d-0e1a19e67683.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
