### ISSUE TITLE
configuarar disponibilidad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#483]
Se crea a temporada con los periodos y tarifas, posteriormente se elimina y se creaa una temporada pero el sistema esta arrojando el siguiente error
![image](https://cloud.githubusercontent.com/assets/15731914/13857555/5e4c8fe0-ec48-11e5-93e5-7a794975a5bf.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
