### ISSUE TITLE
Opción de menú

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#485]
Se debe modificar la opción de restaurante por "Donde comer" y expericienas y aventura se maneja como "experiencia"como se maneja en la versión Web
![image](https://cloud.githubusercontent.com/assets/15731914/13883759/f75e2602-ecf8-11e5-8117-f6229814f0c6.png)

**Comment by Estepfany** [comment]
una vez termines se lo reasignas a manuel

**Comment by mfmontoya** [comment]
ya está ;)

**Comment by popepatas** [comment]
Por favor revisar de nuevo

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
