### ISSUE TITLE
Acceder a las opciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#486]
Se intenta acceder al sistema sin estar logueado y se visualiza un mensaje indicando que se detuvo la aplicación, esto pasa con las opciones:
- "donde quedarse"
- "que hacer"
- "restaurante"
- "experiencias y aventuras"
  ![image](https://cloud.githubusercontent.com/assets/15731914/13884241/2bbf8042-ecfb-11e5-9bb1-dbfd2cba480a.png)

**Comment by mfmontoya** [comment]
corazón depronto lo que ocurrio en el momento fue que se realizarón cambios en el web services y talvéz la aplicación no estaba actualizada en tu dispositivo ;)

**Comment by popepatas** [comment]
por favor prueba con la ultima version que se te instalo en el celular

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
