### ISSUE TITLE
Botón "Inicia tu aventura"

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#487]
Al ingresar al aplicativo se visualiza un botón "Inicia tu aventura" al dar clic sobre él no se generá nínguna acción, se debe verificar y ajustar según sea el propósito del botón 
![image](https://cloud.githubusercontent.com/assets/15731914/13884570/863f57b2-ecfc-11e5-9fc3-8667b03097bb.png)

**Comment by mfmontoya** [comment]
hola :smile: ya está actualiza app :smile:

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
