### ISSUE TITLE
imagen de usuario

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#488]
Una vez se realiza el proceso de login se verifica que la imagen del usuario no carga, esta una vez se realice el login debe visualizarse en el campo superior derecho de la pantalla
![image](https://cloud.githubusercontent.com/assets/15731914/13884868/ec53b5a6-ecfd-11e5-8b75-4ab9a260ba83.png)

**Comment by mfmontoya** [comment]
hola :smile: ya está corregido actualiza la app, un abrazo :sunglasses:

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
