### ISSUE TITLE
Botón volver

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#489]
Se debe aplicar el área de acción del botón volver que se encuentra en la edición del perfil
![image](https://cloud.githubusercontent.com/assets/15731914/13885171/36c0cc90-ecff-11e5-93e8-c4aadb259d1c.png)

**Comment by mfmontoya** [comment]
corazón ya está :smile:  actualiza la app :smiley:

**Comment by popepatas** [comment]
revisar en la ultima version

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
