### ISSUE TITLE
Modulo - parametrización (Productos referencias)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#49]
Al realizar el proceso de actualización se debe solicitar la confirmación de esta acción, los mensajes de confirmación deben llevar el título "Confirmación" y el cuerpo del mensaje: "¿Desea actualizar el registro?" para el proceso de actualización, si se confirma se realiza el proceso de modificación del registro y si se logro realizar con éxito se muestra el mensaje de acción realizada
![1](https://cloud.githubusercontent.com/assets/15731914/11155137/c75491e8-8a11-11e5-82c5-e0ad96b7f04c.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
