### ISSUE TITLE
Cerrar sesión automáticamente 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#490]
Según lo planteado en la documentación se indica que "La opción que permita salir de la aplicación, deberá realizar de manera automática el cierre de sesión." se evidencia que una vez se sale del aplicativo la sesión continua, se debe modificar y cumplir el requerimiento indicado

**Comment by popepatas** [comment]
por favor cambiar el requerimiento, ya que hoy en día una aplicación que pida inicio de sesión cada vez que se abra se torna algo cansona para el usario final. Se cierra sesión cuando el usuario ejecute esta acción dentro de la aplicación

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
