### ISSUE TITLE
Mi establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#496]
Se debe restringir los caracteres especiales que se ingresan en los campos latitud y longitud, solo se debe permitir el ingreso de un punto, ademas del signo de resta (-)
![image](https://cloud.githubusercontent.com/assets/15731914/13892835/1188bb3a-ed28-11e5-9375-5d293ee3c921.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indicada y se evidencia que permite el ingreso del apostrofe ('), corregir

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by AndresTello** [comment]
ok
