### ISSUE TITLE
Ingreso al aplicativo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#497]
Sin realizar el proceso de autenticacióm se visualiza en el menu los valores null para el nombre y apellido del usuario, si aun no se realiza el proceso de autenticación los valores para esos campos debería quedar vacíos 
![image](https://cloud.githubusercontent.com/assets/15731914/13954239/f84ebd66-f00d-11e5-9ca6-eeb9900a4b45.png)

**Comment by mfmontoya** [comment]
hola compañerita :smile: el problema ya está arreglado, :smile_cat:

**Comment by Estepfany** [comment]
Se verifica la solución indica; el problema persiste, verificar si el problema es a raíz de la conexión inestable que se maneja con el sistema y el medio de la oficina

**Comment by popepatas** [comment]
donde queda la ofinacina ?

**Comment by popepatas** [comment]
esto sucede despues del mensaje de error rojo o del letrero de la aplicacion se ha detenido ?

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
