### ISSUE TITLE
Crear reserva - compartida

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#501]
Se intenta realizar una reserva de tipo compartida, para la reserva se indica los siguientes datos, 
fechas: 23 - 24  de marzo, 15 cupos, hotel la maría, al realizar esta configuración se presenta en siguiente error
![image](https://cloud.githubusercontent.com/assets/15731914/13967765/e28fb42e-f046-11e5-8ffd-9e896d3776d2.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica; ya no se presenta el mensaje de error pero se presento una inconsistencia con los cupos disponibles de la habitación y los digitados para la reserva, se puede ingresar un numero mayor al cupo de la habitación, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/14539871/fe17ac66-0247-11e6-900a-94b49baf126a.png)

**Comment by GiovHernandez** [comment]
ok. al reservar se dispara la validacion

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
