### ISSUE TITLE
Nombre del establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#503]
Se debe ampliar el campo en el cual se visualiza el nombre del establecimiento ya que cuando el nombre del establecimiento ocupa 2 renglones el ultimo es cortado
![image](https://cloud.githubusercontent.com/assets/15731914/13969302/02f99690-f050-11e5-9cd0-8658499f0daf.png)

**Comment by mfmontoya** [comment]
hola compañerita :smile: ya esta arreglado :smile_cat:

**Comment by Estepfany** [comment]
Se verifica la solución indica;  se debe ampliar un poco mas 
![image](https://cloud.githubusercontent.com/assets/15731914/14476397/29bdf4c8-00cd-11e6-8646-438875ccc5d2.png)

**Comment by GiovHernandez** [comment]
se ajusto a lo maximo que se puede

**Comment by Estepfany** [comment]
Se verifica la solución indica, 
=> Resuelto
