### ISSUE TITLE
Comentario - Opinión hotel

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#504]
Se crea un comentario a un hotel el día 22 de marzo, para lo cual el sistema asocia el comentario al hotel pero indica que la publicación se realizo ya hace 20 días
![image](https://cloud.githubusercontent.com/assets/15731914/13969696/6125ddda-f052-11e5-946b-138f9fa43af9.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica; se evidencia que si se da clic varias veces se publicar el comentario la cantidad de veces pulsado el botón, se recomienda adicionar un mensaje de confirmación con el fin de retener la acción
![image](https://cloud.githubusercontent.com/assets/15731914/14535438/7fa82c02-0233-11e6-9acc-61a7a2fe1847.png)

**Comment by GiovHernandez** [comment]
ok, se puso una confirmacion

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
