### ISSUE TITLE
Iniciar sesión

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#505]
Se intenta iniciar sesión con el usuario (chaina / 123) y se muestra un error de sintaxis pero igual permite continuar aun que no muestra los datos del usuario
![image](https://cloud.githubusercontent.com/assets/15731914/13970539/5f8bca52-f057-11e5-8969-aa32dfa06987.png)

**Comment by mfmontoya** [comment]
hola compañerita :smile: ya esta arreglado :+1: actualiza la app :smile_cat:

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
