### ISSUE TITLE
Formulario de logue

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#506]
Se debe ampliar el campo en el cual se contiene la opción de recordar contraseña ya que esta se ve recortada
![image](https://cloud.githubusercontent.com/assets/15731914/13987866/7ff57bf0-f0d7-11e5-9c89-bf90663156c8.png)

**Comment by mfmontoya** [comment]
hola compañerita :smile:  ya está arreglado el problemilla, actualiza la app

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
