### ISSUE TITLE
Logo de aplicación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#523]
Se debe adicionar el logo del aplicativo
![image](https://cloud.githubusercontent.com/assets/15731914/14111004/9a34eada-f58e-11e5-9d8b-c1b9b7e2eeb0.png)

**Comment by popepatas** [comment]
ya se ajusto el logo, de acuerdo al diseñado por christian

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
