### ISSUE TITLE
Modulo - parametrización (Tipos de identificación)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#53]
Al realizar el proceso de eliminación se muestra el titulo de la ventana como "Mensaje", los mensajes de confirmación deben llevar el título "Confirmación" y el cuerpo del mensaje: "¿Desea eliminar el registro?" para el proceso de eliminación
![1](https://cloud.githubusercontent.com/assets/15731914/11156499/3e99275c-8a1a-11e5-85ba-8df0d4e2c6b1.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
