### ISSUE TITLE
experiencia

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#538]
Según la documentación se indica que al iniciar la experiencia se debe verificar que el GPS se encuentre encendido, se verifica y esta validación no se esta realizando, modificar
![image](https://cloud.githubusercontent.com/assets/15731914/14191982/7a4f6820-f760-11e5-8590-43eb7c56db30.png)

**Comment by popepatas** [comment]
listo la validacion de gps, para cuando vea el mapa de ruta y cuando vaya a registrar una parada

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
