### ISSUE TITLE
Imagen de usuario - notificaciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#539]
Se debe mejorar la apariencia de los círculos en los cuales se visualizan la imagen de usuario y la cantidad de notificaciones
![image](https://cloud.githubusercontent.com/assets/15731914/14210358/477b27a2-f7ee-11e5-9099-8dfc3d519096.png)

**Comment by ChristiaanGuzman** [comment]
hola esto es de manuel :)

2016-04-01 9:44 GMT-05:00 Estepfany notifications@github.com:

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
