### ISSUE TITLE
Configuración de notificaciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#543]
Se realiza la modificación de recibir notificaciones (ofertas/novedades), visualmente se ve el cambio realizado, se cierra sección  y se inicia nuevamente pero se evidencia que no almacena el cambio realizado
![image](https://cloud.githubusercontent.com/assets/15731914/14212304/de55f248-f7f7-11e5-88cf-540d565674aa.png)

**Comment by popepatas** [comment]
Listo, quedo refrescandose y ajustandose a lo que el usuario de verdad ha marcado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
