### ISSUE TITLE
Modulo - parametrización (Tipo de acompañante)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#55]
Al realizar el proceso de eliminación se muestra el titulo de la ventana como "Mensaje", los mensajes de confirmación deben llevar el título "Confirmación" y el cuerpo del mensaje: "¿Desea eliminar el registro?" para el proceso de eliminación
![1](https://cloud.githubusercontent.com/assets/15731914/11156776/e6beeb32-8a1b-11e5-855f-ce4f0ded4385.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
