### ISSUE TITLE
Imagen de usuario

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#555]
Se debe verificar la manera en la cual se esta mostrando la imagen de usuario una vez inicia sesión ya que para algunos la imagen parece un ovalo vertical/horizontal y no como debe ser (circulo)
![image](https://cloud.githubusercontent.com/assets/15731914/14261393/003835a8-fa76-11e5-9308-30d40b49a2ae.png)

**Comment by ChristiaanGuzman** [comment]
hola esto es de manuel

2016-04-04 15:06 GMT-05:00 Estepfany notifications@github.com:

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
