### ISSUE TITLE
home - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#556]
1) Del home se debe omitir el icono de Mintic
2) Se debe adicionar un link, el cual debe tener como titulo "Créditos", este debe desplegar una ventana en la cual se contendrán los créditos, estos créditos estarán acompañados de texto e imágenes 
![image](https://cloud.githubusercontent.com/assets/15731914/14263280/5f9799fe-fa7f-11e5-8a6e-4490d39072a9.png)

**Comment by ChristiaanGuzman** [comment]
resuelto, sin embargo que imagenes y que texto deberia aparecer alli?
el modal aparece vacio

**Comment by Estepfany** [comment]
Información:
Nombre o título: Agradecimientos
Texto:
El Sistema de Integración Turistico Regional - SITUR fue construido en apoyo de:
Ministerio de Tecnologías de la Información y las Comunicaciones -MINTIC (LOGO MINTIC)
COLCIENCIAS (LOGO COLCIENCIAS)
2) Las opciones "Centro de ayuda" y "términos y condiciones" deben desplegar una ventana emergente

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by ChristiaanGuzman** [comment]
en terminos y condiciones que deberia ir?

centro de ayudas fue eliminado

**Comment by Estepfany** [comment]
Se debe adicionar el botón de cancelar en las ventanas emergentes

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
