### ISSUE TITLE
Servicios - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#557]
Se deben asociar a todos los formularios en los cuales se visualicen los servicios la opción de mensajes emergentes "tooltip", los cuales deben indicar el nombre del servicio cuando se indique o se de clic en el icono del servicio
![image](https://cloud.githubusercontent.com/assets/15731914/14263798/47cf6876-fa82-11e5-92b7-bd65d2e7abe0.png)

**Comment by AndresTello** [comment]
Resuelto.

Se debe verificar para los establecimientos tipo actividades, si se deben mostrar servicios a estos

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by AndresTello** [comment]
ok
