### ISSUE TITLE
Cargar imagen - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#558]
1) En el formulario de "Registrate" se debe adicionar un botón cancelar el cargue de la imagen ademas de un texto informativo en el cual se indique el tamaño y tipo de archivo permitido para las imagenes (Tipo de formato de la imagen png y jpg)
![image](https://cloud.githubusercontent.com/assets/15731914/14264135/195fffda-fa84-11e5-88ce-6b1945906b23.png)
2) Se debe adicionar a los campos de fecha de nacimiento en el formulario de "Registrate" la palabra "Nacimiento" al campo año y día
![image](https://cloud.githubusercontent.com/assets/15731914/14264221/783bb878-fa84-11e5-9a86-27c3f2475103.png)

**Comment by AndresTello** [comment]
Resuelto.
Se le debe aplicar diseño al formulario de carga de la imagen

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Verificar el punto 2, ya que al seleccionar el mes el label de la lista de días se pierde
![image](https://cloud.githubusercontent.com/assets/15731914/14589702/53988d1e-04ae-11e6-8e2b-6d5ef5b09c1f.png)
Ademas de que si selecciona en el combo del mes el item de valor inicial "Mes nacimiento" el combo de días se llena de valores inválidos como se ilustra en la imagen
![image](https://cloud.githubusercontent.com/assets/15731914/14589729/bbc67ba8-04ae-11e6-97e9-2f035e9c8736.png)

**Comment by AndresTello** [comment]
Resuelto.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by AndresTello** [comment]
ok
