### ISSUE TITLE
Crear reserva - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#559]
Se deben verificar y corregir los campos tipo de documento y municipio:
tipo de documento: Esta lista al indicar la reserva  se queda en blanco, es decir se pierde el texto que indica que información contiene
municipio: una vez seleccionado el departamento esta lista queda si el texto que indica que información contiene
![image](https://cloud.githubusercontent.com/assets/15731914/14264330/14f53734-fa85-11e5-8c89-ab982b47062a.png)

**Comment by AndresTello** [comment]
-Para el campo tipo de identificación se revisó y la aplicación esta funcionando correctamente.
-Para el campo de municipios, el caso quedo resuelto.
Nota el cambio realizado para el campo municipio se hiso en todos los formularios donde se encontró que se manejan los campos departamento y municipio

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by AndresTello** [comment]
ok
