### ISSUE TITLE
Modulo - parametrización (Tipo de acompañante)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#56]
Al realizar el proceso de actualización se evidencia que el registro no se muestra en el formulario y no se puede llevar acabo el proceso
![1](https://cloud.githubusercontent.com/assets/15731914/11157046/4c7b6918-8a1d-11e5-8547-42bc5b7cfed6.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
