### ISSUE TITLE
Consulta "Que hacer"

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#560]
Cuando en el formulario de que hacer se especifica el departamento la lista municipio queda vacia, pierde su titulo y no permite al usuario final identificar visualmente que contiene sin la necesidad de desplegar la lista
![image](https://cloud.githubusercontent.com/assets/15731914/14264968/76b8561c-fa86-11e5-915e-1c4b9156411d.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
