### ISSUE TITLE
Reserva - especificación de niños

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#561]
Se intenta crear una reserva especificando niños pero las lista que se visualizan en el formulario de huéspedes no responden, no permiten la selección de adultos, se debe permitir realizar una reserva con la especificación de niños
![image](https://cloud.githubusercontent.com/assets/15731914/14285853/a95489ce-fb12-11e5-9663-34eff38c767e.png)

**Comment by popepatas** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
