### ISSUE TITLE
Ver mapa - experiencia

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#564]
Al tratar de acceder a la opción para ver el mapa de las paradas se evidencia que se genera un error, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/14294675/da4e9702-fb37-11e5-8c9b-7f8817bd800c.png)

**Comment by GiovHernandez** [comment]
ok, verificar que sergio suba los cambios

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto, ya no se genera el error pero aun se presentan inconsistencia con las coordenadas en el mapa estas inconsistencias se están manejando con el hallazgo 587
