### ISSUE TITLE
Experiencia - búsqueda de establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#565]
Se intenta crear una parada indicando una ubicación que no esta relacionado con ningún establecimiento (que sean hoteles) y el sistema arroja el siguiente error
![image](https://cloud.githubusercontent.com/assets/15731914/14294995/54b94c52-fb39-11e5-86e7-8541412df576.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
