### ISSUE TITLE
Modulo - parametrización (Lista Negra)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#57]
Al realizar el proceso de eliminación se muestra el titulo de la ventana como "Mensaje", los mensajes de confirmación deben llevar el título "Confirmación" y el cuerpo del mensaje: "¿Desea eliminar el registro?" para el proceso de eliminación
![1](https://cloud.githubusercontent.com/assets/15731914/11157928/7a8d8458-8a22-11e5-87cc-7512a30269f4.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
