### ISSUE TITLE
Experiencia (lo de la fecha)

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#570]
1) Al editar la parada en la fecha esta aparece con una fecha pasada, se recuerda que la fecha debe estar dentro del rango de la experiencia, debe ser anterior a la fecha actual o ser la fecha actual
![image](https://cloud.githubusercontent.com/assets/15731914/14299123/47c45a40-fb4e-11e5-8155-8b2db282f1ba.png)
2) Al indicar la opción para editar la información de la experiencia esta se muestra vacia
![image](https://cloud.githubusercontent.com/assets/15731914/14299133/5a695eca-fb4e-11e5-84b5-db40ebc39781.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
Se sigue presentando la inconsistencia
![image](https://cloud.githubusercontent.com/assets/15731914/14439129/35e6030a-ffef-11e5-8ad6-664a98ea0bc2.png)

**Comment by GiovHernandez** [comment]
revizar otra vez

**Comment by Estepfany** [comment]
Se verifica y el problema de las fechas al parecer es por la inconsistencia del Internet, verificar
2) Se verifica la solución indica; Resuelto

**Comment by GiovHernandez** [comment]
el tema se trato con sergio y es por problema de conexion ya que el dato de las fechas se consulta por un webservices

**Comment by Estepfany** [comment]
Se verifica y el error se presenta cuando la conexión no es estable, debió a que este error no se puede manejar se cierra
