### ISSUE TITLE
Iniciar sesión

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#573]
Se debe adicionar una validación en la cual se identifique si se cuenta con una sesión iniciada, si no se cuenta con esta se debe solicitar la sesión para poder continuar
![image](https://cloud.githubusercontent.com/assets/15731914/14364026/94e97ec0-fccc-11e5-9b29-b40f67960150.png)

**Comment by GiovHernandez** [comment]
el usuario puede usar opciones sin estar logeado,  aclarar este punto

**Comment by Estepfany** [comment]
Se verifica con la información del documento y posteriormente se aclara con el líder de desarrollo y se establece que se debe contar con las 2 opciones para navegar en el aplicativo y que se contará con ciertas funciones que solo se realizarán una vez se inicie sesión por lo cual se establece que el funcionamiento actual es correcto
