### ISSUE TITLE
Experiencia - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#575]
Se realiza la consulta de las paradas de una experiencia y se evidencia que si la parada hace referencia a un establecimiento que no esta registrado en la bd no muestra su categoría, corregir
![image](https://cloud.githubusercontent.com/assets/15731914/14366715/d1dcc938-fcd9-11e5-8d4d-9d74270c79be.png)

**Comment by AndresTello** [comment]
Resuelto.

La corrección también se debe aplicar en la parte movil de situr.

**Comment by Estepfany** [comment]
Se verifica y la consulta de las experiencias en la parte web aun presenta inconsistencias, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/14589069/c5c540e0-049e-11e6-9e9d-218bcdd03855.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by AndresTello** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
