### ISSUE TITLE
Notificaciones - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#577]
Actualmente la tabla de notificaciones (str_notificaciones) almacena la ip "192.168.1.40:9898" cuando se genera una notificación, estos datos se deben omitir y solo almacenar desde /Tuga/  hacia adelante

**Comment by AndresTello** [comment]
Resuelto.

Con este caso se encontraron los siguientes errores en la generación de las notificiaciones:
1.cuando se crean ofertas en un restaurante, el sistema crea la notificación con la url de los establecimientos tipo actividades.
2. Cuando la consulta de notificaciones genera algun error el mensaje en el alertify esta mal escrito.

Todos los anteriores hallazgos fueron corregidos

**Comment by Estepfany** [comment]
Verificar por que aun se esta presentando los errores mensionados
![image](https://cloud.githubusercontent.com/assets/15731914/14588893/acfd94a8-049a-11e6-8d23-b7cc16720fd5.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
