### ISSUE TITLE
Experiencia - Ver mapa

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#578]
Se intenta acceder a la opción de ver el mapa de la experiencia "Aventuras con sonia" y se arroja el siguiente error
![image](https://cloud.githubusercontent.com/assets/15731914/14367992/9835fde2-fce0-11e5-92ab-edfb8f42bc4b.png)

**Comment by GiovHernandez** [comment]
ok, verificar que sergio suba el cambio

**Comment by Estepfany** [comment]
Se verifica la solución indica;
Se fueron adicionando paradas y verificando la ubicación que indicaba el mapa, para aquellos establecimientos que se indican como otro, se visualizan en un ubicación errónea, ademas de que se muestra Null, no se puede visualizar paradas entre los marcados como otros y aquellos parametrizados, decir no se puede establecer visualmente la ruta
![image](https://cloud.githubusercontent.com/assets/15731914/14443317/0eb169c2-0004-11e6-833d-3b70222f253a.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
La información de la parada que tiene relacionado un establecimiento que no esta parametrizado se visualiza en el mapa como null
![image](https://cloud.githubusercontent.com/assets/15731914/14590468/de2c9f30-04c0-11e6-8679-12756d1efe6f.png)

**Comment by popepatas** [comment]
corregido, probar con paradas nuevas en el sistema y no las viejas hasta antes de este mensaje

**Comment by Estepfany** [comment]
Se verifica y la información de la parada igual se visualiza en null
![image](https://cloud.githubusercontent.com/assets/15731914/14620592/1be86774-0583-11e6-88be-9cd85943d288.png)

**Comment by popepatas** [comment]
solucionado por favor acercarse al mac mas cercano para el update

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
