### ISSUE TITLE
Configuración de habitación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#583]
Se realizo la consulta de una habitación y posterior se indico cancelar, se evidencio que el campo número de la habitación permanece bloqueado, corregir
![image](https://cloud.githubusercontent.com/assets/15731914/14396945/29e74efc-fda0-11e5-8bc3-d76834809221.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by AndresTello** [comment]
ok
