### ISSUE TITLE
Lista negra

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#588]
Según el documento se establece que el sistema identificara las palabras que se encuentren en la lista negra en la parte de los comentarios, si se cuenta con una palabra de la lista negra se debe vetar el comentario de la parada, se verifica este proceso y no se esta realizando la validación del contenido del comentario
![image](https://cloud.githubusercontent.com/assets/15731914/14429492/4473f110-ffc3-11e5-8005-8b0baf711d9f.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indicada, no permite adicionar una palabra de la lista negra pero se debe adicionar un mensaje en el cual se le indique al usuario que el mensaje fue vetado o borrado por su contenido

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se debe corregir la ortografía del mensaje: "Se han ingresado palabras que no están permitidas. Por favor revise e intente nuevamente"
![image](https://cloud.githubusercontent.com/assets/15731914/14506604/3ffc6b90-0184-11e6-8e7d-1f6c310dc040.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
modificar la palabra revice por revise

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
