### ISSUE TITLE
Lista de municipios

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#590]
Se intenta crear una parada tipo actividad, se selecciona al departamento "San andrés y providencia" y se evidencia que no tiene ningun municipio asociado, se debe adicionar el municipio de San andrés y providencia que sería "Providencia y Santa Catalina Islas"
![image](https://cloud.githubusercontent.com/assets/15731914/14439389/90b9a7cc-fff0-11e5-97dd-75be8b1c641b.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
