### ISSUE TITLE
Municipio - amazonas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#591]
Se debe quitar de la base de datos el registro "Afghass" de la entidad municipio la cual esta relacionada con el departamento del Amazonas
![image](https://cloud.githubusercontent.com/assets/15731914/14442540/e1bdc13a-ffff-11e5-84ee-1f5977956fc0.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
