### ISSUE TITLE
Resultado de restaurantes

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#592]
Se realiza la consulta de los restaurante por ubicación y se evidencia que los restaurantes visibles en el móvil no son los mismos del web, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/14443469/1aac9926-0005-11e6-994e-565ebb6199c0.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
