### ISSUE TITLE
Botones - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#593]
Se deben verificar los botones que son utilizados para realizar la carga de imágenes ya que están por fuera del área visible del botón
![image](https://cloud.githubusercontent.com/assets/15731914/14470667/6bf67cba-00b0-11e6-877c-6c5c968d16c1.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by ChristiaanGuzman** [comment]
resuelto
