### ISSUE TITLE
Consultar experiencia de otro

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#596]
Cuando se realiza la consulta de la experiencias de otros turistas se debe contar con la información completa de las paradas como son la categoría del establecimiento de la parada, ademas de la opción para consultar las imágenes, se debe adicionar la categoría en la información de las paradas y la funcionalidad para ver las imágenes de la misma
![image](https://cloud.githubusercontent.com/assets/15731914/14500916/921c91cc-0169-11e6-9e18-ef77c91ed7a9.png)

**Comment by popepatas** [comment]
Gio ajusto este hallazgo

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
