### ISSUE TITLE
iniciar sesión

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#599]
Se debe adicionar una validación del usuario que realiza el proceso de logueo, en esta validación se debe verificar el rol del usuario en el sistema, si el rol del usuario es diferente de turista el sistema debe arrojar un mensaje de advertencia en el cual se indique que debe iniciar sesión con la cuenta de tipo turista, si no tiene esta cuenta realice el proceso de registro.

**Comment by GiovHernandez** [comment]
el usuario se logea normal y puede realizar reservas u otras actividades menos administrativas

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
