### ISSUE TITLE
Correo de reserva

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#601]
Se realiza una reserva y se evidencia que el mensaje al correo electronico llega 3 veces, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/14575283/60d04e4c-0326-11e6-86d7-b8c30513d3e1.png)

**Comment by GiovHernandez** [comment]
revizar si el correo no lo tienen mas usuarios

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
