### ISSUE TITLE
Donde comer - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#602]
Se debe revisar los iconos de servicio de la plantilla de los restaurantes ya que se visualizan muy juntos
![image](https://cloud.githubusercontent.com/assets/15731914/14589761/801ef55c-04af-11e6-896f-a8bacfb2e9e2.png)

**Comment by ChristiaanGuzman** [comment]
es necesario entrar a la parte que genera estos iconos y colocar la siguiente clase
.ContentFeatures  no lo hago porque no se donde se encuentra este html que se genera dinamicamente aqui envio una screen de donde deberia ir dicha clase sin quitar la clase row, solo agregarla
![screenshot_1](https://cloud.githubusercontent.com/assets/15741537/14642057/948b2e10-060e-11e6-94f8-346dc677e6dd.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
