### ISSUE TITLE
Registrar

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#604]
Si se realiza el proceso por movil se evidencia que no se esta verificando si el nombre de usuario o el correo electrónico especificado ya se encuentra en la base de datos, verificar y corregir

**Comment by GiovHernandez** [comment]
OK

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica y no verifica el correo electrónico registrado, permite crear un usuario con un email ya existente
![image](https://cloud.githubusercontent.com/assets/15731914/14713189/c0d2abfe-07a5-11e6-818a-a429c3cc886d.png)

**Comment by GiovHernandez** [comment]
en las pruebas funciona bien

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
