### ISSUE TITLE
Editar parada

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#605]
Se esta presentando un nuevo error, cuando se quiere editar una parada de un establecimiento existente en la base de datos se esta visualizando como otros con el nombre igual a 0 cero, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/14590658/fdc27dec-04c5-11e6-9dec-d76be82a6f9e.png)

**Comment by GiovHernandez** [comment]
ok
