### ISSUE TITLE
Lista negra

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#608]
Se debe adicionar a la base de datos las palabras existente pero en los diferentes géneros y en plural, ejemplo: actualmente en la tabla existe atolondrado, pero falta atolondrada, atolondradas y atolondrados
NOTA: Realizar la asignación a quien corresponda

**Comment by popepatas** [comment]
por favor tello usar la pantalla para complementar la información

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
