### ISSUE TITLE
Opción de cerrar - web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#610]
Se debe adicionar el botón de cerrar para las ventanas emergentes de crédito y términos y condiciones
![image](https://cloud.githubusercontent.com/assets/15731914/14681877/9e269d08-06e8-11e6-801f-149966976876.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
