### ISSUE TITLE
Reserva - tipo de identificación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#614]
Se debe adicionar una validación para el tipo de documento al momento de realizar la reserva, ya que se realizo el proceso y el sistema indico los datos el usuario pero el tipo de identificación como indefinido y no permitió continuar con el proceso hasta que se modifico este campo por lo cual se solicita adicionar un mensaje en que se indique que se debe especificar el tipo de identificación cuando no se cuente con el campo

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
