### ISSUE TITLE
Parada - detalle establecimiento - mejora de bajo nivel

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#615]
Se cuenta con la funcionalidad en las paradas de una experiencia ir al detalle del establecimiento relacionado en la parada pero una vez en el detalle no se puede retornar a la experiencia, esta seria la mejora a realizar

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
