### ISSUE TITLE
Parada - actividad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#617]
Se intenta crear un parada tipo actividad y se selecciona el tipo, subtipo y la actividad posteriormente se cambia el subtipo pero la actividad no cambia, se debe modificar, si el subtipo o el tipo cambia la información relaciona tambien debe solicitar cambio, ejemplo se  selecciona tipo extrema, subtipo bungge y actividad bungge, pero se cambia el subtipo a mbx y el sistema debe cambiar la actividad, dejar el campo vació para que el usuario realice la selección de la actividad según el subtipo modificado
![image](https://cloud.githubusercontent.com/assets/15731914/14723017/74537d7e-07d4-11e6-9301-8b7c755dfd84.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica y se evidencia que al llegar a la selección del nombre de la actividad no carga la lista y se visualiza el mensaje indicando que no se tiene conexión, este proceso se realiza varias veces y en todas se obtiene el resultado

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se realiza nuevamente la prueba y se genera el mensaje de error de conexión una vez indicado que se almacene el cambio

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
