### ISSUE TITLE
iniciar aplicativo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#622]
Se intenta acceder al aplicativo y se genera el siguiente error
![image](https://cloud.githubusercontent.com/assets/15731914/14746416/2c853e14-0875-11e6-9ff7-106826d91200.png)

**Comment by popepatas** [comment]
esto paso porque se dejo corriendo una version de desarrollo. ya no debe suceder

**Comment by popepatas** [comment]
por favor indicar un diagnóstico de cuando sucede exactamente el error

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
