### ISSUE TITLE
Detalle establecimiento - ofertas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#623]
Al estar en el detalle del establecimiento se indica ver las ofertas, se visualizan las ofertas pero la imagen que acompaña las ofertas es una imagen por defecto, se debe adicionar la imagen del establecimiento al cual le pertenece la oferta
![image](https://cloud.githubusercontent.com/assets/15731914/14787260/3e9321ac-0ac8-11e6-9d3c-06d832daae2c.png)

**Comment by EverHidalgo** [comment]
solucionado. 
se coloca la imagen del establecimiento

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
