### ISSUE TITLE
Menú - experiencia

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#629]
Se debe ampliar el menú que se encuentra en la consulta de experiencias
![image](https://cloud.githubusercontent.com/assets/15731914/14834321/6c4a5122-0bc9-11e6-836d-473f6ccc3585.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
