### ISSUE TITLE
Cargar imagen

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#631]
1) Una vez seleccionada la imagen no se logra generar la imagen en miniatura en el mosaico de imágenes
![image](https://cloud.githubusercontent.com/assets/15731914/14917651/c0e87f60-0de5-11e6-89fd-8c221f248969.png)
2) Una vez cargada la imagen y en el mosaico se selecciona la imagen se espera ver el detalle de la misma pero esta no se logra visualizar
![image](https://cloud.githubusercontent.com/assets/15731914/14917839/90f4d398-0de6-11e6-8562-177eb0f662ac.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
