### ISSUE TITLE
Consultar experiencia - imagenes

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#632]
Al consultar las experiencias de otros y la parada no tiene imágenes asociadas se debe adicionar un mensaje en el cual se indique que no tiene imágenes, "Parada sin imágenes asociadas"
![image](https://cloud.githubusercontent.com/assets/15731914/14918819/7a5aa4b4-0deb-11e6-8394-30be052bf005.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by GiovHernandez** [comment]
ok

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
