### ISSUE TITLE
Nombre de usuario - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#633]
Se debe limitar el número de caracteres que se visualizaran en el nombre del usuario ya que si es mayor a 19 caracteres se baja el contenido de la barra superior
![image](https://cloud.githubusercontent.com/assets/15731914/14927459/a41964da-0e17-11e6-9ac6-0b88ee436365.png)

**Comment by AndresTello** [comment]
Resuelto.

Se decide cambiar la consulta de los datos del usuario, separando los campos (nombre, apellidos), por espacio y tomar la primera palabra que encuentre.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
