### ISSUE TITLE
Formulario - huéspedes

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#634]
En este formulario se encuentra la opción de cerrar la cual debería retornar a la configuración de la consulta para la disponibilidad pero esta opción no funciona
![image](https://cloud.githubusercontent.com/assets/15731914/14927622/a9736330-0e18-11e6-8130-774204776536.png)

**Comment by popepatas** [comment]
solucionado

**Comment by Estepfany** [comment]
se revisa y se evidencia que aun se presenta la inconsistencia

**Comment by popepatas** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
