### ISSUE TITLE
Consulta disponibilidad - Web

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#635]
Se realiza la siguiente configuración para la disponibilidad en el hotel la maría;
fechas: 01/05/2016 - 06/05/2016
cant. habitaciones: 2
1 hab. 1 adulto, 2 niños, edad: 17 - 6
2 hab. 2 adultos, 1 niño. edad: 17
resultado según las edades:
1 habi, 2 adultos y 1 niño
2 habi, 3 adultos y 0 niño
Como resultado se obtiene varias habitaciones pero 2 de ese listado no cumplen con los requisitos, revisar, las habitaciones que no cumplen son:
- nueva habitación
- clásica cambio por aqui

![image](https://cloud.githubusercontent.com/assets/15731914/14928069/43d7485e-0e1b-11e6-9f59-cc4dcbd27b68.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
