### ISSUE TITLE
Tamaño para información de habitación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#637]
Se realiza la siguiente configuración para la disponibilidad en el hotel la maría;
fechas: 01/05/2016 - 06/05/2016
cant. habitaciones: 2
1 hab. 1 adulto, 2 niños, edad: 17 - 6
2 hab. 2 adultos, 1 niño. edad: 17
resultado según las edades:
1 habi, 2 adultos y 1 niño
2 habi, 3 adultos y 0 niño
en una de las habitaciones que se muestran en el listado su información no esta completa, verificar si se requiere ampliar la zona del detalle de las habitaciones
![image](https://cloud.githubusercontent.com/assets/15731914/14928248/5579afec-0e1c-11e6-958a-48870d7ef8d1.png)

**Comment by GiovHernandez** [comment]
se va a crear una regla para no introducir enter en el campo

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
