### ISSUE TITLE
Volver - registrar

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#639]
Se acceder al formulario para realizar el proceso de registro y se indica la opción volver pero esta dirige al usuario al index, modificar se debe dirigir al menú
![image](https://cloud.githubusercontent.com/assets/15731914/14929915/d068b064-0e25-11e6-9411-02147da224d8.png)

**Comment by GiovHernandez** [comment]
ok, el boton volver se cancela ya que tiene el boton del menu para redireccionarlo,

**Comment by GiovHernandez** [comment]
ok, el boton volver se cancela ya que tiene el boton del menu para redireccionarlo,

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
