### ISSUE TITLE
Experiencia imagenes

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#641]
Se debe ampliar el tamaño de la opción de eliminar imagen
![image](https://cloud.githubusercontent.com/assets/15731914/14985015/30dd396e-110b-11e6-9bbe-dcae32b14b0b.png)

**Comment by GiovHernandez** [comment]
ok revizar de nuevo

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
