### ISSUE TITLE
Información de habitaciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#642]
Se realiza el proceso de disponibilidad y se evidencia que las habitaciones no cuenta con información correcta
![image](https://cloud.githubusercontent.com/assets/15731914/15021104/8dcce716-11ea-11e6-9b72-eebdce954e88.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
