### ISSUE TITLE
Mensajes 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#643]
Se debe verificar la lista ya que no se obtiene los usuarios que han consumido en el establecimiento
![image](https://cloud.githubusercontent.com/assets/15731914/15025180/a44ede64-11fd-11e6-9171-cfe4cec72baa.png)

**Comment by AndresTello** [comment]
Se revisa la aplicación y esta funcionando correctamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
