### ISSUE TITLE
Consulta de experiencias publicadas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#645]
Se realiza la consulta de las experiencias publicadas y se evidencia que todas indican la misma ubicación, ademas no se puede comprobar si el filtro funciona correctamente
![image](https://cloud.githubusercontent.com/assets/15731914/15027198/31f43e58-1208-11e6-872b-40323e6e0f2c.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
