### ISSUE TITLE
Establecimiento - restaurante - menú

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#646]
Se intenta ingresar al menú del restaurante de "la cocina de juanita" y se presente el siguiente error
![image](https://cloud.githubusercontent.com/assets/15731914/15027537/fbe83470-1209-11e6-8605-84728246ed29.png)

**Comment by popepatas** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
