### ISSUE TITLE
Información de contacto

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#648]
Se debe verificar la información que se visualiza en la pestaña de contactos ya que la información del número de celular no es correcto
![image](https://cloud.githubusercontent.com/assets/15731914/15028616/4eceed3c-120f-11e6-9e32-37ca5a78ef08.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by Estepfany** [comment]
Se verifica y se evidencia que la información no se muestra de forma dinámica ya que se modifican los tipos de número telefónico y este cambio no se obtiene en el móvil, se colocan los 3 números con fijos 
![image](https://cloud.githubusercontent.com/assets/15731914/15045666/778e2fac-12a1-11e6-9575-9fdbb56bbcb5.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by popepatas** [comment]
Revisar porque la información se quedó pegada. Se hizo lo siguiente para el establecimiento aventuras con luigi:
- Ingrese a tuga como luigi/123 
- Cambie los telefonos como se observa en la web
- ingrese al aplicativo movil  y consulte en luigi
- seguia apareciendo la información vieja de los telefonos 

![image](https://cloud.githubusercontent.com/assets/10553595/15254534/e452b548-18fc-11e6-861d-b2b367ffe481.png)

**Comment by GiovHernandez** [comment]
verificar la ip de la conexion de base de datos  de los webservices del movil ya que trae info que no corresponde a la info que esta en el web, las consultas sql estan bien

**Comment by popepatas** [comment]
corregido en android

**Comment by popepatas** [comment]
arreglado en ios
