### ISSUE TITLE
Barra informativa

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#650]
Se debe separar la barra informativa del dispositivo de la zona requerida de situr
![image](https://cloud.githubusercontent.com/assets/15731914/15082953/33057e68-1390-11e6-8416-23dab885f612.png)

**Comment by popepatas** [comment]
por  no dañar diseño y desarrollo, se opto por dejar en fullscreen para ios, y normal en android

**Comment by popepatas** [comment]
solución comprobada en android e ios
