### ISSUE TITLE
Barra de división 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#651]
Se observa que se cuenta con varias barras de división aun sin contar con varios resultados
![image](https://cloud.githubusercontent.com/assets/15731914/15083168/5514be32-1391-11e6-9456-22f085b6253a.png)

**Comment by popepatas** [comment]
solucionado en los directorios se verificara en donde mas se use este tipo de diseño

**Comment by popepatas** [comment]
solcionado en donde hay tablas directorio y experiencias

**Comment by popepatas** [comment]
comprobado en android y ios
