### ISSUE TITLE
Opción de comentar

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#654]
No se logra identificar esta opción de manera clara ya que aparece solo una pequeña parte del botón
![image](https://cloud.githubusercontent.com/assets/15731914/15083465/f8eb47f0-1392-11e6-8610-57354b62e90c.png)

**Comment by popepatas** [comment]
solucionado

**Comment by popepatas** [comment]
se corrigio en detalle hotel, restaurante y actividades

**Comment by popepatas** [comment]
se descuadra en iphone 4s y en samsung s4 revisar los porcentajes de los altos que no esten con valores en vez de porcentajes.

![image](https://cloud.githubusercontent.com/assets/10553595/15254159/fda0ade0-18fa-11e6-9ef9-cf974d21e19d.png)

**Comment by popepatas** [comment]
solucionado para ios y android

**Comment by popepatas** [comment]
comprobada la solución en android y ios
