### ISSUE TITLE
Servicios de establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#655]
Se verifica la información de los establecimiento, se evidencia que cuando la información                (1er pestaña) es extensa  no se cuenta con la opción del scroll vertica
![image](https://cloud.githubusercontent.com/assets/15731914/15084597/23baebfa-139a-11e6-8423-8d84ed8fcf8b.png)

**Comment by popepatas** [comment]
revisate esto de los servicios pòr favor, se queda como corta la pantalla en altura (height) toca mirar los viewsX

**Comment by popepatas** [comment]
solucionado

**Comment by popepatas** [comment]
comprobado en ios y android
