### ISSUE TITLE
Establecimiento - actividades

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#656]
Se verifica la información del establecimiento y se evidencia que realmente no se esta validando si el establecimiento tiene servicios asociados, ya que muestra el mensaje de que no los tiene parametrizados aun si los tengo asociados
nota: quitar la tilde de la palabra "encontrarón"
![image](https://cloud.githubusercontent.com/assets/15731914/15084741/29fcfe8a-139b-11e6-90c5-74091b28dac2.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by popepatas** [comment]
se verifica la correcion

**Comment by popepatas** [comment]
solución comprobada en android y ios
