### ISSUE TITLE
establecimiento restaurante - ofertas 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#658]
Se debe verificar aquellas consultas en las que se genere varios registros ya que cuando es solo uno igual trae varios separadores
NOTA: esto esta ocurriendo en todas las pestañas en las cuales se pueden esperar varios resultados
![image](https://cloud.githubusercontent.com/assets/15731914/15085160/299e2e5c-139e-11e6-80b1-8946242aa650.png)

**Comment by popepatas** [comment]
solucionado y probado en ios y android

**Comment by popepatas** [comment]
solucion comprobada
