### ISSUE TITLE
Consulta de experiencias publicadas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#659]
Se realiza la consulta a la galería de un parada de una experiencia publicada y se cuenta con la opción de eliminar y permite ejecutarla, quitar esta opción de la consulta de experiencias publicadas
![image](https://cloud.githubusercontent.com/assets/15731914/15085329/3c537286-139f-11e6-9c3f-86129526d16f.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by popepatas** [comment]
solucionado, y verificado en iOS y android
