### ISSUE TITLE
Filtro de paradas

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#661]
Se evidencia que no se permite filtrar las paradas de una experiencia 
![image](https://cloud.githubusercontent.com/assets/15731914/15085557/adfacadc-13a0-11e6-85ce-46fe788030ab.png)

**Comment by GiovHernandez** [comment]
ok

**Comment by popepatas** [comment]
solucionado, solo cambiar el mensaje del dialog que dice "Parada De actividades" por "Parada de actividades" y "Ver Mapa" por "Ver mapa"

**Comment by GiovHernandez** [comment]
ok

**Comment by popepatas** [comment]
solucionado
