### ISSUE TITLE
Eliminar todas las notificaciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#662]
Se intenta realiza la acción de eliminar todas las notificaciones y esta opción no funciona, no realiza ninguna acción
![image](https://cloud.githubusercontent.com/assets/15731914/15086571/5d56ea50-13a7-11e6-9e95-dc4f0b4a2cb4.png)

**Comment by popepatas** [comment]
solucionado

**Comment by popepatas** [comment]
comprobado en ios y android
