### ISSUE TITLE
Gestión de experiencias

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#664]
Una vez logueado con el usuario esnia, se indica la opción del menú experiencia (propias), el sistema cierra el aplicativo
![image](https://cloud.githubusercontent.com/assets/15731914/15086878/9fc753f0-13a9-11e6-9600-c3603fc3a8de.png)

**Comment by popepatas** [comment]
intenta replicarlo gio, mi no me sale.

**Comment by GiovHernandez** [comment]
funciona bien, si no estoy mal esto era lo de las imagenes que arreglamos que en ios las imagenes que o estan en el server fisicamente se revienta

**Comment by popepatas** [comment]
solucionado

**Comment by popepatas** [comment]
comprobado en android y ios
