### ISSUE TITLE
Diseño - Logo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#84]
Al minimizar el tamaño de la ventana del navegador se evidencia que el logo de Situr queda incompleto, se debe minimizar todo el logo no solo parte de el.
![1](https://cloud.githubusercontent.com/assets/15731914/11446956/d5babcb6-950c-11e5-97e1-6879e4c7775e.png)

**Comment by ChristiaanGuzman** [comment]
el logo cambia en su version movil

2015-11-27 13:44 GMT-05:00 Estepfany notifications@github.com:

**Comment by ChristiaanGuzman** [comment]
es la idea que cambie asi, sin embargo tocaria buscar otra disposicion del logo porque esta interfiriendo en los enlaces que estan cerca de el mismo

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
