### ISSUE TITLE
Diseño - Menú

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#85]
En el menú se visualiza una marca que resalta la opción en la cual es encuentre ubicado el usuario, en los navegadores Chrome y Explorer se visualiza en la parte inferior de las opciones pero en Firefox se visualiza en la parte superior, el menú se debe comportar igual en todos los navegadores
![1](https://cloud.githubusercontent.com/assets/15731914/11447690/7ed51930-9518-11e5-9db7-ab4bea748629.png)

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
