### ISSUE TITLE
Consulta establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#87]
Todas las columnas de los reportes deberían tener el título, al ejecutar la consulta de los establecimientos se visualiza que hay una columna que no tiene el título, según la documentación el titulo de esta columna es "Ver detalle"
![1](https://cloud.githubusercontent.com/assets/15731914/11475358/13c88278-974b-11e5-81ad-2967ddd1ef9a.png)

**Comment by AndresTello** [comment]
Resuelto.

Se agrega el titulo de la columna ver detalle

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
