### ISSUE TITLE
Creación de establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#88]
en el campo de verificación de correo electrónico no se debe permitir la acción de copy paste, ya que es un campo de verificación y se requiere que se digite nuevamente la información
![1](https://cloud.githubusercontent.com/assets/15731914/11476917/497acd2e-9753-11e5-8cff-907b65e82773.png)

**Comment by AndresTello** [comment]
Resuelto.
Se bloquea el campo Verficar correo para que no permita pegar lo que se tenga en el porta papeles

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
