### ISSUE TITLE
Creación de establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#89]
Según la documentación se debe validar si ya existe en la parametrización un establecimiento con el mismo tipo y número de identificación del establecimiento: "Si al momento de ingresar los datos para crear un nuevo establecimiento de servicio turístico, el sistema identifica que ya existe uno con el mismo tipo de identificación y con el mismo número de identificación, deberá mostrar al usuario administrador un mensaje alertándolo sobre el suceso: “Ya existe un establecimiento de servicio turístico con esa identificación, desea continuar con el proceso?”. Y al recibir una aceptación sobre la respuesta del mensaje, el sistema permitirá continuar con el proceso de creación del establecimiento de servicio turístico. Este caso puede llegar a darse teniendo para los establecimientos de servicios turísticos que bajo la misma identificación operan en diferentes lugares.", se debe realizar esta validación.
![1](https://cloud.githubusercontent.com/assets/15731914/11477822/c471d410-9757-11e5-9397-fa2772a7e70c.png)

**Comment by AndresTello** [comment]
Se revisa la aplicación y en este punto  esta funcionando correctamente

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
