### ISSUE TITLE
Creación de Cuenta representante

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#90]
en el campo de verificación de contraseña no se debe permitir la acción de copy paste, ya que es un campo de verificación y se requiere que se digite nuevamente la información
![1](https://cloud.githubusercontent.com/assets/15731914/11480527/e45ba298-9765-11e5-97ca-ae62c476c606.png)

**Comment by EverHidalgo** [comment]
solucionado

**Comment by Estepfany** [comment]
zSe verifica la solución indica;
=> Resuelto
