### ISSUE TITLE
Creación de Cuenta representante

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#91]
Al realizar el proceso de creación de cuenta para el representante del establecimiento se ingresa la información indicada y como resultado se visualiza un mensaje vació, el cual no permite identificar si el proceso se logró realizar con éxito
![1](https://cloud.githubusercontent.com/assets/15731914/11480958/76fdb4a4-9768-11e5-82cc-db957429c91c.png)

**Comment by EverHidalgo** [comment]
solucionado.

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
