### ISSUE TITLE
Pantalla de bienvenida

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#93]
Una vez realizado el proceso de logueo del representante se visualiza una pantalla de bienvenida que no esta relacionada con el proyecto SItur, adicionar la pantalla de inicio al aplicativo
![1](https://cloud.githubusercontent.com/assets/15731914/11541595/070d95b6-9901-11e5-9ce0-bad788510693.png)

**Comment by ChristiaanGuzman** [comment]
la pantalla de inicio ya esta asignada

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
