### ISSUE TITLE
Actualizar establecimiento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#94]
En el proceso de especificación de información al indicar el campo "Extensión", se visualiza un mensaje de advertencia en el cual se solicita la zona campo que se encuentra mas adelante, es decir se esta validando antes de llegar a su especificación 
![1](https://cloud.githubusercontent.com/assets/15731914/11542772/fd07d65c-9906-11e5-8062-e9c2fb9179f8.png)

**Comment by AndresTello** [comment]
Resuelto

Se corrige error en la aplicación

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
