### ISSUE TITLE
Actualizar establecimiento - puntos de referencia

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#95]
En la pantalla emergente en la cual se realiza la selección de los puntos de referencia se visualiza el titulo del reporte, ese se debe quitar,
No se cuenta con el formulario en el cual es admin de situr realice la gestión de este parámetro
Nota: como mejora se puede filtar los puntos de referencia al menos por el departamento del establecimiento el cual previamente se conoce 
![1](https://cloud.githubusercontent.com/assets/15731914/11543582/8a6f9bca-990b-11e5-82c1-e865cec0c6fc.png)

**Comment by AndresTello** [comment]
Resuelto.

Se modifica la aplicación al momento de ejecutar la pantalla, ocultando el titulo del reporte

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
