### ISSUE TITLE
Actualizar establecimiento - servicios

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#96]
Se debe mejorar la presentación del reporte en el cual se realiza la selección de los servicios ya que por su tamaño dificulta la selección
![1](https://cloud.githubusercontent.com/assets/15731914/11544665/0b9208c8-9911-11e5-951a-66282e84b8e8.png)

**Comment by AndresTello** [comment]
Se debe revisar por diseño, ya que no es el tamaño de  la imagen, si no la columna de la tabla que genera el reporte

**Comment by ChristiaanGuzman** [comment]
solucionado

**Comment by Estepfany** [comment]
Se revisa y se visualiza la columna de logo, la cual esta vacia, se debe evaluar si la imagen no se va a visualizar se debe quitar la columna o verificar si no se logra cargar la imagen 
![1](https://cloud.githubusercontent.com/assets/15731914/11959233/3b5e3bd8-a89a-11e5-998f-7f680407c217.png)

**Comment by AndresTello** [comment]
Resuelto

**Comment by Estepfany** [comment]
Se debe verificar si es posible modificar el ancho de las columnas de este reporte

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se verifica y se evidencia que la modificación para evitar los scroll no se logro realizar, igual se cierra ya que la forma actual si permite la visualización y asignación de los servicios
