### ISSUE TITLE
Logueo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#97]
Al realizar el proceso de logueo se visualiza el campo contraseña con un titulo diferente, se debe verificar el titulo del campo para visualizar la letra "Ñ"
![1](https://cloud.githubusercontent.com/assets/15731914/11565746/5a9feb46-99ad-11e5-91c0-9b92372b7474.png)

**Comment by EverHidalgo** [comment]
solucionado.

![image](https://cloud.githubusercontent.com/assets/15741670/11755452/95d9aa8e-a020-11e5-8eb8-e643b9baca2f.png)

**Comment by Estepfany** [comment]
Se verifica la solución indica;
=> Resuelto
