### ISSUE TITLE
Cambio de contraseña - admin Situr - adminET

### ISSUE THREAD

**Issue by Estepfany** [popepatas/Situr#99]
Se verifica el proceso de cambiar contraseña con usuario con perfil igual a admin SItur y adminET, el formulario utilizado no realiza las validaciones estipuladas en  la documentación "Validación de contraseñas"
❖ Que tenga al menos 8 caracteres.
❖ Que tenga al menos 2 letras mayúsculas
❖ Que tenga al menos 2 letras minúsculas
❖ Que tenga al menos 2 números
❖ Que tenga al menos 2 caracteres especiales

![1](https://cloud.githubusercontent.com/assets/15731914/11566821/18f376d6-99b2-11e5-9579-bda97e3a1290.png)

**Comment by EverHidalgo** [comment]
solucionado. 
se agregaron las validaciones de la contraseña  a las dos pantallas de cambio de password, tanto para los usuarios como para el administrador

**Comment by EverHidalgo** [comment]
solucionado. 
se agregaron las validaciones de la contraseña a las dos pantallas de cambio de password, tanto para los usuarios como para el administrador
